const toggle=document.querySelector('#menu-toggle'),menu=document.querySelector('#menu');
let menuAnimation=null,menuToken=0;
function setMenu(open){
  const token=++menuToken,from=menuAnimation?getComputedStyle(menu).opacity:(open?'0':'1');menuAnimation?.cancel();
  if(open)menu.hidden=false;toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Close menu':'Open menu');document.body.classList.toggle('menu-open',open);
  document.querySelector('main').inert=open;
  const finish=()=>{if(token!==menuToken)return;if(!open)menu.hidden=true;menuAnimation?.cancel();menuAnimation=null};
  if(matchMedia('(prefers-reduced-motion: reduce)').matches){finish();return}
  menuAnimation=menu.animate([{opacity:from},{opacity:open?1:0}],{duration:500,easing:'linear',fill:'both'});menuAnimation.finished.then(finish).catch(()=>{});
}
function closeMenu(){setMenu(false)}toggle.addEventListener('click',()=>setMenu(toggle.getAttribute('aria-expanded')!=='true'));
menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});const language=document.querySelector('#language-toggle');language.addEventListener('click',()=>{const el=document.querySelector('#languages');el.hidden=!el.hidden;language.setAttribute('aria-expanded',!el.hidden)});const search=document.querySelector('#search-dialog'),input=document.querySelector('#search-input'),results=document.querySelector('#search-results');const sections=[['Family month','family'],['Exhibitions and collection','exhibitions'],['Visitor information','visitor']];function find(){const q=input.value.toLowerCase();results.replaceChildren();sections.filter(s=>s[0].toLowerCase().includes(q)).forEach(s=>{const a=document.createElement('a');a.href='#'+s[1];a.textContent=s[0]+' →';a.onclick=()=>search.close();results.append(a)});if(!results.children.length)results.textContent='No matching section.'}document.querySelector('#search-toggle').onclick=()=>{search.showModal();find();input.focus()};input.oninput=find;document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());const details={kooning:['Willem de Kooning at work','From 9 October. Exhibition preview from the official homepage.','de-kooning.jpg','https://www.rijksmuseum.nl/en/whats-on/exhibitions/willem-de-kooning-at-work'],chintz:['Reviving Chintz','Explore the collection in the Rijksmuseum Shop.','chintz.jpg','https://www.rijksmuseumshop.nl/en/current/reviving-chintz']};document.querySelectorAll('[data-exhibit]').forEach(b=>b.onclick=()=>{const d=details[b.dataset.exhibit];document.querySelector('#detail-title').textContent=d[0];document.querySelector('#detail-caption').textContent=d[1];document.querySelector('#detail-image').src='assets/'+d[2];document.querySelector('#detail-image').alt=d[0];document.querySelector('#detail-link').href=d[3];document.querySelector('#exhibit-dialog').showModal()});

document.querySelector('#mobile-language-toggle').onclick=()=>{const el=document.querySelector('#languages');el.hidden=!el.hidden;document.querySelector('#language-toggle').setAttribute('aria-expanded',String(!el.hidden))};
