function atlasImage(url){return window.AtlasAssets?window.AtlasAssets.attach(new Image(),url):Object.assign(new Image(),{src:url});}
/* Public geometry and stage mechanics are observed; trajectories are locally fitted. */
const modes=['chat','work','code'];
const features={chat:['chat.webp','ChatGPT 日常对话官方界面'],work:['work.webp','ChatGPT Work 演示文稿官方界面'],code:['code.webp','ChatGPT Codex 代码评审官方界面']};
const colors={chat:['#10a0e8','#fcd448'],work:['#04b84c','#10a0e8'],code:['#ceb0fb','#10a0e8']};
const stage=document.querySelector('.mode-experience'),artwork=document.querySelector('.artwork'),mobileArt=document.querySelector('.mobile-artwork'),rail=document.querySelector('.mode-rail'),productWindow=document.querySelector('.mode-window'),images=document.querySelector('.window-images');
const reducedMedia=matchMedia('(prefers-reduced-motion:reduce)'),desktopMedia=matchMedia('(min-width:1024px)'),pointerMedia=matchMedia('(hover:hover) and (pointer:fine)');
let introMode='chat',windowMode=null,scrollMode=null,frame=0,manualSelection=false,pointerInside=false,paused=false,serial=0;
const clamp=v=>Math.max(0,Math.min(1,v)),ease=v=>1-Math.pow(1-clamp(v),3),motionEnabled=()=>!reducedMedia.matches&&!paused,scrollStageEnabled=()=>desktopMedia.matches&&!reducedMedia.matches;
document.querySelectorAll('.action-word').forEach(button=>{const text=button.textContent;button.setAttribute('aria-label',text);button.replaceChildren(...[...text].map((letter,i)=>{const span=document.createElement('span');span.textContent=letter;span.style.setProperty('--letter-color',colors[button.dataset.select][i]);span.setAttribute('aria-hidden','true');return span;}));});
function makeArtwork(mode,mobile,animate){const group=document.createElement('div');group.className='artwork-mode'+(animate?' entering':'');group.dataset.mode=mode;
 for(const [index,layer]of window.CHATGPT_MOTION_LAYERS[mode].entries()){const l=mobile?layer.mobile:layer,anchor=document.createElement('div');anchor.className='motion-layer';anchor.dataset.layer=layer.name;anchor.dataset.parallax=layer.parallax;anchor.style.left=l.x+'%';anchor.style.top=l.y+'%';anchor.style.width=l.width+'%';anchor.style.zIndex=l.z;anchor.style.setProperty('--angle',l.rotation+'deg');anchor.style.setProperty('--delay',index*22+'ms');
  const edge=mobile?l.edge:(l.x<35?'left':l.x>65?'right':l.y<50?'top':'bottom');anchor.style.setProperty('--from-x',edge==='left'?'-32vw':edge==='right'?'32vw':'0px');anchor.style.setProperty('--from-y',edge==='top'?'-32vh':edge==='bottom'?'32vh':'0px');const parallax=document.createElement('div');parallax.className='layer-parallax';const image=atlasImage(layer.file.replace(/star-(large|small)-light\.svg/,(_,size)=>'star-'+size+(matchMedia('(prefers-color-scheme:dark)').matches?'-dark':'-light')+'.svg'));image.alt='';image.draggable=false;parallax.append(image);anchor.append(parallax);group.append(anchor);}
 return group;}
function switchArtwork(container,mode,mobile){container.querySelectorAll('.leaving').forEach(e=>e.remove());const old=container.querySelector('.artwork-mode'),animate=motionEnabled();if(old&&animate){old.classList.remove('entering');old.classList.add('leaving');setTimeout(()=>old.remove(),550);}else old?.remove();const incoming=makeArtwork(mode,mobile,animate);container.append(incoming);if(animate)setTimeout(()=>incoming.classList.remove('entering'),950);}
function setWindowMode(mode){if(windowMode===mode)return;const previousMode=windowMode;windowMode=mode;productWindow.dataset.mode=mode;images.querySelectorAll('.outgoing').forEach(e=>e.remove());const old=images.querySelector('.current');const animate=motionEnabled();const direction=previousMode===null?1:(modes.indexOf(mode)>modes.indexOf(previousMode)?1:-1);const localSerial=++serial;
 if(old&&animate){old.id='';old.setAttribute('aria-hidden','true');old.className='mode-image outgoing';old.style.setProperty('--card-direction',direction);setTimeout(()=>old.remove(),720);}else old?.remove();
 const image=atlasImage('assets/'+features[mode][0]);image.alt=features[mode][1];image.width=1920;image.height=1230;image.id='showcase-image';image.className='mode-image current'+(animate&&previousMode!==null?' incoming':'');image.style.setProperty('--card-direction',direction);images.append(image);if(animate)setTimeout(()=>{if(serial===localSerial)image.classList.remove('incoming');},720);}
function setRailMode(mode){document.querySelectorAll('[data-rail-mode]').forEach(button=>{const selected=button.dataset.railMode===mode,article=button.closest('article'),description=document.getElementById(button.getAttribute('aria-controls'));button.setAttribute('aria-expanded',String(selected));if(article.classList.contains('active')===selected)return;article.classList.toggle('active',selected);description.getAnimations().forEach(a=>a.cancel());if(!motionEnabled()){description.hidden=!selected;return;}const start=description.hidden?0:description.getBoundingClientRect().height;description.hidden=false;const end=selected?description.scrollHeight:0;description.style.overflow='hidden';const animation=description.animate([{height:start+'px',opacity:selected?0:1},{height:end+'px',opacity:selected?1:0}],{duration:360,easing:'cubic-bezier(.22,1,.36,1)'});animation.finished.then(()=>{description.hidden=!selected;description.style.overflow='';}).catch(()=>{});});setWindowMode(mode);}
const mobileModes=document.querySelector('.mobile-modes');
modes.forEach(mode=>{const article=document.createElement('article');article.dataset.mobileMode=mode;article.setAttribute('aria-roledescription','slide');const image=atlasImage('assets/'+features[mode][0]);image.alt=features[mode][1];image.width=1920;image.height=1230;const copy=document.createElement('div');copy.className='mobile-mode-copy';const title=document.createElement('h2');title.textContent=mode==='code'?'Codex':mode==='work'?'工作':'聊天';copy.append(title,...[...document.querySelector('#mode-'+mode).children].map(e=>e.cloneNode(true)));article.append(image,copy);mobileModes.append(article);});
function moveMobile(mode){if(desktopMedia.matches)return;const i=modes.indexOf(mode);mobileModes.scrollTo({left:i*(mobileModes.children[0].getBoundingClientRect().width+32),behavior:motionEnabled()?'smooth':'instant'});}
function selectIntro(mode,source='interaction'){if(source==='interaction')manualSelection=true;const changed=mode!==introMode;introMode=mode;document.querySelectorAll('.action-word').forEach(b=>{const on=b.dataset.select===mode;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));});if(changed||!artwork.children.length){switchArtwork(artwork,mode,false);switchArtwork(mobileArt,mode,true);}if(scrollMode===null)setWindowMode(mode);if(desktopMedia.matches&&reducedMedia.matches)setRailMode(mode);if(source!=='mobile-scroll')moveMobile(mode);}
let mobileRaf=0;mobileModes.addEventListener('scroll',()=>{if(mobileRaf)return;mobileRaf=requestAnimationFrame(()=>{mobileRaf=0;const width=mobileModes.children[0].getBoundingClientRect().width+32,index=Math.max(0,Math.min(2,Math.round(mobileModes.scrollLeft/width)));if(modes[index]!==introMode)selectIntro(modes[index],'mobile-scroll');document.querySelector('#mode-prev').disabled=index===0;document.querySelector('#mode-next').disabled=index===2;});},{passive:true});
document.querySelector('#mode-prev').onclick=()=>moveMobile(modes[Math.max(0,modes.indexOf(introMode)-1)]);document.querySelector('#mode-next').onclick=()=>moveMobile(modes[Math.min(2,modes.indexOf(introMode)+1)]);
function requestScroll(){if(!frame)frame=requestAnimationFrame(updateScroll);}
function updateScroll(){frame=0;const bounds=stage.getBoundingClientRect(),delta=-bounds.top;if(!scrollStageEnabled()){stage.dataset.phase='static';stage.style.setProperty('--intro-opacity','1');rail.inert=false;scrollMode=null;return;}
 const fade=ease((delta+10)/340);stage.style.setProperty('--intro-opacity',1-fade);stage.style.setProperty('--intro-scale',1-.04*fade);
 const phase=delta<0?'intro':delta<340?'handoff':'accordion';stage.dataset.phase=phase;rail.inert=phase!=='accordion';
 if(delta>=340){const next=modes[Math.min(2,Math.max(0,Math.floor((delta-500)/500)))];if(scrollMode!==next){scrollMode=next;setRailMode(next);}}else if(scrollMode!==null){scrollMode=null;setWindowMode(introMode);}
 const parallax=Math.max(-1.3,Math.min(1.3,(innerHeight*.65-bounds.top)/innerHeight));artwork.querySelectorAll('.motion-layer').forEach(layer=>layer.querySelector('.layer-parallax').style.transform=motionEnabled()?'translate3d(0,'+(parallax*Number(layer.dataset.parallax)).toFixed(2)+'px,0)':'none');document.querySelectorAll('.mode-progress').forEach((line,index)=>line.style.transform='scaleX('+clamp((delta-500-index*500)/500)+')');}
document.querySelectorAll('.action-word').forEach(button=>{button.addEventListener('pointerenter',()=>{if(pointerMedia.matches){pointerInside=true;selectIntro(button.dataset.select);}});button.addEventListener('pointerleave',()=>pointerInside=false);button.addEventListener('focus',()=>selectIntro(button.dataset.select));button.addEventListener('click',()=>selectIntro(button.dataset.select));});
document.querySelectorAll('[data-rail-mode]').forEach(button=>button.onclick=()=>{const mode=button.dataset.railMode;if(scrollStageEnabled())window.scrollTo({top:stage.getBoundingClientRect().top+scrollY+520+modes.indexOf(mode)*500,behavior:motionEnabled()?'smooth':'instant'});else{selectIntro(mode);moveMobile(mode);}});
rail.addEventListener('keydown',event=>{if(!['ArrowDown','ArrowUp','Home','End'].includes(event.key))return;event.preventDefault();const buttons=[...rail.querySelectorAll('button')],position=buttons.indexOf(document.activeElement),index=event.key==='Home'?0:event.key==='End'?2:(position+(event.key==='ArrowDown'?1:-1)+3)%3;buttons[index].focus();buttons[index].click();});
window.addEventListener('scroll',requestScroll,{passive:true});window.addEventListener('resize',requestScroll);
function adaptMotion(){document.body.classList.toggle('reduce-motion',reducedMedia.matches);if(!motionEnabled()){document.querySelectorAll('.leaving,.outgoing').forEach(e=>e.remove());document.querySelectorAll('.entering,.incoming').forEach(e=>e.classList.remove('entering','incoming'));}requestScroll();}
reducedMedia.addEventListener('change',adaptMotion);desktopMedia.addEventListener('change',adaptMotion);document.querySelector('#motion-toggle').onclick=event=>{paused=!paused;document.body.classList.toggle('motion-paused',paused);event.currentTarget.setAttribute('aria-pressed',String(paused));event.currentTarget.textContent=paused?'继续演出':'暂停演出';adaptMotion();};
const cycle=setInterval(()=>{if(!motionEnabled()||manualSelection||pointerInside||document.hidden||stage.getBoundingClientRect().top<0)return;selectIntro(modes[(modes.indexOf(introMode)+1)%3],'auto');},6500);window.addEventListener('pagehide',()=>clearInterval(cycle),{once:true});selectIntro('chat','initial');adaptMotion();document.fonts.ready.then(requestScroll);
const cards=document.querySelector('.feature-cards'),previousCard=document.querySelector('#card-prev'),nextCard=document.querySelector('#card-next');function cardControls(){previousCard.disabled=cards.scrollLeft<4;nextCard.disabled=cards.scrollLeft+cards.clientWidth>=cards.scrollWidth-4;}function moveCards(direction){cards.scrollBy({left:direction*(cards.querySelector('article').getBoundingClientRect().width+20),behavior:motionEnabled()?'smooth':'instant'});}previousCard.onclick=()=>moveCards(-1);nextCard.onclick=()=>moveCards(1);cards.addEventListener('scroll',cardControls,{passive:true});window.addEventListener('resize',cardControls);cardControls();
const menu=document.querySelector('.menu'),hamburger=document.querySelector('.hamburger');const menuItems={'功能':['ChatGPT Work','深入研究','圆点','Finances','Health','图像','插件','远程','购物','Slack 和 Teams','站点','空间','学习模式','语音','语音功能（支持视频）'],'学习':['学生','大学教师','教师','研究人员','创作灵感','旅行','日常生活'],'Codex':['概览','定价','Enterprise','联系销售团队'],'Business':['概览','联系销售团队','行业与职能'],'定价':['概览','免费版','Plus','Pro','Business','Enterprise']};
function closeMenu(){menu.hidden=true;menu.classList.remove('mobile-menu');document.body.classList.remove('menu-open');document.querySelectorAll('[data-menu],.hamburger').forEach(button=>button.setAttribute('aria-expanded','false'));}
function openMenu(button,key){closeMenu();menu.dataset.key=key;menu.replaceChildren(...menuItems[key].map(text=>{const link=document.createElement('a');link.href='https://chatgpt.com/zh-Hans-CN/'+({'ChatGPT Work':'work','深入研究':'features/deep-research','图像':'images','站点':'features/sites','语音':'features/voice','学生':'use-cases/students'}[text]||'overview/');link.textContent=text;link.target='_blank';link.rel='noreferrer';return link;}));menu.hidden=false;button.setAttribute('aria-expanded','true');if(desktopMedia.matches){const rect=button.getBoundingClientRect();menu.style.left=rect.left+'px';}else{menu.style.left='';menu.classList.add('mobile-menu');document.body.classList.add('menu-open');hamburger.setAttribute('aria-expanded','true');const back=document.createElement('button');back.textContent='← 返回';back.setAttribute('aria-label','返回主导航');back.onclick=renderMobileRoot;menu.prepend(back);}}
document.querySelectorAll('[data-menu]').forEach(button=>{button.addEventListener('pointerenter',()=>{if(pointerMedia.matches&&desktopMedia.matches&&menu.dataset.key!==button.dataset.menu)openMenu(button,button.dataset.menu);});button.addEventListener('click',event=>{event.preventDefault();openMenu(button,button.dataset.menu);});});
function renderMobileRoot(){menu.dataset.key='root';menu.replaceChildren(...['简介','功能','学习','Codex','Business','定价','下载'].map(text=>{const button=document.createElement('button');button.textContent=text;if(menuItems[text])button.onclick=()=>openMenu(button,text);else button.onclick=()=>{closeMenu();if(text==='简介')window.scrollTo({top:0,behavior:motionEnabled()?'smooth':'instant'});else window.open('https://chatgpt.com/zh-Hans-CN/download/','_blank','noopener');};return button;}));menu.classList.add('mobile-menu');menu.hidden=false;document.body.classList.add('menu-open');hamburger.setAttribute('aria-expanded','true');}hamburger.onclick=()=>{if(!menu.hidden)closeMenu();else renderMobileRoot();};
document.querySelector('header').addEventListener('pointerleave',()=>{if(desktopMedia.matches)closeMenu();});document.addEventListener('click',event=>{if(!event.composedPath().includes(document.querySelector('header')))closeMenu();});document.addEventListener('keydown',event=>{if(event.key==='Escape')closeMenu();});
const account=document.querySelector('#account');document.querySelectorAll('[data-open]').forEach(button=>button.onclick=()=>{account.querySelector('h2').textContent=button.dataset.open;account.showModal();});document.querySelectorAll('dialog .close').forEach(button=>button.onclick=()=>button.closest('dialog').close());const imageDialog=document.querySelector('#image-dialog');document.querySelector('#image-expand').onclick=()=>{imageDialog.querySelector('img').src=document.querySelector('#showcase-image').src;imageDialog.showModal();};

(()=>{const dark=matchMedia('(prefers-color-scheme:dark)'),desktop=matchMedia('(min-width:768px)');function media(){document.querySelectorAll('.window-images img').forEach(i=>{const match=i.src.match(/(chat|work|code)(?:-dark)?\.webp/);if(match)i.src='assets/'+match[1]+(dark.matches&&desktop.matches?'-dark':'')+'.webp';});}new MutationObserver(media).observe(document.querySelector('.window-images'),{childList:true});dark.addEventListener('change',media);desktop.addEventListener('change',media);media();})();

(()=>{const theme=matchMedia('(prefers-color-scheme:dark)');function stars(){document.querySelectorAll('.artwork img,.mobile-artwork img').forEach(i=>{if(/star-(large|small)-(?:light|dark)\.svg/.test(i.src))i.src=i.src.replace(/star-(large|small)-(?:light|dark)\.svg/,(_,size)=>'star-'+size+(theme.matches?'-dark':'-light')+'.svg');});}theme.addEventListener('change',stars);stars();})();
