// Fixed source commit; media bytes are preserved. Generated by scripts/build-asset-sources.mjs.
globalThis.DesignAtlasAssetSources = {
  "commit": "a31ca4e9761d553b31459f013f5dec1ec778a9f8",
  "baseUrl": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/",
  "thresholdBytes": 131072,
  "assets": {
    "demos/apple-product/assets/3d_viewer__hgotqf9hvvee_large_2x.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/apple-product/assets/3d_viewer__hgotqf9hvvee_large_2x.jpg",
      "bytes": 208666,
      "sha256": "423d4bc008da4c4f7506b5243cda183ca37c0b2022ee99970230d91a1fcbde5c"
    },
    "demos/apple-product/assets/action_button__f9p8n5h9xk66_large_2x.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/apple-product/assets/action_button__f9p8n5h9xk66_large_2x.jpg",
      "bytes": 268548,
      "sha256": "53d66073c3849dd0afb5216150aa27ec809ae477bfce4ee907a0b9e4abd95cf8"
    },
    "demos/apple-product/assets/battery_endframe__ds9p2a09r9aq_large_2x.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/apple-product/assets/battery_endframe__ds9p2a09r9aq_large_2x.jpg",
      "bytes": 192789,
      "sha256": "d2c25c0bdfaf105fcdb2d8257d921cff4165bd35ae0be867b567d1bc3ec7f845"
    },
    "demos/apple-product/assets/camera_control__f4t7iottmvyy_large_2x.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/apple-product/assets/camera_control__f4t7iottmvyy_large_2x.jpg",
      "bytes": 354491,
      "sha256": "489d5dbcb6018018574818f44a3f98fb82fb77c28543c25b5fd19662ad45ce09"
    },
    "demos/apple-product/assets/camera_system_startframe__e0gisudnvv2a_large_2x.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/apple-product/assets/camera_system_startframe__e0gisudnvv2a_large_2x.jpg",
      "bytes": 707793,
      "sha256": "428c84b2e68f0b59d13e79da914449f30c3b88872d515a425f8914c7a22df10c"
    },
    "demos/apple-product/assets/camera-system.webm": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/apple-product/assets/camera-system.webm",
      "bytes": 14923281,
      "sha256": "00381bce69d67621f713220a69eda52811a68b18c3537e1294dc005a5d4ae95b"
    },
    "demos/apple-product/assets/chip_endframe__lhkymtfv1uie_large_2x.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/apple-product/assets/chip_endframe__lhkymtfv1uie_large_2x.jpg",
      "bytes": 255586,
      "sha256": "2b8fb8575b918a5174284488b4c3837244029290b65f271e223c240ff2eaaf89"
    },
    "demos/apple-product/assets/color_black__dseo2tvypuc2_large_2x.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/apple-product/assets/color_black__dseo2tvypuc2_large_2x.jpg",
      "bytes": 213558,
      "sha256": "de4def8f73d72e0a91a2473268a7ea7db5c6cb0b83e1dacdd43780a79b5ef2c7"
    },
    "demos/apple-product/assets/color_burgundy__f95it7a6dnyq_large_2x.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/apple-product/assets/color_burgundy__f95it7a6dnyq_large_2x.jpg",
      "bytes": 268556,
      "sha256": "19738f9a11af8561ab66650f71d143e08a5ae2b842f026d5894ffa097d4e26d8"
    },
    "demos/apple-product/assets/color_glacier__fkxlpbz0ruy6_large_2x.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/apple-product/assets/color_glacier__fkxlpbz0ruy6_large_2x.jpg",
      "bytes": 322531,
      "sha256": "63c43fdc992cab64f8f9f3d89a0604ab38bdfc2c75d1c1877b8b9f40d442b4f0"
    },
    "demos/apple-product/assets/color_silver__c0oudn0fzw4m_large_2x.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/apple-product/assets/color_silver__c0oudn0fzw4m_large_2x.jpg",
      "bytes": 308910,
      "sha256": "88bd331d6430190f6dbe194ab2a0ef09ab55d3212558d3e95cc30dae51f14cc3"
    },
    "demos/apple-product/assets/colors_endframe__czfie0zmty4i_large_2x.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/apple-product/assets/colors_endframe__czfie0zmty4i_large_2x.jpg",
      "bytes": 224871,
      "sha256": "28b1b79cbf4caf80dc2c4c9d477bd6877ae48fca4268d290207a119477f5c91d"
    },
    "demos/apple-product/assets/durability__gluy1en01nqm_large_2x.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/apple-product/assets/durability__gluy1en01nqm_large_2x.jpg",
      "bytes": 303511,
      "sha256": "9820a433515a6784c0f63ab40823a3d9af32d6d4bb6407020e9ecd7c6cf6de7d"
    },
    "demos/apple-product/assets/dynamic_island_endframe__edszr68pgo66_large_2x.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/apple-product/assets/dynamic_island_endframe__edszr68pgo66_large_2x.jpg",
      "bytes": 228153,
      "sha256": "ae8a278d0913cfc06fd9fd223611a89e1263cfc22c63f2000cc13f4c47ee0001"
    },
    "demos/apple-product/assets/large_2x.mp4": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/apple-product/assets/large_2x.mp4",
      "bytes": 7447723,
      "sha256": "fdb3b7dc1a225c0403a9da728e3713f84fafe6ab1f920a4315e13eb24ee7bb49"
    },
    "demos/apple-product/assets/main_camera_endframe__fcjfhs06rdme_large_2x.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/apple-product/assets/main_camera_endframe__fcjfhs06rdme_large_2x.jpg",
      "bytes": 217444,
      "sha256": "a7fe61cb9c48da8bfb0ca5d2cb062bee99ed034f0782a396537185d8ce8d0fe4"
    },
    "demos/apple-product/assets/size__ufk3tqa1f5e2_large_2x.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/apple-product/assets/size__ufk3tqa1f5e2_large_2x.jpg",
      "bytes": 327084,
      "sha256": "a6c284b2c698db02d833f2961ecad3ed7e0d13c25e7e61dc22b16d9f6337749a"
    },
    "demos/apple-product/assets/viewer_aperture_endframe__2jpki8xah2au_large_2x.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/apple-product/assets/viewer_aperture_endframe__2jpki8xah2au_large_2x.jpg",
      "bytes": 184099,
      "sha256": "80acb0ce71af410fbbeefe2921c90ad21542804fc0be3eaa42973f6bbcbf617f"
    },
    "demos/arknights-world/assets/amiya-e2.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/amiya-e2.png",
      "bytes": 3379229,
      "sha256": "8fa6ef35c4384a1d39db7f5d706a1b903c1d498b335dbe43f1196286606c5b17"
    },
    "demos/arknights-world/assets/amiya-thumb.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/amiya-thumb.png",
      "bytes": 143206,
      "sha256": "01a573d2b8c4a6be80d07dc0b90ff09d218829b21624d800f536b4b31038251e"
    },
    "demos/arknights-world/assets/amiya.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/amiya.png",
      "bytes": 584564,
      "sha256": "e59f307fd5efa7a26806dc687d5fbc89fc203532f825dc8eec0d4ebec02ec0aa"
    },
    "demos/arknights-world/assets/animation.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/animation.jpg",
      "bytes": 251727,
      "sha256": "9edd6dddd4eb6e7c4f92839fac954d9cd0160d4668ed081625e9162e0908c906"
    },
    "demos/arknights-world/assets/background.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/background.jpg",
      "bytes": 138403,
      "sha256": "e44c737212d52aa9e4f4be09322bf73bbcf8c6147f8c717e6cfc7bfdb48ceb10"
    },
    "demos/arknights-world/assets/bgm.mp3": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/bgm.mp3",
      "bytes": 3130419,
      "sha256": "3ea3799565739b4fecd05ff986a21d77a44c09b9c6000e1aff0bc6144e870ed1"
    },
    "demos/arknights-world/assets/chen-e2.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/chen-e2.png",
      "bytes": 3842673,
      "sha256": "6abe7afc6f2cf9e46e3e0d5c8ce8dba7b0e057869b7ccc5da416b43abae7be35"
    },
    "demos/arknights-world/assets/chen-thumb.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/chen-thumb.png",
      "bytes": 134289,
      "sha256": "e1ba9ca7df65145725b372daf0fbc5a266053ad747e2a5cefa5a5b8e0bc82b14"
    },
    "demos/arknights-world/assets/chen-voice.mp3": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/chen-voice.mp3",
      "bytes": 160134,
      "sha256": "188055ebdc4722f05d881e547d76be2572ddb4ff6041ce75ff8e3805bd4d7d9a"
    },
    "demos/arknights-world/assets/chen.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/chen.png",
      "bytes": 426774,
      "sha256": "a14f1e8403e672ff0321b74de6907574142d38dc63319faf3ccc7b122abbe759"
    },
    "demos/arknights-world/assets/common_mask.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/common_mask.png",
      "bytes": 452646,
      "sha256": "743f20f36ef3fbc101388e209193f98862eef6040544eea74836f3758fced213"
    },
    "demos/arknights-world/assets/home-poster.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/home-poster.jpg",
      "bytes": 273961,
      "sha256": "ae3941e8d532221bf576dbbfe94a424c3c55ddbda2187ebc5a2800b23410e393"
    },
    "demos/arknights-world/assets/home.mp4": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/home.mp4",
      "bytes": 4191430,
      "sha256": "af52b137550ae4bfa01463c6658866f7fd1d78c99377e604a78cbd663fbc7187"
    },
    "demos/arknights-world/assets/infected.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/infected.png",
      "bytes": 186849,
      "sha256": "65904ef8f3921be0797471cad6a5faf612fd5d513590bddd7528d884871931bb"
    },
    "demos/arknights-world/assets/integrated_strategies_m.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/integrated_strategies_m.png",
      "bytes": 223218,
      "sha256": "b615a9af304501daf5a739e80773d1deb10fb27ef7cade4c0283ebb2dfc74287"
    },
    "demos/arknights-world/assets/integrated_strategies.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/integrated_strategies.png",
      "bytes": 637476,
      "sha256": "b0e3a8b56c513ee418a55ed7e091b3436abc0ba840c7dce001eee8ddfb8f4a70"
    },
    "demos/arknights-world/assets/kaltsit-e2.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/kaltsit-e2.png",
      "bytes": 2574398,
      "sha256": "cc75f8d39869df5202c320c4635cefae3d5d2ddfcd92dbd854246f8f02cbf702"
    },
    "demos/arknights-world/assets/kaltsit-thumb.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/kaltsit-thumb.png",
      "bytes": 140163,
      "sha256": "23b374fc0eae7b9722cf91388119e301d32cb62a9b7f928eef917b29426bb16c"
    },
    "demos/arknights-world/assets/kaltsit-voice.wav": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/kaltsit-voice.wav",
      "bytes": 1957836,
      "sha256": "9c1e879e3f84d2d3652403ad1d1cdc1ffbbf6dee5cb319434269a86189809cf3"
    },
    "demos/arknights-world/assets/kaltsit.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/kaltsit.png",
      "bytes": 1171898,
      "sha256": "55541275ebb108bf57812b604480b1d939545d78f12f2c3647c5a66c86654d34"
    },
    "demos/arknights-world/assets/news-yesterday-sea.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/news-yesterday-sea.jpg",
      "bytes": 286981,
      "sha256": "18dd2cb64bd2640d68ad12109ddd3573a42909f95f126ddf185a832020d9a576"
    },
    "demos/arknights-world/assets/nomadic_city.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/nomadic_city.png",
      "bytes": 213422,
      "sha256": "36102181a055a99923963d147f799abbc067fad4a558fcca1e342bb143f36e42"
    },
    "demos/arknights-world/assets/operator_active.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/operator_active.png",
      "bytes": 147239,
      "sha256": "145bfba0aeeb4f26816644a84e46bc7e355dae788693f9bc1a5eb08284df6ba7"
    },
    "demos/arknights-world/assets/originium_arts.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/originium_arts.png",
      "bytes": 196498,
      "sha256": "7892c87ede064fa5ec5cd8baaaca22f07a888049a5de62b5d2722bdd4b861ec6"
    },
    "demos/arknights-world/assets/originiums.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/originiums.png",
      "bytes": 147748,
      "sha256": "4c6b8d7adb3b13a2cd5b3afed7a80e7db9c0a93adfe716772ae54bfd6bba1ae5"
    },
    "demos/arknights-world/assets/reclamation_algorithm_m.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/reclamation_algorithm_m.png",
      "bytes": 249470,
      "sha256": "5e7587597311a65bf8e122e140ac7c56c7c43f00d9ebf5ab54321d453ce30070"
    },
    "demos/arknights-world/assets/reclamation_algorithm.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/reclamation_algorithm.png",
      "bytes": 697825,
      "sha256": "8f37c9fb1cf35bf31d1c183f8f9b209a825d0f7f891c65dd6cf9bc46667c28a5"
    },
    "demos/arknights-world/assets/video_active.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/arknights-world/assets/video_active.png",
      "bytes": 149048,
      "sha256": "cdf992ef7b557d1c61a11f7c8e474b788253e8d6a6d0d5b9d10b3da28bd5965e"
    },
    "demos/blue-archive/assets/01.bd71aff1.wav": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/blue-archive/assets/01.bd71aff1.wav",
      "bytes": 697882,
      "sha256": "18e8fa390f662f0a20637eb36124aa61f8f59f86677b2a2fda4cb0b5116d1485"
    },
    "demos/blue-archive/assets/02.73ff260c.wav": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/blue-archive/assets/02.73ff260c.wav",
      "bytes": 398650,
      "sha256": "de5cde3175587a67d9b39d941eb698a8522a04c4a59dde6e5d045b6e66dd56c4"
    },
    "demos/blue-archive/assets/03.83e84e04.wav": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/blue-archive/assets/03.83e84e04.wav",
      "bytes": 786016,
      "sha256": "45685d4770aab4bab7295d5c09bfff893daa6fe41d894f6e07d9e866a43076f3"
    },
    "demos/blue-archive/assets/04.99faa124.wav": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/blue-archive/assets/04.99faa124.wav",
      "bytes": 503652,
      "sha256": "edb08c1d5198f3d67dbd09a2bdc23fbec4bb10274a4172daee270fd0c172eaed"
    },
    "demos/blue-archive/assets/bg.555a8a72.mp4": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/blue-archive/assets/bg.555a8a72.mp4",
      "bytes": 1602930,
      "sha256": "f2e3d8ddc504774c720c625f68cf89dddb25ecbcb4efe358fc80aa737834ef10"
    },
    "demos/blue-archive/assets/character-background-mobile.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/blue-archive/assets/character-background-mobile.png",
      "bytes": 809436,
      "sha256": "41917c5e8a78713bb1e338aa54afcf4e72525d1de0856c80289c184a95c60daf"
    },
    "demos/blue-archive/assets/character-background.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/blue-archive/assets/character-background.png",
      "bytes": 453388,
      "sha256": "f348448c6e1a4542cebafbb1d939bc875b63df573738086ea94159735f2d3577"
    },
    "demos/blue-archive/assets/hoshino.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/blue-archive/assets/hoshino.png",
      "bytes": 340576,
      "sha256": "07eb5a84d715cb62dc1cfdcc63517381082b833fe0c9f2a4761eab872ad77cea"
    },
    "demos/blue-archive/assets/nonomi.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/blue-archive/assets/nonomi.png",
      "bytes": 288977,
      "sha256": "53d12909adb258dce9e6e0a588d00273c13543829b1100067cb6a6d1206be6ea"
    },
    "demos/blue-archive/assets/serika.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/blue-archive/assets/serika.png",
      "bytes": 183477,
      "sha256": "99531fc0fc4cc39dd9962b83ce0fbfe427393ada397f1e3b2e4b05bada55468b"
    },
    "demos/blue-archive/assets/shiroko.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/blue-archive/assets/shiroko.png",
      "bytes": 318153,
      "sha256": "228a1e53b94ef0ab014f05c160c776d5aa61956f3b886de15e89c0cc4c63222d"
    },
    "demos/chatgpt-platform/assets/code-dark.webp": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/chatgpt-platform/assets/code-dark.webp",
      "bytes": 171766,
      "sha256": "c61448ec07cf0cab5106ea7487c813e9229c1ee9253e14446d3d575cb230d049"
    },
    "demos/chatgpt-platform/assets/code-light.svg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/chatgpt-platform/assets/code-light.svg",
      "bytes": 159885,
      "sha256": "edc0f72129f34fc7056c4cdac524570b5ecfbe77561ea933b11d915c5b235a75"
    },
    "demos/chatgpt-platform/assets/code.webp": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/chatgpt-platform/assets/code.webp",
      "bytes": 152266,
      "sha256": "abcf7a498fd22236ee99211faa06106f1b6f3d1a81e9417587152fbae1ba303c"
    },
    "demos/chatgpt-platform/assets/OpenAISansSC-Variable-002.woff2": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/chatgpt-platform/assets/OpenAISansSC-Variable-002.woff2",
      "bytes": 207168,
      "sha256": "eeeaec298e7d0b6915426426d3c1b0930716cf3504e1aa8c0a2fed8e363cbdf5"
    },
    "demos/chatgpt-platform/assets/OpenAISansSC-Variable-003.woff2": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/chatgpt-platform/assets/OpenAISansSC-Variable-003.woff2",
      "bytes": 407616,
      "sha256": "ee710f03293ddde72265975274fbe026ed46ae7edfb91784d15a6f590f9f893b"
    },
    "demos/claude-platform/assets/cowork.mp4": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/claude-platform/assets/cowork.mp4",
      "bytes": 3811999,
      "sha256": "4e8fa322a4948bba7c5ff1cc461a63714f7b682b4f4ec86d6261eb2a50a6dd62"
    },
    "demos/claude-platform/assets/serif.woff2": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/claude-platform/assets/serif.woff2",
      "bytes": 175356,
      "sha256": "e96fe97bb7ba2190a9a227d27380e0c79894408bfc6acea5a511774d93a16f69"
    },
    "demos/design-sight/assets/A-POC_2121_G3_2026_JAXAproject_KV_W1280H720px_ToGO-thumb-1280xauto-8340.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/design-sight/assets/A-POC_2121_G3_2026_JAXAproject_KV_W1280H720px_ToGO-thumb-1280xauto-8340.jpg",
      "bytes": 877705,
      "sha256": "face730bf3f06da2c7cbad1128b52ef736bddc2b91d11827ee727870fb2fe30a"
    },
    "demos/design-sight/assets/about_directors-thumb-500x333-5880.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/design-sight/assets/about_directors-thumb-500x333-5880.jpg",
      "bytes": 169350,
      "sha256": "0970ca2b5b2c114f1a944b2514ca03810e2735ddf9c3b7369028987a519d939c"
    },
    "demos/design-sight/assets/slide_hojoki-thumb-1280xauto-8283.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/design-sight/assets/slide_hojoki-thumb-1280xauto-8283.jpg",
      "bytes": 622044,
      "sha256": "1fef9a68f7dc8a48e2db43eb134003b451345c3285713a78ef27b30f15dbaba8"
    },
    "demos/design-sight/assets/top_information-thumb-630xauto-7221.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/design-sight/assets/top_information-thumb-630xauto-7221.jpg",
      "bytes": 245621,
      "sha256": "bb4ea2ae0555e9c33e04a1f404d393163aa2200f24c4ddf35aa31e0a3fe6c472"
    },
    "demos/design-sight/assets/topweb_type_xvii-thumb-630xauto-8332.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/design-sight/assets/topweb_type_xvii-thumb-630xauto-8332.jpg",
      "bytes": 165118,
      "sha256": "09005d14e42553a201e2d2571f16b618ad947faccd2f519b492a72a694f9991d"
    },
    "demos/digital-dunhuang/assets/mural-257.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/digital-dunhuang/assets/mural-257.jpg",
      "bytes": 250670,
      "sha256": "c9e1edbbad9a63cb0393f18df875f6d90edccf12fefaf20c23ce07efc3cd55c0"
    },
    "demos/endfield-industrial/assets/aic.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/endfield-industrial/assets/aic.png",
      "bytes": 690429,
      "sha256": "b5471e709c1592deaffa543830f1c2468fc9f7937bfed2b35fdba38c927b1938"
    },
    "demos/endfield-industrial/assets/si-display.webp": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/endfield-industrial/assets/si-display.webp",
      "bytes": 569554,
      "sha256": "74670101097f7e2265fb4cab96b4d5e2fd0f45c714f72ada7fd2ee68bba105db"
    },
    "demos/endfield-industrial/assets/si.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/endfield-industrial/assets/si.png",
      "bytes": 19539177,
      "sha256": "b4b64796e94633d9d572d34be91645478f335d5adcaee066a3521ee08f5614a4"
    },
    "demos/fuji-rock/assets/4AS4QwyCS1efKr65S46uaPdnyKlI2c2PJ46xsn4spc.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/fuji-rock/assets/4AS4QwyCS1efKr65S46uaPdnyKlI2c2PJ46xsn4spc.jpg",
      "bytes": 195099,
      "sha256": "700792c3e539966484c7c7ddd455021467b7821a5544cb9405545718e12ee026"
    },
    "demos/fuji-rock/assets/4AS4QwyCS1efKr65S46uaPdnyKlI2c2PJ46xsn4ssp.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/fuji-rock/assets/4AS4QwyCS1efKr65S46uaPdnyKlI2c2PJ46xsn4ssp.jpg",
      "bytes": 175940,
      "sha256": "b19c3fb469aad894b5947077577c781bc51a39d78f4b252e47bd57790557aa97"
    },
    "demos/fuji-rock/assets/aTIiCxTF0FbTasM3Dpxb7B9pdYwG5HI5l4x2tLfjpc.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/fuji-rock/assets/aTIiCxTF0FbTasM3Dpxb7B9pdYwG5HI5l4x2tLfjpc.jpg",
      "bytes": 259735,
      "sha256": "eeb09021388eb39b9b629bd19c9875a129de974cc72d7d32fe7a1e2de434d465"
    },
    "demos/fuji-rock/assets/aTIiCxTF0FbTasM3Dpxb7B9pdYwG5HI5l4x2tLfjsp.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/fuji-rock/assets/aTIiCxTF0FbTasM3Dpxb7B9pdYwG5HI5l4x2tLfjsp.jpg",
      "bytes": 334202,
      "sha256": "7a85aabbe58ec7526cbdfb896193b6d2baa4759df9696313a3d821fe2e7bf67c"
    },
    "demos/fuji-rock/assets/wtdrdF0xM8yaZQoCtKBNOnud4e7Zf5LgOWNPfXVJpc.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/fuji-rock/assets/wtdrdF0xM8yaZQoCtKBNOnud4e7Zf5LgOWNPfXVJpc.jpg",
      "bytes": 193956,
      "sha256": "5cc2abaf680c53d253b6aacac0b359f3aeed7576ee150b19b9c0a5cba66dc4c3"
    },
    "demos/fuji-rock/assets/wtdrdF0xM8yaZQoCtKBNOnud4e7Zf5LgOWNPfXVJsp.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/fuji-rock/assets/wtdrdF0xM8yaZQoCtKBNOnud4e7Zf5LgOWNPfXVJsp.jpg",
      "bytes": 185883,
      "sha256": "d6dfcd3ce75298613f989eb15834c236bade9c3cd47efd4badacb4f6971b9c98"
    },
    "demos/genshin-world/assets/calendar.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/genshin-world/assets/calendar.jpg",
      "bytes": 592436,
      "sha256": "40d350f541c823ead20f9563833cf9349cd0d888565c8172d641d5acdfb991d5"
    },
    "demos/genshin-world/assets/character-1.webp": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/genshin-world/assets/character-1.webp",
      "bytes": 181604,
      "sha256": "7b187102c054c90f7514a6d602c9e8ba1bff95a6cc1cb9c1b0bfeb13c25a6fc7"
    },
    "demos/genshin-world/assets/character-2.webp": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/genshin-world/assets/character-2.webp",
      "bytes": 238726,
      "sha256": "2f6e3c048d15c79ba0f9f82d4a27c82d8b6d5061f1fd5f24ff6d5e3f8abecbb0"
    },
    "demos/genshin-world/assets/character-background-2.webp": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/genshin-world/assets/character-background-2.webp",
      "bytes": 333210,
      "sha256": "0356766903c851de7466280ec08689a72e0ff306c092e9af76241045694e2bb4"
    },
    "demos/genshin-world/assets/character-background.webp": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/genshin-world/assets/character-background.webp",
      "bytes": 225730,
      "sha256": "5a288303e1a1c5c571d362cf476d567be909202408438bb1c0bcd2430321c35a"
    },
    "demos/genshin-world/assets/hero-poster.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/genshin-world/assets/hero-poster.jpg",
      "bytes": 179117,
      "sha256": "e8bc3407e9c61b29b31ec4c7cf59e70b89da2922bfd9f3d2a59d9cfbe5e443a1"
    },
    "demos/genshin-world/assets/hero-title.webp": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/genshin-world/assets/hero-title.webp",
      "bytes": 341036,
      "sha256": "5a570e5c0be6a22604e870900561ea55710d89ef2b5dcd7c72c1e9b504f27705"
    },
    "demos/genshin-world/assets/hero.mp4": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/genshin-world/assets/hero.mp4",
      "bytes": 3598213,
      "sha256": "ce8f953bf73f2a0a559ece45b6b0dd31a6ed82d3f1df48d13c4943f77d4a1b8d"
    },
    "demos/genshin-world/assets/page-background.webp": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/genshin-world/assets/page-background.webp",
      "bytes": 425002,
      "sha256": "6f0c0c16718de3407d563a46ffc9df1c6a83493567f8cbb8d30b38b8e35afb38"
    },
    "demos/genshin-world/assets/voice-2-3.mp3": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/genshin-world/assets/voice-2-3.mp3",
      "bytes": 181484,
      "sha256": "aef978ef22fdaf310246bda962beec1bcef1773f09719a9efa129873f2fbd2b6"
    },
    "demos/google-material/assets/google-symbols-300-600.woff2": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/google-material/assets/google-symbols-300-600.woff2",
      "bytes": 1407616,
      "sha256": "2a545dc277112a0cbb10c3a8d1012cfe3356741c92d980dc1b1a880ea1fcf50c"
    },
    "demos/google-material/assets/hero-poster.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/google-material/assets/hero-poster.png",
      "bytes": 3028014,
      "sha256": "999217f6893b10fa663d6bbd30e762d7fb1be10efa67170c5ac87ca387c7005d"
    },
    "demos/google-material/assets/hero.mp4": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/google-material/assets/hero.mp4",
      "bytes": 16707976,
      "sha256": "27eb52ee151a6e996ee5befc1b84903a3e38e883e57667aa97ce71b457353d46"
    },
    "demos/google-material/assets/mncu38ac-home1.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/google-material/assets/mncu38ac-home1.png",
      "bytes": 150036,
      "sha256": "d4d41abf27d56b15104a8e8184816246cedbb750c2ab192654b42390566df150"
    },
    "demos/google-material/assets/mncu6xu7-home2.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/google-material/assets/mncu6xu7-home2.png",
      "bytes": 197354,
      "sha256": "a51d0c0982a46d790e81fcb8c19671640ff3c06edeb7ec1902342c6ef85be651"
    },
    "demos/google-material/assets/mncup23w-home11.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/google-material/assets/mncup23w-home11.png",
      "bytes": 179174,
      "sha256": "f4366d4e18db176fa75f2433cf7afca5404b157578cb2f7e9716426aad71cb97"
    },
    "demos/google-material/assets/mpmb3q7e-homepage1.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/google-material/assets/mpmb3q7e-homepage1.png",
      "bytes": 213072,
      "sha256": "837d8ee772639a4aa5bd0d213d9f5f56335b86a3fa20163728d9c993064668bf"
    },
    "demos/google-material/assets/mpme6ojb-homepage5.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/google-material/assets/mpme6ojb-homepage5.png",
      "bytes": 249201,
      "sha256": "2544efcfd5452fbeb8389988a517161e3180b7d1973c7a0505473f6cebb89520"
    },
    "demos/google-material/assets/mpmebssm-homepage6.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/google-material/assets/mpmebssm-homepage6.png",
      "bytes": 320708,
      "sha256": "e19a775101e20087d0cb6fd277f5d25b97b057de090092f16378c4d5263668f1"
    },
    "demos/google-material/assets/mpmewref-m3-social.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/google-material/assets/mpmewref-m3-social.jpg",
      "bytes": 553174,
      "sha256": "a493f79710190496bf61a93fd8c3044062e77eb82543e8eac2644699f482462a"
    },
    "demos/google-material/assets/mpmf99wi-m3-social.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/google-material/assets/mpmf99wi-m3-social.jpg",
      "bytes": 553174,
      "sha256": "a493f79710190496bf61a93fd8c3044062e77eb82543e8eac2644699f482462a"
    },
    "demos/google-material/assets/mpmfahpc-m3-social.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/google-material/assets/mpmfahpc-m3-social.jpg",
      "bytes": 553174,
      "sha256": "a493f79710190496bf61a93fd8c3044062e77eb82543e8eac2644699f482462a"
    },
    "demos/linear-workflow/assets/inter.woff2": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/linear-workflow/assets/inter.woff2",
      "bytes": 352240,
      "sha256": "693b77d4f32ee9b8bfc995589b5fad5e99adf2832738661f5402f9978429a8e3"
    },
    "demos/linear-workflow/assets/product-depth.webp": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/linear-workflow/assets/product-depth.webp",
      "bytes": 162273,
      "sha256": "6553308a3ae76d09f080a96ba62a19cffd28fb6e444b37bf87f4bce466d4be26"
    },
    "demos/met-museum/assets/dendur.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/met-museum/assets/dendur.jpg",
      "bytes": 202579,
      "sha256": "2c89d7d21ff3cfba8c932fa710c51fa0fc2a3e439704b383885c5cdcd6644481"
    },
    "demos/met-museum/assets/facade.webp": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/met-museum/assets/facade.webp",
      "bytes": 4332852,
      "sha256": "484cc95125260e8da1e9828b4757b7812b6cb7f94cd1b8d9167a899ebc528951"
    },
    "demos/met-museum/assets/vangogh.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/met-museum/assets/vangogh.jpg",
      "bytes": 588545,
      "sha256": "fc3764e14b0e84b0045f1a5b81f1a012a405a976ecb6f8746c79dcaf50b576ac"
    },
    "demos/monument-valley-game/assets/4-8f27e7fa.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/monument-valley-game/assets/4-8f27e7fa.jpg",
      "bytes": 185406,
      "sha256": "091e55a3abafcd6b8719111222e51428cd0b8ef42521d1dfad6b7b1caa30f6b1"
    },
    "demos/monument-valley-game/assets/mv-trailer-a0b9cbc1.mp4": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/monument-valley-game/assets/mv-trailer-a0b9cbc1.mp4",
      "bytes": 6694081,
      "sha256": "8717d5e90beb2bd066ac50942c698ae2832bfeaee68720b20873f731fc9771f5"
    },
    "demos/monument-valley-game/assets/trailer-landscape-poster-e2193d06.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/monument-valley-game/assets/trailer-landscape-poster-e2193d06.jpg",
      "bytes": 532455,
      "sha256": "21de0d6d56b0f81f292cc8cdc557f7343cbbce249a953bdd754af50cf39c9d49"
    },
    "demos/notion-editorial/assets/automate.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/notion-editorial/assets/automate.jpg",
      "bytes": 466452,
      "sha256": "11265cf6be1a4f9fe7e99d09cf34485f2d2107ddf59353e735ae9ce6a582bc4d"
    },
    "demos/notion-editorial/assets/capture.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/notion-editorial/assets/capture.jpg",
      "bytes": 694622,
      "sha256": "400eeb74f056f21433745fe13a1aa0f6e68c92371fab7b165db3639b86ccdb81"
    },
    "demos/notion-editorial/assets/hero.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/notion-editorial/assets/hero.jpg",
      "bytes": 348890,
      "sha256": "6aaa810ac0013d8c0980b3519d5bb83c8157346895b8cf7fe2f77244742184b4"
    },
    "demos/notion-editorial/assets/hero.mp4": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/notion-editorial/assets/hero.mp4",
      "bytes": 2185016,
      "sha256": "d9155355559e12340aace8fcd0f2307eea37f885c39c88b6db814a5339d60ab6"
    },
    "demos/notion-editorial/assets/mobile.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/notion-editorial/assets/mobile.jpg",
      "bytes": 255577,
      "sha256": "8da05074817fd61adf8230357507152090d0b6ad91c62eaf451ead8de1c85e7d"
    },
    "demos/palace-museum/assets/roof-detail.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/palace-museum/assets/roof-detail.png",
      "bytes": 517848,
      "sha256": "f3b8944e97b0b252eb41fdc53e90ff2318f894e5101697fe33a8cf875a9d1816"
    },
    "demos/palace-museum/assets/topic-vessel.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/palace-museum/assets/topic-vessel.png",
      "bytes": 145895,
      "sha256": "fd0c62870839305bca58bc72620b12cc5c147853981463a7d56113c6eefe92d6"
    },
    "demos/persona-kinetic/assets/ann-school.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/persona-kinetic/assets/ann-school.png",
      "bytes": 131781,
      "sha256": "0e01b65dfdf4e626715c662546a3398581ad6d14ca4348d548b7bbf7e383451e"
    },
    "demos/persona-kinetic/assets/ann-thief.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/persona-kinetic/assets/ann-thief.png",
      "bytes": 273001,
      "sha256": "7b5541a528a2f6139be6753772f9cce356319a79bbd348b7a90a1acba2dd4df0"
    },
    "demos/persona-kinetic/assets/arsene.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/persona-kinetic/assets/arsene.png",
      "bytes": 338362,
      "sha256": "f49f66520d1ad54767d6c4d41e6865049fa42582b831ba846e8a30e2c690ed55"
    },
    "demos/persona-kinetic/assets/captain-kidd.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/persona-kinetic/assets/captain-kidd.png",
      "bytes": 399261,
      "sha256": "981ca214f24effb840befc8f480f2e179e8b4ad77bbb8d0102085d108530c550"
    },
    "demos/persona-kinetic/assets/carmen.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/persona-kinetic/assets/carmen.png",
      "bytes": 400500,
      "sha256": "a4412eae1b5455f3aa88d505d3477b76f820970ea938c3c6461ac3e444fa239d"
    },
    "demos/persona-kinetic/assets/dot.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/persona-kinetic/assets/dot.png",
      "bytes": 9890450,
      "sha256": "67451ae237fe0fe09c4bc467c19105baa061a60118b67bfb5b1f0b8f6462e449"
    },
    "demos/persona-kinetic/assets/hero.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/persona-kinetic/assets/hero.png",
      "bytes": 1024306,
      "sha256": "f0f088ce61ee16ead49520dc5f60fff756f12724921f2bf721cc6a632de2c242"
    },
    "demos/persona-kinetic/assets/joker-school.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/persona-kinetic/assets/joker-school.png",
      "bytes": 146592,
      "sha256": "243d6383fe3d5f2fffcc3a15a8f90d8d16cef79e8c6be095efd58e28d59f0ac1"
    },
    "demos/persona-kinetic/assets/joker-thief.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/persona-kinetic/assets/joker-thief.png",
      "bytes": 230126,
      "sha256": "f01124b844274ea0995969d2cd43da4bda3d5bd3661582d5bb58997faf6643e7"
    },
    "demos/persona-kinetic/assets/ryuji-school.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/persona-kinetic/assets/ryuji-school.png",
      "bytes": 204388,
      "sha256": "23465d441fda6be1ee9513b56581a0ff1be4fc2feae86dbf86849c994c8fdd40"
    },
    "demos/persona-kinetic/assets/ryuji-thief.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/persona-kinetic/assets/ryuji-thief.png",
      "bytes": 211956,
      "sha256": "c12f9368371a40bce93641be5c6b94a5dc767d25f4d4db2113f24f7d4ca3cb84"
    },
    "demos/persona-kinetic/assets/school_life_ss1.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/persona-kinetic/assets/school_life_ss1.png",
      "bytes": 133749,
      "sha256": "c426c91cb8dde1ccf3fb7c7200e59e0a2c5ca1ddc9137f9269c417f72f9a87e3"
    },
    "demos/persona-kinetic/assets/school_life_ss3.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/persona-kinetic/assets/school_life_ss3.png",
      "bytes": 154219,
      "sha256": "7686368984069acb5798dd21b7cb840b9bda1e27fcb8dbb293db9db20c254b17"
    },
    "demos/persona-kinetic/assets/school.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/persona-kinetic/assets/school.png",
      "bytes": 133749,
      "sha256": "c426c91cb8dde1ccf3fb7c7200e59e0a2c5ca1ddc9137f9269c417f72f9a87e3"
    },
    "demos/persona-kinetic/assets/star.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/persona-kinetic/assets/star.png",
      "bytes": 134072,
      "sha256": "b0c0e67c5aee966fd9b050f054201cce4c9d815796dce06384c6dbc03de5bd11"
    },
    "demos/persona-kinetic/assets/star1.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/persona-kinetic/assets/star1.png",
      "bytes": 188148,
      "sha256": "7d01da542985e505c51fbf703c0882c437e8a98c1a4515f562e274499b450254"
    },
    "demos/philharmonie-music/assets/benjamin.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/philharmonie-music/assets/benjamin.jpg",
      "bytes": 197241,
      "sha256": "c2dc63961e6efee6650c298fc5e8de3f3280e7d86b6ade74deec5e411290bb19"
    },
    "demos/philharmonie-music/assets/installation-1.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/philharmonie-music/assets/installation-1.jpg",
      "bytes": 670143,
      "sha256": "266f3809b8be589777918e8a698f94ff0fcd91ce000b0ab6d330a8ca34124695"
    },
    "demos/philharmonie-music/assets/installation-2.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/philharmonie-music/assets/installation-2.jpg",
      "bytes": 636095,
      "sha256": "0507010bbfc6191484c708efebe1718ae790fe53bf173762e1b69dc8887e9621"
    },
    "demos/philharmonie-music/assets/sprite.svg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/philharmonie-music/assets/sprite.svg",
      "bytes": 188042,
      "sha256": "3e7a154ae39aafabcc8f5e5557e72b4bbd6078cec70a694b40eefef0be162b05"
    },
    "demos/qoder-platform/assets/mobile.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/qoder-platform/assets/mobile.png",
      "bytes": 1299018,
      "sha256": "bb7a577f0a41c79c46f64779935e5d9cb762a01ceeb7eb8ee173ebcf69854627"
    },
    "demos/rhine-lab/assets/lone-trail.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/rhine-lab/assets/lone-trail.jpg",
      "bytes": 553285,
      "sha256": "f53ee12bc12cb278ee75ca0c19f4731440a9dda66c101be454457ea2c370f3c0"
    },
    "demos/rijksmuseum-art/assets/chintz.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/rijksmuseum-art/assets/chintz.jpg",
      "bytes": 322630,
      "sha256": "b6108728c8d43ac3267c25fa70d2714167e84c411b4d78489ea6d7bb4972d63d"
    },
    "demos/rijksmuseum-art/assets/de-kooning.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/rijksmuseum-art/assets/de-kooning.jpg",
      "bytes": 2324847,
      "sha256": "2c3d236015509e7a42304cc091aee9d4b6552fc06cf14615814be417901ce0a4"
    },
    "demos/rijksmuseum-art/assets/family.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/rijksmuseum-art/assets/family.jpg",
      "bytes": 439288,
      "sha256": "cb671b1e8950b4da8947370298c11dcf5c168daa5b496d1e72749b96ba460dcf"
    },
    "demos/rijksmuseum-art/assets/hero-desktop.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/rijksmuseum-art/assets/hero-desktop.jpg",
      "bytes": 283237,
      "sha256": "3262fc63e16d76935f51942db7ae7614c059b88d2ed02ef386fa1881c8d51b0d"
    },
    "demos/rijksmuseum-art/assets/hero-mobile.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/rijksmuseum-art/assets/hero-mobile.jpg",
      "bytes": 175584,
      "sha256": "5eb873c38463d2ebdcc9f7436090800682b9ad876a4fd17d7ad345afe124c01c"
    },
    "demos/rijksmuseum-art/assets/hero.webp": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/rijksmuseum-art/assets/hero.webp",
      "bytes": 203870,
      "sha256": "fc51390d78be279e10d9e51e17eef7c5eb2f57f871750e2a346a003302757c52"
    },
    "demos/stripe-platform/assets/enterprise-hertz.webp": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/stripe-platform/assets/enterprise-hertz.webp",
      "bytes": 205658,
      "sha256": "d478ae6ee3bd578ba17c178426b28262ff27319c398b691eb601429190d36819"
    },
    "demos/stripe-platform/assets/enterprise-instacart.webp": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/stripe-platform/assets/enterprise-instacart.webp",
      "bytes": 187628,
      "sha256": "e9e350bac6128d46a58bfb6bf48c32848b8309cac5825fb3efe7ab14ee0f936f"
    },
    "demos/stripe-platform/assets/enterprise-lemonde.webp": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/stripe-platform/assets/enterprise-lemonde.webp",
      "bytes": 148666,
      "sha256": "b17cddb82e511ddc8b33e98159bfe30312acfd2aa9691b64972701a3e7891f62"
    },
    "demos/stripe-platform/assets/enterprise-urbn.webp": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/stripe-platform/assets/enterprise-urbn.webp",
      "bytes": 219658,
      "sha256": "b391a0713efeab1ebd9922f3d9139c8d73cea0a92dbdd7057b3e0de6d540a237"
    },
    "demos/uma-musume/assets/about_bg.BBeJqHpY.avif": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/uma-musume/assets/about_bg.BBeJqHpY.avif",
      "bytes": 133545,
      "sha256": "f5342a90b79a78266525d405cbe0839c5fc482abbab8814963715dc0db314e43"
    },
    "demos/uma-musume/assets/app-icon.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/uma-musume/assets/app-icon.png",
      "bytes": 513750,
      "sha256": "422f52106a9af0e67cb1b2728d084f80389c568b58ef36c6451ea90ce448eb53"
    },
    "demos/uma-musume/assets/kv.C6tHq3MX.avif": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/uma-musume/assets/kv.C6tHq3MX.avif",
      "bytes": 415417,
      "sha256": "c24dc850168634d1f5332b5c73dfd4a216a88acebc725d216bfb0ab78bf5f33a"
    },
    "demos/uma-musume/assets/logo-umamusume.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/uma-musume/assets/logo-umamusume.png",
      "bytes": 132471,
      "sha256": "3a11b259f3c215c9a03a16a5ab40bb81db41a1de99d9cb81dc672adca7fa498f"
    },
    "demos/uma-musume/assets/top_about.mp4": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/uma-musume/assets/top_about.mp4",
      "bytes": 25860812,
      "sha256": "c893f883aa5652e11dd5da5de8ebc3ac0aacaaa7a23d53a11b262243d3a8155c"
    },
    "demos/zelda-world/assets/bgm.mp3": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/zelda-world/assets/bgm.mp3",
      "bytes": 3182185,
      "sha256": "b75d4ee9a456439feaed07ba36b42cf62b7009a5aa469b2be6323e084113ac34"
    },
    "demos/zelda-world/assets/kakeru-poster.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/zelda-world/assets/kakeru-poster.jpg",
      "bytes": 206000,
      "sha256": "768bbedba0f6de353d5180b97dc335f00cc9e99e5a141e90be0cd4d035f5ccaa"
    },
    "demos/zelda-world/assets/kakeru.mp4": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/zelda-world/assets/kakeru.mp4",
      "bytes": 3423246,
      "sha256": "392c355b0b83c7a0c0f3444c43a412416220d6c8fa11f7341289019d45f8df42"
    },
    "demos/zelda-world/assets/logo.webp": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/zelda-world/assets/logo.webp",
      "bytes": 165894,
      "sha256": "464d2126eecc13a69c9c38d4c0f56b8f7dfb0dde505aef74e76936f2a955e8ab"
    },
    "demos/zelda-world/assets/obj_loading_2.webp": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/zelda-world/assets/obj_loading_2.webp",
      "bytes": 136048,
      "sha256": "81906246afb8a10f5620ca41ebf9d7c64d1609febd29a54aff58a5e06d4b2017"
    },
    "demos/zelda-world/assets/se.mp3": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/zelda-world/assets/se.mp3",
      "bytes": 156980,
      "sha256": "3983686ce1e1ce4f7939ec4641b0b205399afb61699093afe577b393d4fc7149"
    },
    "demos/zelda-world/assets/tsukuru-poster.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/zelda-world/assets/tsukuru-poster.jpg",
      "bytes": 289879,
      "sha256": "28f74c13b70728adc00eddfab54e1ff1ec4d72d443f59bd28a4ec8040b2da6ac"
    },
    "demos/zelda-world/assets/tsukuru.mp4": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/zelda-world/assets/tsukuru.mp4",
      "bytes": 3878328,
      "sha256": "581bd2a6f584b51d92c270492484c87a96ced3f38a2978d383cdeb0159aab2c9"
    },
    "demos/zelda-world/assets/tsumugu.mp4": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/demos/zelda-world/assets/tsumugu.mp4",
      "bytes": 3557818,
      "sha256": "11142d11c48dc8ca4de587e78ca7c802fa1d0b6ef4f79d2562c01b45b172878e"
    },
    "previews/blue-archive.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/previews/blue-archive.jpg",
      "bytes": 241005,
      "sha256": "eb65a5396d590d7acf93621f7be0273219383797788e62f719c1174295058e03"
    },
    "previews/design-sight.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/previews/design-sight.jpg",
      "bytes": 287757,
      "sha256": "be82da102e18fe4eae60448246f17af20df22b9c0c20d0384ac2e4cbf203b195"
    },
    "previews/endfield-industrial.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/previews/endfield-industrial.jpg",
      "bytes": 199719,
      "sha256": "41b1938633c8cb9218beb8ca7e025287f3c699fd4d739a67392bef70722abde2"
    },
    "previews/fuji-rock.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/previews/fuji-rock.jpg",
      "bytes": 254999,
      "sha256": "e3cbed6a69417faeee96f804a8ce43d77d00f8718d5747788c009bcb2d26c7a4"
    },
    "previews/genshin-world.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/previews/genshin-world.jpg",
      "bytes": 285335,
      "sha256": "7fbc430fdda649af1b97743d885a80a9ff9e48fd2b0e86d667dfdffa1a1c9964"
    },
    "previews/google-material.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/previews/google-material.jpg",
      "bytes": 164835,
      "sha256": "676300f36bea87a6c81935b9e066823e8789b77885ac0a704fef405f8e3a8304"
    },
    "previews/met-museum.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/previews/met-museum.jpg",
      "bytes": 243835,
      "sha256": "7bcf4df876a5a2dd76735871304b0b07b4ff86b5f3446e41dcc599aab045b265"
    },
    "previews/mori-art-museum.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/previews/mori-art-museum.jpg",
      "bytes": 149652,
      "sha256": "d6741f1f04dc10f13959e4b81a865708e5192ad1b9b76957f7b456913947923c"
    },
    "previews/persona-kinetic.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/previews/persona-kinetic.jpg",
      "bytes": 258032,
      "sha256": "7fe61d6caf9175e29a12a7b842e4f3ca2a7b32b421775618f040158b4c9d5e54"
    },
    "previews/rijksmuseum-art.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/previews/rijksmuseum-art.jpg",
      "bytes": 182846,
      "sha256": "76c14c7408315f82779eb7ac3e0827474ee8060499b98e2be792054aac6edda5"
    },
    "previews/suzhou-museum.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/previews/suzhou-museum.jpg",
      "bytes": 151472,
      "sha256": "a6790706650a16a9af0f587ac9f63ffefdc2cf46efed3c3baa313a83a7d22349"
    },
    "previews/uma-musume.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/previews/uma-musume.jpg",
      "bytes": 430946,
      "sha256": "e5ecbb32231038405242116312445fdce6aa525a5a813f61c3a7f79ecf0aa734"
    },
    "research/screenshots/blue-archive-source.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/research/screenshots/blue-archive-source.jpg",
      "bytes": 168907,
      "sha256": "48d9f31299c2cb273d2a0a1bcd21d6ec75d442bc7dbe880df23e9c57e4f56dbe"
    },
    "research/screenshots/fuji-rock-source.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/research/screenshots/fuji-rock-source.jpg",
      "bytes": 191109,
      "sha256": "60e5488badeb4da684658aa43a470d07c18406281763f8730502bc2b68d4977d"
    },
    "research/screenshots/genshin-world-source.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/research/screenshots/genshin-world-source.jpg",
      "bytes": 277034,
      "sha256": "d967b90341613e2bf9d3c5612423b73496c29c2986ce4c7f75ea3279d029fe83"
    },
    "research/screenshots/linear-workflow-source.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/research/screenshots/linear-workflow-source.png",
      "bytes": 285471,
      "sha256": "218eb677d0a6004dcd0227b4e4bbf1657982ff26b32df12643f7d13cf2bde951"
    },
    "research/screenshots/met-museum-source.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/research/screenshots/met-museum-source.jpg",
      "bytes": 160684,
      "sha256": "6b4fe39c32e3cc11c253178ad43a0a56528122358d1fa88f05477655b36f1b42"
    },
    "research/screenshots/notion-editorial-source.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/research/screenshots/notion-editorial-source.png",
      "bytes": 202533,
      "sha256": "d315a17ae32909b7e9ea55242ac139561ed5aa26c92b325d40b2df4fb1856485"
    },
    "research/screenshots/persona-character-source.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/research/screenshots/persona-character-source.jpg",
      "bytes": 165390,
      "sha256": "44afffe30b74228c699e4ae5e8a85b9b6a6990bbbf4924274aae678533f4732f"
    },
    "research/screenshots/persona-kinetic-source.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/research/screenshots/persona-kinetic-source.jpg",
      "bytes": 176860,
      "sha256": "d313880e6cfa41cdf3cdccd9013a5aff00a3167ba1a52fe324d8b5c9e5f9dfe4"
    },
    "research/screenshots/rijksmuseum-art-source.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/research/screenshots/rijksmuseum-art-source.jpg",
      "bytes": 135512,
      "sha256": "e1f9db97968f22ffb135f8e3af64cafb060e8d1aa37eb545df210b5fe20aaed3"
    },
    "research/screenshots/stripe-platform-source.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/research/screenshots/stripe-platform-source.png",
      "bytes": 676090,
      "sha256": "2760148e906513f767291374d7f8313a5e153fedcc17120caa7e0acd10121074"
    },
    "research/screenshots/uma-musume-source.jpg": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/research/screenshots/uma-musume-source.jpg",
      "bytes": 216259,
      "sha256": "e358f4e70bb7e2b76ed2e73a2c078e9e5f13fa12247003d99e60467af489466d"
    },
    "docs/readme/cover.webp": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/docs/readme/cover.webp",
      "bytes": 363354,
      "sha256": "ae5261935ab2a69ca2e7ef19cbf3b9fcc3122f50875b7afd74f18045bb325b4c"
    },
    "docs/site/cases.png": {
      "url": "https://raw.githubusercontent.com/MIBXR/design-atlas/a31ca4e9761d553b31459f013f5dec1ec778a9f8/docs/site/cases.png",
      "bytes": 298322,
      "sha256": "a9d9c04d69576823a67c176522153dddd5165ac0e1d647a7ee845441fe03a245"
    }
  }
};
