/* The same readiness gate is used by an embedded case and its standalone URL. */
(()=>{
 'use strict';
 const id=location.pathname.match(/\/demos\/([^/]+)/)?.[1];
 const cases={
  'apple-product':{roots:'header,#hero',videos:'#hero-video'},
  'arknights-world':{roots:'header,#entry-loader,#index',native:'#entry-loader',videos:'#home-video',images:['assets/background.jpg','assets/bg2.png','assets/common_mask.png'],sections:{'#operator':['assets/kaltsit.png','assets/kaltsit-e2.png','assets/amiya.png','assets/amiya-e2.png','assets/chen.png','assets/chen-e2.png'],'#world':['assets/particle.png','assets/originiums.png','assets/originium_arts.png','assets/reunion.png','assets/infected.png','assets/nomadic_city.png','assets/rhodes_island.png']},files:{'#world':['assets/world-models.json']}},
  'blue-archive':{roots:'header,#home',videos:'#background-video',images:['assets/bg_cover.9bd1cfea.png']},
  'chatgpt-platform':{roots:'header,.hero,#showcase',images:['assets/chat.webp','assets/overview-chat-scribble.webp','assets/overview-chat-flower.webp','assets/overview-chat-tomato.webp','assets/merge-chat-shape.svg','assets/star-large-light.svg','assets/star-small-light.svg','assets/star-large-dark.svg','assets/star-small-dark.svg'],sections:{'#showcase':['assets/work.webp','assets/code.webp','assets/merge-work-deck.webp','assets/merge-work-preso.webp','assets/merge-work-shape-transparent.svg','assets/merge-code-ascii.webp','assets/merge-code-picker-light-1.webp','assets/code-light.svg','assets/globe-light.svg']}},
  'claude-platform':{roots:'header,.hero',videos:'.hero video'},
  'design-sight':{roots:'header,.poster',native:'#entry-loader'},
  'fuji-rock':{roots:'header,.photo-hero',native:'#loader'},
  'genshin-world':{roots:'header,#home',videos:'#keyart-video',images:['assets/page-background.webp']},
  'google-material':{roots:'header,.site-header,.hero,.rail,nav',videos:'#hero-video'},
  'linear-workflow':{roots:'header,.hero'},
  'met-museum':{roots:'header,#visit'},
  'monument-valley-game':{roots:'header,#home',native:'#loading-screen',videos:'#hero-video'},
  'mori-art-museum':{roots:'header,.exhibition-hero'},
  'notion-editorial':{roots:'header,.hero',videos:'#hero-video'},
  'persona-kinetic':{roots:'header,.hero',images:['assets/dot.png','assets/star1.png','assets/star2.png','assets/star3.png','assets/star4.png','assets/star5.png','assets/star6.png']},
  'philharmonie-music':{roots:'header,.hero'},
  'qoder-platform':{roots:'header,.hero',sections:{'.platforms':['assets/desktop.svg','assets/mobile.png','assets/ide.svg','assets/jetbrains.svg','assets/cli.svg']}},
  'rijksmuseum-art':{roots:'header,.hero'},
  'stripe-platform':{roots:'header,.hero,.single-wave',images:['assets/wave.webp'],sections:{'.enterprise':['assets/enterprise-hertz.webp','assets/enterprise-urbn.webp','assets/enterprise-instacart.webp','assets/enterprise-lemonde.webp']}},
  'uma-musume':{roots:'header,#home',images:['assets/header-blue.jpg']},
  'zelda-world':{roots:'header,#entry-gate,#world-1,.chapters',native:'#entry-gate',videos:'#world-1 video',images:['assets/bg_loading.webp','assets/mask_loading.webp','assets/frame_thumbnail.webp','assets/logo.webp']}
 };
 let config=cases[id];if(!config)return;if(id==='chatgpt-platform'&&innerWidth>=768&&matchMedia('(prefers-color-scheme: dark)').matches){config.images.push('assets/chat-dark.webp');config.sections['#showcase'].push('assets/work-dark.webp','assets/code-dark.webp');}
 // A first hover can immediately enter Work or Codex; decode every mode before that opening.
 if(id==='chatgpt-platform')config.images=[...new Set([...config.images,...config.sections['#showcase']])];
 if(id==='blue-archive'&&location.pathname.endsWith('/character.html'))config={roots:'header,#characters',images:['assets/shiroko.png','assets/school-abydos-card.png','assets/character-background.png','assets/character-background-mobile.png','assets/student-card.png'],sections:{'#characters':['assets/hoshino.png','assets/serika.png','assets/nonomi.png']}};
 const startedAt=performance.now(),html=document.documentElement,cache=new Map(),scriptBodies=new Map();
 html.dataset.caseLoading='pending';html.dataset.caseId=id;
 let resolveReady;const ready=new Promise(resolve=>resolveReady=resolve);
 const api=window.CaseLoading={id,startedAt,ready,prepare,config,state:'pending',completed:0,total:0,failures:[]};
 const assetRuntime=()=>window.AtlasAssets||window.AssetRuntime||window.CaseAssets;
 const resolve=url=>assetRuntime()?.resolve?.(url)||url;
 const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches||new URLSearchParams(location.search).get('motion')==='reduce';
 let panel,label,count,bar,retry,proceed,native,activeAttempt=0,started=false,hint,hintTimer,panelTimer,waitingToStart=false,scriptFailed=false;
 const deferred=()=>{let complete;return {promise:new Promise(resolve=>complete=resolve),complete:value=>complete(value)};};let scriptWait=deferred();
 const autoplay=[];
 function timeout(promise,ms=20000){return new Promise((yes,no)=>{const timer=setTimeout(()=>no(new Error('资源等待超时')),ms);Promise.resolve(promise).then(value=>{clearTimeout(timer);yes(value);},error=>{clearTimeout(timer);no(error);});});}
 function fetchAsset(url){return assetRuntime()?.fetch?.(url)||fetch(resolve(url));}
 function image(url){const load=actual=>new Promise((yes,no)=>{const img=new Image;img.onload=()=>img.decode?img.decode().then(yes,no):yes();img.onerror=()=>no(new Error('图片未能载入'));img.src=actual;if(img.complete&&img.naturalWidth)img.onload();});return assetRuntime()?.load?assetRuntime().load(url,load):load(resolve(url));}
 function firstFrame(video){if(video.error||video.networkState===3)video.load();if(video.readyState>=2&&!video.seeking)return Promise.resolve();return new Promise((yes,no)=>{const done=()=>{if(video.readyState<2||video.seeking)return;clean();yes();},fail=()=>{clean();no(new Error('视频首帧未能载入'));},clean=()=>{clearTimeout(timer);video.removeEventListener('loadeddata',done);video.removeEventListener('seeked',done);video.removeEventListener('error',fail);},timer=setTimeout(fail,19000);video.addEventListener('loadeddata',done);video.addEventListener('seeked',done);video.addEventListener('error',fail,{once:true});video.preload='auto';if(video.networkState===0)video.load();done();});}
 function visible(el){const style=getComputedStyle(el);return style.display!=='none'&&el.getClientRects().length>0;}
 function urls(value){return [...String(value).matchAll(/url\(\s*["']?([^"')]+)["']?\s*\)/g)].map(m=>m[1]);}
 function collect(scope,{fonts=false,video=true,includeHidden=false}={}){
  const jobs=[];const add=(key,run)=>{if(!jobs.some(x=>x.key===key))jobs.push({key,run});};
  const nodes=[scope,...scope.querySelectorAll('*')];
  for(const node of nodes){
   if(node instanceof HTMLImageElement){if(!includeHidden&&!visible(node))continue;node.loading='eager';node.fetchPriority=fonts?'high':'low';const src=node.currentSrc||node.src;if(src)add('image:'+src,()=>image(src));}
   if(node instanceof HTMLVideoElement){if((includeHidden||visible(node))&&node.poster)add('image:'+node.poster,()=>image(node.poster));if(video&&(includeHidden||visible(node))&&(node.currentSrc||node.src||node.querySelector('source[src]')))add('video:'+(node.id||node.currentSrc||node.src),()=>firstFrame(node));}
   if(!includeHidden&&!visible(node))continue;
   for(const pseudo of [null,'::before','::after']){const style=getComputedStyle(node,pseudo);for(const field of ['backgroundImage','maskImage','webkitMaskImage'])for(const src of urls(style[field]))if(!src.startsWith('data:'))add('image:'+src,()=>image(src));}
  }
  if(fonts&&document.fonts){const samples=[scope,...scope.querySelectorAll('h1,h2,button,nav,.verb,.section-indicator,.icon,[class*="logo"]')].filter(el=>includeHidden||visible(el)).slice(0,64);for(const el of samples){const s=getComputedStyle(el),font=s.fontStyle+' '+s.fontWeight+' '+s.fontSize+' '+s.fontFamily;add('font:'+font,()=>document.fonts.load(font,el.textContent?.trim().slice(0,64)||'Aa一'));}}
  return jobs;
 }
 function extraJobs(scope){const jobs=[];for(const [selector,assets] of Object.entries(config.sections||{}))if(scope.matches(selector)||scope.querySelector(selector))assets.forEach(url=>jobs.push({key:'image:'+url,run:()=>image(url)}));for(const [selector,assets] of Object.entries(config.files||{}))if(scope.matches(selector)||scope.querySelector(selector))assets.forEach(url=>jobs.push({key:'file:'+url,run:()=>fetchAsset(url).then(r=>{if(!r.ok)throw new Error('资源未能载入');return r.arrayBuffer();})}));return jobs;}
 async function runJobs(jobs,onProgress,refresh=false){let done=0;const total=jobs.length;onProgress?.(0,total);return Promise.all(jobs.map(async job=>{try{if(refresh)cache.delete(job.key);if(!cache.has(job.key))cache.set(job.key,timeout(job.run()));await cache.get(job.key);return {key:job.key,ok:true};}catch(error){cache.delete(job.key);return {key:job.key,ok:false,message:error.message};}finally{onProgress?.(++done,total);}}));}
 function rememberReady(results,scope=document){const urls=results.filter(item=>item.ok&&item.key.startsWith('image:')).map(item=>resolve(item.key.slice(6)));const videos=scope.matches?.('video')?[scope]:[...scope.querySelectorAll('video')];videos.filter(video=>video.readyState>=2&&video.currentSrc).forEach(video=>urls.push(video.currentSrc));if(assetRuntime()?.mode==='github')for(const [path,entry] of Object.entries(window.DesignAtlasAssetSources?.assets||{}))if(path.startsWith('demos/'+id+'/')&&/\.(woff2?|ttf|otf)$/i.test(path))urls.push(resolve(typeof entry==='string'?entry:entry.url));try{window.DesignAtlasAssetCache?.remember?.([...new Set(urls)])?.catch(()=>{});}catch{}}
 function showHint(message,failed=false,again){if(!hint){hint=document.createElement('div');hint.className='case-load-hint';hint.setAttribute('role','status');document.body.append(hint);}clearTimeout(hintTimer);hint.hidden=false;hint.textContent=message;if(again){const b=document.createElement('button');b.textContent='重试';b.onclick=again;hint.append(b);}if(failed)hintTimer=setTimeout(()=>hint.hidden=true,8000);}
 async function prepare(scope,options={}){if(typeof scope==='string')scope=document.querySelector(scope);if(!scope)return [];try{if(options.retry)await assetRuntime()?.retry?.(scope);await assetRuntime()?.prepare?.(scope);}catch{}const jobs=[...collect(scope,{video:options.video!==false,includeHidden:true}),...extraJobs(scope)];const loading=setTimeout(()=>{if(options.hint)showHint('下一章节素材正在载入…');},250);const result=await runJobs(jobs,null,options.retry);rememberReady(result,scope);clearTimeout(loading);const failures=result.filter(r=>!r.ok);if(options.hint){if(failures.length)showHint('部分素材未载入，可继续浏览或重试。',true,()=>prepare(scope,{...options,retry:true}));else if(hint)hint.hidden=true;}scope.dataset.assetsReady=failures.length?'partial':'ready';return result;}
 function makePanel(){native=config.native&&document.querySelector(config.native);if(native)native.hidden=false;panel=document.createElement('div');panel.id='case-resource-loader';if(native)panel.className='case-load-native';panel.setAttribute('role','status');panel.setAttribute('aria-live','polite');panel.innerHTML='<div class="case-load-panel"><p class="case-load-label">正在准备页面</p><div class="case-load-track" aria-hidden="true"><i></i></div><p class="case-load-count">关键素材载入中</p><div class="case-load-actions"><button class="case-load-retry" hidden>重试</button><button class="case-load-continue">继续浏览</button></div></div>';document.body.append(panel);label=panel.querySelector('.case-load-label');count=panel.querySelector('.case-load-count');bar=panel.querySelector('i');retry=panel.querySelector('.case-load-retry');proceed=panel.querySelector('.case-load-continue');retry.onclick=()=>attempt(true);proceed.onclick=()=>scriptFailed?location.reload():start(true);if(native?.id==='entry-gate')native.inert=true;
  const bodyStyle=getComputedStyle(document.body),rootStyle=getComputedStyle(html),solid=color=>color&&color!=='transparent'&&color!=='rgba(0, 0, 0, 0)';const palette={'persona-kinetic':['#d40012','#fff'],'genshin-world':['#142e45','#fff'],'blue-archive':['#e4f5ff','#17324f']};const colors=palette[id]||[solid(bodyStyle.backgroundColor)?bodyStyle.backgroundColor:solid(rootStyle.backgroundColor)?rootStyle.backgroundColor:'#f6f6f5',bodyStyle.color||'#242424'];html.style.setProperty('--case-loading-background',colors[0]);html.style.setProperty('--case-loading-color',colors[1]);if(!native){panel.hidden=true;panelTimer=setTimeout(()=>{if(!started)panel.hidden=false;},180);}
 }
 function progress(done,total){api.completed=done;api.total=total;count.textContent=done+' / '+total+' 项关键素材';bar.style.width=(total?done/total*100:100)+'%';panel.dataset.completed=done;panel.dataset.total=total;if(id==='arknights-world'){const percentage=Math.floor(total?done/total*100:100);document.querySelector('#loading-percent').textContent=percentage;document.querySelector('#loading-bar').style.width=percentage+'%';}}
 async function start(continued=false){if(started||waitingToStart)return;waitingToStart=true;if(continued){proceed.disabled=true;proceed.textContent='正在准备交互';}const scripts=await scriptWait.promise;waitingToStart=false;if(scripts.some(item=>!item.ok)){scriptFailed=true;api.state='failed';label.textContent='交互脚本尚未就绪';count.textContent='请重试或刷新页面';retry.hidden=false;proceed.disabled=false;proceed.textContent='刷新页面';return;}started=true;activeAttempt++;clearTimeout(panelTimer);api.state=continued?'continued':'ready';api.readyAt=performance.now();api.failures=api.failures||[];html.dataset.caseLoading='ready';if(native?.id==='entry-gate')native.inert=false;panel.hidden=true;resolveReady({continued,failures:api.failures});
  // All script bytes are fetched before this point; execution remains in original order.
  const markers=[...document.querySelectorAll('script[type="application/x-case-script"]')];
  for(const marker of markers){const source=marker.dataset.src||marker.getAttribute('src');const script=document.createElement('script');if(marker.dataset.scriptType==='module')script.type='module';script.textContent=(source?scriptBodies.get(source):marker.textContent)+'\n//# sourceURL='+new URL(source||('case-inline-'+id),location.href).href;try{document.body.append(script);marker.dataset.executed='true';}catch(error){console.warn('Case startup unavailable',error.message);}}
  for(const video of autoplay)if(id!=='arknights-world'&&!reduced()&&!document.hidden&&visible(video)){video.setAttribute('autoplay','');video.play().catch(()=>{});}
  document.dispatchEvent(new CustomEvent('case:ready',{detail:{id,continued}}));observeSections();
 }
 async function attempt(refresh=false){if(refresh)scriptWait=deferred();scriptFailed=false;proceed.disabled=false;proceed.textContent='继续浏览';const attemptId=++activeAttempt;api.state='pending';retry.hidden=true;label.textContent='正在准备页面';try{await timeout(assetRuntime()?.ready||Promise.resolve());await timeout(window.DesignAtlasAssetCache?.ready||Promise.resolve(),8500);if(refresh)await assetRuntime()?.retry?.(document);await assetRuntime()?.prepare?.(document);}catch{}
  const roots=[...document.querySelectorAll(config.roots)],hash=document.querySelector(location.hash&&/^#[\w-]+$/.test(location.hash)?location.hash:'__no_target__');if(hash&&hash.matches('section,.world'))roots.push(hash);
  const jobs=roots.flatMap(root=>collect(root,{fonts:true,video:false,includeHidden:root===hash||id==='arknights-world'&&root.id==='index'||id==='zelda-world'&&root.matches('.world')}));if(hash)jobs.push(...extraJobs(hash));(config.images||[]).forEach(url=>jobs.push({key:'image:'+url,run:()=>image(url)}));
  let selectors=config.videos;if(id==='notion-editorial'&&innerWidth<=700)selectors=null;if(id==='arknights-world'&&hash&&hash.id!=='index')selectors='#'+hash.id+' video';if(id==='zelda-world'&&hash?.matches('.world'))selectors='#'+hash.id+' video';if(selectors)document.querySelectorAll(selectors).forEach(video=>{if(visible(video)||['arknights-world','zelda-world'].includes(id))jobs.push({key:'video:'+(video.id||video.currentSrc||video.src),run:()=>firstFrame(video)});});
  for(const marker of document.querySelectorAll('script[type="application/x-case-script"]')){const source=marker.dataset.src||marker.getAttribute('src');if(source)jobs.push({key:'script:'+source,run:async()=>{const response=await fetchAsset(source);if(!response.ok)throw new Error('交互脚本未能载入');scriptBodies.set(source,await response.text());}});}
  const unique=[...new Map(jobs.map(job=>[job.key,job])).values()],all=runJobs(unique,progress,refresh),slot=scriptWait;runJobs(unique.filter(job=>job.key.startsWith('script:'))).then(slot.complete);const result=await all;rememberReady(result);if(started||attemptId!==activeAttempt)return;api.failures=result.filter(item=>!item.ok);if(api.failures.length){api.state='failed';scriptFailed=api.failures.some(item=>item.key.startsWith('script:'));label.textContent=scriptFailed?'交互脚本尚未就绪':'部分素材未能载入';count.textContent=scriptFailed?'请重试或刷新页面':api.failures.length+' 项未就绪，可重试或继续浏览';retry.hidden=false;proceed.disabled=false;proceed.textContent=scriptFailed?'刷新页面':'继续浏览';panel.dataset.failed=String(api.failures.length);}else start();
 }
 function observeSections(){const sections=['arknights-world','zelda-world'].includes(id)?[]:[...document.querySelectorAll('main section')];if(sections.length){const observer=new IntersectionObserver(rows=>{for(const row of rows)if(row.isIntersecting){prepare(row.target);observer.unobserve(row.target);}},{rootMargin:'700px 0px'});sections.forEach(section=>observer.observe(section));}document.addEventListener('pointerover',event=>{const link=event.target.closest('a[href^="#"]');if(link&&/^#[\w-]+$/.test(link.hash))prepare(link.hash);},{passive:true});document.addEventListener('focusin',event=>{const link=event.target.closest('a[href^="#"]');if(link&&/^#[\w-]+$/.test(link.hash))prepare(link.hash);});}
 async function boot(){if(id==='google-material'){let theme;try{theme=localStorage.getItem('material-study-theme');}catch{}html.dataset.theme=theme==='dark'||theme!=='light'&&matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';}document.querySelectorAll('video').forEach(video=>{if(video.hasAttribute('autoplay'))autoplay.push(video);video.pause();video.removeAttribute('autoplay');if(video.readyState>=1&&video.currentTime>0)try{video.currentTime=0;}catch{}});makePanel();attempt();}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
