(()=>{
 const wall=document.querySelector('.logo-wall>div');[...wall.children].forEach(e=>{const copy=e.cloneNode(true);copy.setAttribute('aria-hidden','true');wall.append(copy);});
 const menu=document.querySelector('.menu'),header=document.querySelector('header'),buttons=[...document.querySelectorAll('[data-menu]')],desktop=matchMedia('(min-width:701px)'),reduce=matchMedia('(prefers-reduced-motion:reduce)');
 const menus={Product:['Capture','Find','Automate','See all features','See what’s new','Download Notion'],AI:['Notion AI','Enterprise search','AI meeting notes','Agents'],Resources:['Templates','Customer stories','Help center','Notion Academy']};
 let phase='closed',key='',token=0,leave,finishTimer,activeTrigger=null;menu.inert=true;menu.setAttribute('aria-hidden','true');menu.dataset.phase=phase;
 function settle(id,next){if(id!==token)return;phase=next;menu.dataset.phase=next;if(next==='closed')menu.hidden=true;}
 function hide(focus=false){clearTimeout(leave);clearTimeout(finishTimer);if(phase==='closed')return;const id=++token;phase='closing';menu.dataset.phase=phase;menu.inert=true;menu.setAttribute('aria-hidden','true');buttons.forEach(b=>b.setAttribute('aria-expanded','false'));const finish=()=>{settle(id,'closed');if(id===token&&focus)activeTrigger?.focus({preventScroll:true});};if(reduce.matches||!desktop.matches)finish();else finishTimer=setTimeout(finish,200);}
 function show(b){if(!desktop.matches)return;clearTimeout(leave);clearTimeout(finishTimer);const next=b.dataset.menu;if((phase==='open'||phase==='opening')&&key===next)return;const hidden=menu.hidden,switched=!hidden&&phase!=='closing'&&key!==next,id=++token;key=next;activeTrigger=b;menu.hidden=false;menu.inert=false;menu.setAttribute('aria-hidden','false');menu.dataset.key=next;menu.innerHTML=menus[next].map(t=>'<a href="#features">'+t+' →</a>').join('');buttons.forEach(x=>x.setAttribute('aria-expanded',String(x===b)));if(reduce.matches||switched){settle(id,'open');return;}if(hidden){menu.dataset.phase='closed';void menu.offsetWidth;}phase='opening';menu.dataset.phase=phase;finishTimer=setTimeout(()=>settle(id,'open'),250);}
 buttons.forEach(b=>{b.onclick=()=>show(b);b.addEventListener('mouseenter',()=>{if(matchMedia('(hover:hover)').matches)show(b);});b.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();show(b);menu.querySelector('a')?.focus();}});});
 header.addEventListener('mouseleave',()=>{if(desktop.matches)leave=setTimeout(()=>hide(),150);});header.addEventListener('mouseenter',()=>clearTimeout(leave));menu.addEventListener('mouseenter',()=>clearTimeout(leave));
 document.addEventListener('keydown',e=>{if(desktop.matches&&e.key==='Escape')hide(true);});document.addEventListener('click',e=>{if(desktop.matches&&!e.target.closest('header'))hide();});menu.addEventListener('click',e=>{if(e.target.closest('a'))hide();});desktop.addEventListener('change',()=>{if(!desktop.matches)hide();});reduce.addEventListener('change',()=>{if(!reduce.matches)return;clearTimeout(finishTimer);if(phase==='closing')settle(token,'closed');else if(phase!=='closed')settle(token,'open');});
})();

/* Captured mobile menu: one accordion group in place, with persistent bottom actions. */
(()=>{
 const trigger=document.querySelector('.hamburger'),header=document.querySelector('header'),desktopToggle=trigger.onclick,desktop=document.querySelector('.menu'),phone=matchMedia('(max-width:700px)'),reduce=matchMedia('(prefers-reduced-motion:reduce)');
 const products=[['Notion AI','/product/ai','AI tools for work','✦'],['Agents','/product/agents','Automate busywork','✧'],['AI Meeting Notes','/product/ai-meeting-notes','Perfectly written by AI','♩'],['Enterprise Search','/product/enterprise-search','Find answers instantly','⌕'],['Knowledge Base','/product/wikis','Centralize your knowledge','▤'],['Docs','/product/docs','Simple and powerful','▧'],['Projects','/product/projects','Manage any project','◎'],['Connections','/connections','Connect your apps','⋈'],['Security','/security','Safe and scalable','♙'],['Notion Calendar','/product/calendar',"It's time",'▦']];
 const groups={Product:[['',products]],AI:[['AI features',products.slice(0,4)],['Explore use cases',[['For work','/product/ai/use-cases?type=work'],['For life','/product/ai/use-cases?type=life']]]],Resources:[['Notion for',[['Enterprise','/enterprise'],['Small businesses','/teams'],['Startups','/startups'],['Developers','/product/dev']]],['Discover',[["What's New",'/releases'],['Customer stories','/customers'],['Webinars','/webinars'],['Templates','/templates'],['Consultants','/explore-consultants']]],['Learn',[['Academy','https://academy.notion.com'],['Product tours','/product/demos'],['Help Center','/help']]]]};
 const overlay=document.createElement('div');overlay.className='notion-phone';overlay.id='notion-phone-nav';overlay.hidden=true;overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-label','Mobile navigation');
 const links=(list)=>list.map(([label,path,caption,icon],i)=>'<a class="notion-phone-link '+(caption?'has-caption':'')+'" href="'+(path.startsWith('http')?path:'https://www.notion.com'+path)+'">'+(icon?'<span class="notion-phone-icon icon-'+i+'" aria-hidden="true">'+icon+'</span>':'')+'<span><strong>'+label+'</strong>'+(caption?'<small>'+caption+'</small>':'')+'</span></a>').join('');
 overlay.innerHTML='<div class="notion-phone-head"><a href="https://www.notion.com/" aria-label="Notion home"><img src="assets/logo.svg" alt="Notion"></a><a class="notion-phone-cta" href="https://www.notion.com/signup">Get Notion free</a><button class="notion-phone-close" aria-label="Close main menu">×</button></div><div class="notion-phone-scroll">'+Object.entries(groups).map(([key,sections])=>'<section class="notion-phone-group"><button data-phone-group="'+key+'" aria-expanded="false" aria-controls="notion-phone-'+key+'">'+key+'<span class="notion-phone-chevron" aria-hidden="true"></span></button><div class="notion-phone-submenu" id="notion-phone-'+key+'" hidden>'+sections.map(([label,list])=>'<div>'+(label?'<p>'+label+'</p>':'')+links(list)+'</div>').join('')+'</div></section>').join('')+'<a class="notion-phone-pricing" href="https://www.notion.com/pricing">Pricing</a></div><div class="notion-phone-actions"><a href="https://www.notion.com/download">Download app</a><a href="https://www.notion.com/login">Log in</a></div>';header.append(overlay);
 const close=overlay.querySelector('.notion-phone-close'),buttons=[...overlay.querySelectorAll('[data-phone-group]')],content=[document.querySelector('main'),document.querySelector('footer'),document.querySelector('.locale')];let open=false,expanded='',closeTimer,overflowBefore='';trigger.setAttribute('aria-controls',overlay.id);trigger.setAttribute('aria-label','Toggle main menu');
 function expand(key){expanded=expanded===key?'':key;overlay.dataset.expanded=expanded;buttons.forEach(b=>{const active=b.dataset.phoneGroup===expanded;b.setAttribute('aria-expanded',String(active));document.getElementById(b.getAttribute('aria-controls')).hidden=!active;});}
 function hide(){if(!open)return;open=false;overlay.dataset.open='false';trigger.setAttribute('aria-expanded','false');desktop.classList.remove('mobile-open');content.forEach(e=>e.inert=false);document.body.style.overflow=overflowBefore;trigger.focus({preventScroll:true});clearTimeout(closeTimer);closeTimer=setTimeout(()=>{if(!open)overlay.hidden=true;},reduce.matches?0:350);}
 function show(){clearTimeout(closeTimer);overflowBefore=document.body.style.overflow;desktop.hidden=true;desktop.classList.add('mobile-open');open=true;overlay.hidden=false;overlay.dataset.open='false';content.forEach(e=>e.inert=true);document.body.style.overflow='hidden';trigger.setAttribute('aria-expanded','true');void overlay.offsetWidth;overlay.dataset.open='true';close.focus({preventScroll:true});}
 trigger.onclick=e=>{if(!phone.matches){desktopToggle?.call(trigger,e);return;}open?hide():show();};buttons.forEach(b=>b.onclick=()=>expand(b.dataset.phoneGroup));close.onclick=hide;overlay.addEventListener('click',e=>{if(e.target.closest('a'))hide();});
 document.addEventListener('keydown',e=>{if(!open)return;if(e.key==='Escape'){e.preventDefault();hide();}else if(e.key==='Tab'){const items=[...overlay.querySelectorAll('a,button')].filter(x=>x.getClientRects().length);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});phone.addEventListener('change',()=>{if(!phone.matches)hide();});
})();
