function atlasImage(url){return window.AtlasAssets?window.AtlasAssets.attach(new Image(),url):Object.assign(new Image(),{src:url});}
// A query override makes the reduced-motion branch reviewable without changing browser settings.
const motionOverride=new URLSearchParams(location.search).get('motion')==='reduce';
if(motionOverride)document.documentElement.dataset.motion='reduce';
function motionReduced(){return motionOverride||matchMedia('(prefers-reduced-motion: reduce)').matches;}
const cast=[{name:'主人公',code:'JOKER',voice:'PROTAGONIST / CV 福山润',text:'白天，是刚刚转学的高中生。夜晚，是潜入人心、夺取扭曲欲望的怪盗团团长。',art:'joker',persona:'arsene',personaName:'ARSÈNE / 阿尔赛纳'},{name:'坂本龙司',code:'SKULL',voice:'RYUJI SAKAMOTO / CV 宫野真守',text:'率直而重视伙伴的行动派。与主人公相遇后，觉醒为追寻自由的怪盗。',art:'ryuji',persona:'captain-kidd',personaName:'CAPTAIN KIDD / 船长基德'},{name:'高卷杏',code:'PANTHER',voice:'ANN TAKAMAKI / CV 水树奈奈',text:'拥有强烈的正义感和关怀他人的心。以怪盗之名，直面扭曲人心的不公。',art:'ann',persona:'carmen',personaName:'CARMEN / 卡门'}];let selected=0,costume='thief';const buttons=[...document.querySelectorAll('[data-ch]')],costumes=[...document.querySelectorAll('[data-costume]')];
function render(){const c=cast[selected];document.querySelector('#ch-name').textContent=c.name;document.querySelector('#code').textContent=c.code;document.querySelector('#voice').textContent=c.voice;document.querySelector('#description').textContent=c.text;document.querySelector('#persona-name').textContent=c.personaName;const figure=document.querySelector('#character-art');figure.src='assets/'+c.art+'-'+costume+'.png';figure.alt=c.name+(costume==='school'?'制服立绘':'怪盗立绘');const p=document.querySelector('#persona-art');p.src='assets/'+c.persona+'.png';p.alt=c.personaName;buttons.forEach((b,i)=>b.setAttribute('aria-pressed',String(i===selected)));costumes.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.costume===costume)));document.querySelector('.ch-number').innerHTML=String(selected+1).padStart(2,'0')+' <span>/ 03</span>';}
buttons.forEach((b,i)=>{b.addEventListener('click',()=>{switchCharacter(i)});b.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();switchCharacter(selected+(e.key==='ArrowRight'?1:-1));buttons[selected].focus()}})});costumes.forEach(b=>b.addEventListener('click',()=>{costume=b.dataset.costume;render();const art=document.querySelector('#character-art');art.classList.remove('costume-fade');void art.offsetWidth;art.classList.add('costume-fade')}));

let castAnimations=[];function switchCharacter(next){next=Math.max(0,Math.min(cast.length-1,next));if(next===selected)return;castAnimations.forEach(a=>a.cancel());document.querySelectorAll('.motion-ghost').forEach(e=>e.remove());const direction=next>selected?1:-1;const pieces=[document.querySelector('#character-art'),document.querySelector('#persona-art'),document.querySelector('.profile')];const outgoing=pieces.map(el=>{const clone=el.cloneNode(true);clone.removeAttribute('id');clone.querySelectorAll('[id]').forEach(n=>n.removeAttribute('id'));clone.classList.add('motion-ghost');clone.setAttribute('aria-hidden','true');clone.inert=true;el.after(clone);return clone;});selected=next;render();document.querySelector('#characters').dataset.transition=motionReduced()?'instant':'slide-500';if(motionReduced()){outgoing.forEach(e=>e.remove());return;}castAnimations=pieces.map((el,i)=>{const transform=getComputedStyle(el).transform;const base=transform==='none'?'':' '+transform;const anim=el.animate([{transform:`translateX(${direction*100}vw)${base}`},{transform:`translateX(0)${base}`}],{duration:500,easing:'ease'});const old=outgoing[i].animate([{transform:`translateX(0)${base}`},{transform:`translateX(${-direction*100}vw)${base}`}],{duration:500,easing:'ease'});old.onfinish=()=>outgoing[i].remove();return anim;});castAnimations[0].onfinish=()=>document.querySelector('#characters').dataset.transition='idle';}


// The six public star textures and motion parameters follow source modules 175/558/562.
const royalHero=document.querySelector('.hero'),ambientToggle=document.querySelector('#ambient-toggle');let ambientPaused=motionReduced();const bgCanvas=document.querySelector('#royal-bg-stars'),kvCanvas=document.querySelector('#royal-kv-stars'),bgCtx=bgCanvas.getContext('2d'),kvCtx=kvCanvas.getContext('2d'),textures=Array.from({length:6},(_,i)=>{const im=atlasImage('assets/star'+(i+1)+'.png');return im;});let stars=[],kvStars=[],lastY=scrollY,lastTime=0,raf;
function createStar(y){return{x:Math.random()*innerWidth,y:y??Math.random()*innerHeight+innerHeight,anchor:Math.random(),texture:Math.floor(Math.random()*6),factor:Math.random()*2+1,delay:Math.random()*5000};}
function resizeStars(){bgCanvas.width=innerWidth;bgCanvas.height=innerHeight;kvCanvas.width=royalHero.clientWidth;kvCanvas.height=royalHero.clientHeight;stars=Array.from({length:15},()=>createStar());const w=kvCanvas.width,h=kvCanvas.height;kvStars=[[100,40],[25,180],[w-100,100],[w-170,h-230],[w/2-530,h-320]].map(([x,y])=>({...createStar(y),x,anchor:.5}));drawStars(lastTime);}
function renderStars(ctx,items,t){ctx.clearRect(0,0,ctx.canvas.width,ctx.canvas.height);ctx.globalCompositeOperation='screen';for(const s of items){const im=textures[s.texture];if(!im.complete||!im.naturalWidth)continue;const elapsed=Math.max(0,t-s.delay),alpha=motionReduced()?.5:(1-Math.cos(Math.PI*elapsed/3000))/2;ctx.globalAlpha=alpha;ctx.drawImage(im,s.x-im.naturalWidth*s.anchor,s.y,im.naturalWidth,im.naturalHeight);}ctx.globalAlpha=1;}
function drawStars(t){lastTime=t;renderStars(bgCtx,stars,t);renderStars(kvCtx,kvStars,t);}
function frame(t){drawStars(t);if(!ambientPaused&&!document.hidden&&!motionReduced())raf=requestAnimationFrame(frame);}
function ambientState(){cancelAnimationFrame(raf);ambientToggle.disabled=motionReduced();ambientToggle.setAttribute('aria-pressed',String(ambientPaused));ambientToggle.textContent=ambientPaused?'▶︎ AMBIENT':'Ⅱ AMBIENT';ambientToggle.setAttribute('aria-label',ambientPaused?'播放星光':'暂停星光');if(!ambientPaused&&!document.hidden&&!motionReduced())raf=requestAnimationFrame(frame);else drawStars(lastTime);}
ambientToggle.addEventListener('click',()=>{ambientPaused=!ambientPaused;ambientState();});addEventListener('resize',resizeStars);addEventListener('scroll',()=>{const delta=lastY-scrollY;lastY=scrollY;stars.forEach((s,i)=>{s.y+=delta/s.factor;if(s.y<-300||s.y>innerHeight*2)stars[i]=createStar();});if(ambientPaused||motionReduced())drawStars(lastTime);},{passive:true});textures.forEach(im=>im.onload=()=>drawStars(lastTime));resizeStars();ambientState();document.addEventListener('visibilitychange',ambientState);matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',()=>{if(motionReduced())ambientPaused=true;ambientState();});
// Independent infinite center-mode sliders. Clones preserve continuous end-to-start movement.
const lifeContent={school:[['school_life_ss1.png','探索东京与放学后的日常'],['school_life_ss2.png','学校生活与同伴交流'],['school_life_ss3.png','建立羁绊，度过自己的时间'],['school_life_ss4.png','参加课堂与校园活动'],['school_life_ss5.png','发现新的日常体验']],phantom:[['phantom_life_ss1.png','夜晚，与怪盗团进入异世界'],['phantom_life_ss2.png','直面扭曲欲望与战斗'],['phantom_life_ss3.png','以团队行动夺取人心']]};
document.querySelectorAll('.life-carousel').forEach(root=>{const data=lifeContent[root.dataset.life],track=root.querySelector('.life-track'),viewport=root.querySelector('.life-viewport');let pos=1,logical=0,locked=false,pending=0,touchX=null;const rows=[data[data.length-1],...data,data[0]];rows.forEach(([image,label],i)=>{const card=document.createElement('article');card.className='life-card';card.innerHTML='<img src="assets/'+image+'" alt="'+label+'"><p>'+label+'</p>';if(i===0||i===rows.length-1){card.setAttribute('aria-hidden','true');card.inert=true;}track.append(card);});function paint(instant=false){const cards=[...track.children],width=cards[0].getBoundingClientRect().width,offset=(viewport.clientWidth-width)/2;track.style.transition=instant||motionReduced()?'none':'transform 500ms ease';track.style.transform='translateX('+(offset-pos*width)+'px)';cards.forEach((c,i)=>c.classList.toggle('is-current',i===pos));root.querySelector('.life-count').textContent=(logical+1)+' / '+data.length;root.dataset.slide=String(logical);}
function move(dir){if(locked){pending=dir;return;}pos+=dir;logical=(logical+dir+data.length)%data.length;locked=!motionReduced();paint();if(motionReduced()){if(pos===0)pos=data.length;if(pos===data.length+1)pos=1;paint(true);return;}setTimeout(()=>{if(pos===0)pos=data.length;if(pos===data.length+1)pos=1;paint(true);locked=false;if(pending){const next=pending;pending=0;move(next);}},500);}
root.querySelector('.life-prev').onclick=()=>move(-1);root.querySelector('.life-next').onclick=()=>move(1);root.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();move(e.key==='ArrowRight'?1:-1);}});viewport.addEventListener('touchstart',e=>touchX=e.touches[0].clientX,{passive:true});viewport.addEventListener('touchend',e=>{if(touchX!==null){const dx=e.changedTouches[0].clientX-touchX;if(Math.abs(dx)>40)move(dx<0?1:-1);touchX=null;}},{passive:true});addEventListener('resize',()=>paint(true));paint(true);});
