// A query override makes the reduced-motion branch reviewable without changing browser settings.
const motionOverride=new URLSearchParams(location.search).get('motion')==='reduce';
if(motionOverride)document.documentElement.dataset.motion='reduce';
function motionReduced(){return motionOverride||matchMedia('(prefers-reduced-motion: reduce)').matches;}
const cast=[{name:'主人公',code:'JOKER',voice:'PROTAGONIST / CV 福山润',text:'白天，是刚刚转学的高中生。夜晚，是潜入人心、夺取扭曲欲望的怪盗团团长。',art:'joker',persona:'arsene',personaName:'ARSÈNE / 阿尔赛纳'},{name:'坂本龙司',code:'SKULL',voice:'RYUJI SAKAMOTO / CV 宫野真守',text:'率直而重视伙伴的行动派。与主人公相遇后，觉醒为追寻自由的怪盗。',art:'ryuji',persona:'captain-kidd',personaName:'CAPTAIN KIDD / 船长基德'},{name:'高卷杏',code:'PANTHER',voice:'ANN TAKAMAKI / CV 水树奈奈',text:'拥有强烈的正义感和关怀他人的心。以怪盗之名，直面扭曲人心的不公。',art:'ann',persona:'carmen',personaName:'CARMEN / 卡门'}];let selected=0,costume='thief';const buttons=[...document.querySelectorAll('[data-ch]')],costumes=[...document.querySelectorAll('[data-costume]')];
function render(){const c=cast[selected];document.querySelector('#ch-name').textContent=c.name;document.querySelector('#code').textContent=c.code;document.querySelector('#voice').textContent=c.voice;document.querySelector('#description').textContent=c.text;document.querySelector('#persona-name').textContent=c.personaName;const figure=document.querySelector('#character-art');figure.src='assets/'+c.art+'-'+costume+'.png';figure.alt=c.name+(costume==='school'?'制服立绘':'怪盗立绘');const p=document.querySelector('#persona-art');p.src='assets/'+c.persona+'.png';p.alt=c.personaName;buttons.forEach((b,i)=>b.setAttribute('aria-pressed',String(i===selected)));costumes.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.costume===costume)));document.querySelector('.ch-number').innerHTML=String(selected+1).padStart(2,'0')+' <span>/ 03</span>';}
buttons.forEach((b,i)=>{b.addEventListener('click',()=>{switchCharacter(i)});b.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();switchCharacter(selected+(e.key==='ArrowRight'?1:-1));buttons[selected].focus()}})});costumes.forEach(b=>b.addEventListener('click',()=>{costume=b.dataset.costume;render()}));

let castAnimations=[];function switchCharacter(next){next=Math.max(0,Math.min(cast.length-1,next));if(next===selected)return;castAnimations.forEach(a=>a.cancel());document.querySelectorAll('.motion-ghost').forEach(e=>e.remove());const direction=next>selected?1:-1;const pieces=[document.querySelector('#character-art'),document.querySelector('#persona-art'),document.querySelector('.profile')];const outgoing=pieces.map(el=>{const clone=el.cloneNode(true);clone.removeAttribute('id');clone.querySelectorAll('[id]').forEach(n=>n.removeAttribute('id'));clone.classList.add('motion-ghost');clone.setAttribute('aria-hidden','true');clone.inert=true;el.after(clone);return clone;});selected=next;render();document.querySelector('#characters').dataset.transition=motionReduced()?'instant':'slide-500';if(motionReduced()){outgoing.forEach(e=>e.remove());return;}castAnimations=pieces.map((el,i)=>{const transform=getComputedStyle(el).transform;const base=transform==='none'?'':' '+transform;const anim=el.animate([{transform:`translateX(${direction*100}vw)${base}`},{transform:`translateX(0)${base}`}],{duration:500,easing:'ease'});const old=outgoing[i].animate([{transform:`translateX(0)${base}`},{transform:`translateX(${-direction*100}vw)${base}`}],{duration:500,easing:'ease'});old.onfinish=()=>outgoing[i].remove();return anim;});castAnimations[0].onfinish=()=>document.querySelector('#characters').dataset.transition='idle';}

const royalHero=document.querySelector('.hero'),ambientToggle=document.querySelector('#ambient-toggle');let ambientPaused=motionReduced();function ambientState(){ambientToggle.disabled=motionReduced();royalHero.classList.toggle('ambient-paused',ambientPaused);ambientToggle.setAttribute('aria-pressed',String(ambientPaused));ambientToggle.textContent=ambientPaused?'▶ AMBIENT':'Ⅱ AMBIENT';ambientToggle.setAttribute('aria-label',ambientPaused?'播放本地金色光点':'暂停本地金色光点');}ambientToggle.addEventListener('click',()=>{ambientPaused=!ambientPaused;ambientState();});ambientState();new IntersectionObserver(es=>royalHero.classList.toggle('media-offscreen',es[0].intersectionRatio<.15),{threshold:[0,.15]}).observe(royalHero);matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',()=>{if(motionReduced())ambientPaused=true;ambientState();});

document.addEventListener('visibilitychange',()=>royalHero.classList.toggle('page-hidden',document.hidden));
