(()=>{'use strict';
const query=new URLSearchParams(location.search),preference=matchMedia('(prefers-reduced-motion: reduce)');let reduced=query.get('motion')==='reduce'||preference.matches;
if(reduced)document.documentElement.classList.add('motion-reduced');
const terminal=document.querySelector('#terminal'),video=document.querySelector('#scene-video'),frame=document.querySelector('#scene-frame'),plate=document.querySelector('#selected-plate'),scrub=document.querySelector('#scene-scrub'),clock=document.querySelector('#source-clock'),viewStatus=document.querySelector('#view-status'),playToggle=document.querySelector('#play-toggle'),status=document.querySelector('#media-status'),statusCopy=document.querySelector('#media-status-copy');
const scenes={permission:{start:19.2,duration:4.2,still:22,title:'许可环线',alt:'官方22秒许可画面：黑白细弧环、橙色节点与中心圆形'},archive:{start:27,duration:12.2,still:35,title:'档案阵列',alt:'官方35秒画面：大量平行透明档案，单件抽出及细射线'},optics:{start:39.2,duration:12.32,still:48,title:'双环光学',alt:'官方48秒画面：大小双环、灰色透明光学材质及橙色内缘'},matrix:{start:59.6,duration:13.8,still:68,title:'机构矩阵',alt:'官方68秒科室构图：CMPT CTRL中心及九个外围缩写、射线与橙色节点'}};
const order=Object.keys(scenes);let scene='archive',view='interactive',request=0,continuous=false,loadTimer=0,failed=false;
function format(seconds){const minute=Math.floor(seconds/60);return String(minute).padStart(2,'0')+':'+(seconds-minute*60).toFixed(2).padStart(5,'0');}
function statusText(){viewStatus.textContent=view==='interactive'?'静态原帧 / 本地点选':video.paused?'原作片段 / 已暂停':'原作片段 / 播放中';playToggle.textContent=view==='film'&&!video.paused?'暂停动效':view==='film'?'继续动效':'播放原作动效';}
function setClock(time){clock.textContent='原作 '+format(time);}
function showInteractive(){request++;clearTimeout(loadTimer);video.pause();view='interactive';terminal.dataset.view=view;status.hidden=true;failed=false;frame.src='assets/'+scene+'-frame.png';frame.alt=scenes[scene].alt;scrub.max=String(scenes[scene].duration);scrub.value=String(scenes[scene].still-scenes[scene].start);setClock(scenes[scene].still);statusText();document.querySelector('#array-toggle').hidden=scene!=='archive';}
function chooseScene(name){if(!scenes[name])return;scene=name;terminal.dataset.scene=name;terminal.classList.remove('array-hidden');document.querySelector('#array-toggle').setAttribute('aria-pressed','true');document.querySelector('#array-toggle').textContent='阵列：显示';document.querySelectorAll('[data-scene]').forEach(b=>{if(b.tagName==='BUTTON')b.setAttribute('aria-pressed',String(b.dataset.scene===scene));});plate.style.setProperty('--plate-x','0px');plate.style.setProperty('--plate-y','0px');showInteractive();}
function requestFilm(position=0,autoplay=true){const token=++request;clearTimeout(loadTimer);video.pause();view='film';terminal.dataset.view=view;terminal.classList.remove('array-hidden');document.querySelector('#array-toggle').hidden=true;failed=false;status.hidden=false;statusCopy.textContent='正在准备 '+scenes[scene].title+' 原作片段';document.querySelector('#retry-media').hidden=true;const source='assets/'+scene+'.mp4';const begin=()=>{if(token!==request)return;video.currentTime=Math.min(position,scenes[scene].duration);status.hidden=true;clearTimeout(loadTimer);if(autoplay)video.play().then(statusText).catch(()=>{video.pause();statusText();});else statusText();};const sameSource=video.dataset.source===source;video.dataset.source=source;if(sameSource&&video.readyState>=2)begin();else{if(window.AtlasAssets)window.AtlasAssets.attach(video,source);else video.src=source;video.poster='assets/'+scene+'-frame.png';video.addEventListener('loadeddata',begin,{once:true});video.load();}loadTimer=setTimeout(()=>{if(token!==request||video.readyState>=2)return;failed=true;statusCopy.textContent='片段暂未就绪；可以重试或保留原帧阅读。';document.querySelector('#retry-media').hidden=false;},15000);statusText();}
video.addEventListener('error',()=>{if(view!=='film')return;clearTimeout(loadTimer);failed=true;status.hidden=false;statusCopy.textContent='片段加载失败；原帧与全部阅读入口仍可使用。';document.querySelector('#retry-media').hidden=false;statusText();});
video.addEventListener('timeupdate',()=>{if(view!=='film')return;scrub.value=String(video.currentTime);setClock(scenes[scene].start+video.currentTime);});video.addEventListener('play',statusText);video.addEventListener('pause',statusText);
video.addEventListener('ended',()=>{if(continuous&&!reduced){const next=order.indexOf(scene)+1;if(next<order.length){chooseScene(order[next]);requestFilm(0,true);return;}continuous=false;document.querySelector('#play-all').setAttribute('aria-pressed','false');}statusText();});
document.querySelectorAll('button[data-scene]').forEach(b=>b.onclick=()=>{continuous=false;document.querySelector('#play-all').setAttribute('aria-pressed','false');chooseScene(b.dataset.scene);});
playToggle.onclick=()=>{if(view!=='film'||failed)requestFilm(0,true);else if(!video.paused){video.pause();statusText();}else if(video.ended){video.currentTime=0;video.play().then(statusText).catch(statusText);}else video.play().then(statusText).catch(statusText);};
document.querySelector('#replay').onclick=()=>requestFilm(0,true);document.querySelector('#interactive-view').onclick=showInteractive;document.querySelector('#continue-still').onclick=showInteractive;document.querySelector('#retry-media').onclick=()=>requestFilm(0,!reduced);
document.querySelector('#play-all').onclick=()=>{continuous=!continuous;document.querySelector('#play-all').setAttribute('aria-pressed',String(continuous));if(continuous){chooseScene('permission');requestFilm(0,!reduced);}};
scrub.addEventListener('input',()=>{if(view!=='film')requestFilm(Number(scrub.value),false);else{video.pause();video.currentTime=Number(scrub.value);setClock(scenes[scene].start+Number(scrub.value));statusText();}});
document.querySelector('#reference-only').onchange=e=>terminal.classList.toggle('reference-only',e.target.checked);
document.querySelector('#array-toggle').onclick=e=>{if(scene!=='archive')chooseScene('archive');showInteractive();const hidden=terminal.classList.toggle('array-hidden');e.currentTarget.setAttribute('aria-pressed',String(!hidden));e.currentTarget.textContent=hidden?'阵列：隐藏':'阵列：显示';};
const records=[['多排阵列，单件抽出。','源片先以大量平行立体档案覆盖视野，再抬出一件X-001；不是平面作品卡片行。这里五个按钮是本地教学目录，不代表原片有五个可点击档案。','27.00—35.00'],['细射线，连接焦点。','抽出的透明板保留四角标定、金属边缘、编号与上下两条细射线。射线和机密文字在源片35—38秒出现；网页选择不虚构原作中的权限验证。','34.00—39.20'],['环形渐变，属于光学材质。','原片双环有厚度、透明灰面、反射、橙色内缘、网格参照与镜头旋转。本地使用原片段保留这些细节，不用一个CSS圆框替代它们。','39.20—51.52'],['科室字标，保留连字。','中心CMPT CTRL与九个外围科室同时出现，字标内嵌莱茵环形符号。原帧保留字体与纹理；热点及下方目录只增加可操作语义。','59.60—73.40'],['镜头有方向，片段有边界。','每个片段使用原作1倍速度与25fps。连续播放保留选中四段内部镜头；段间连接为网页编排，略去完整影片其他镜头。','19.20—73.40（选段）']];let selected=0;const recordButtons=[...document.querySelectorAll('[data-record]')],body=document.querySelector('#record-body'),toggle=document.querySelector('#open-record');
function selectRecord(index){selected=(index+records.length)%records.length;chooseScene('archive');recordButtons.forEach((b,i)=>b.setAttribute('aria-pressed',String(i===selected)));document.querySelector('#record-count').textContent='OBSERVATION '+String(selected+1).padStart(2,'0')+' / 05';document.querySelector('#record-title').textContent=records[selected][0];document.querySelector('#record-copy').textContent=records[selected][1];document.querySelector('#record-time').textContent='原作 '+records[selected][2]+' 秒';plate.style.setProperty('--plate-x',reduced?'0px':String(selected*2)+'px');plate.style.setProperty('--plate-y',reduced?'0px':String(selected*-2)+'px');toggle.setAttribute('aria-expanded','false');toggle.textContent='展开观察 ＋';body.hidden=true;}
recordButtons.forEach((b,i)=>{b.onclick=()=>selectRecord(i);b.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();selectRecord(i+(e.key==='ArrowRight'?1:-1));recordButtons[selected].focus();}};});document.querySelector('#previous').onclick=()=>selectRecord(selected-1);document.querySelector('#next').onclick=()=>selectRecord(selected+1);toggle.onclick=()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));toggle.textContent=open?'收起观察 −':'展开观察 ＋';body.hidden=!open;};
const departments=[{code:'CMPT CTRL',name:'COMPONENTS CONTROL SECTION',rect:[788,388,343,342],node:[1090,363],copy:'中心双行字标用黑底白字，C中嵌莱茵环形符号，外围九个科室以细射线联系。网页点击不新增官方组织权限。'},{code:'DEF',name:'DEFENSE SECTION',rect:[154,331,188,185],node:[314,312],copy:'白色半透明方块上的防卫字标。原片的轻微雾化和背景网格通过原帧保留。'},{code:'HRI',name:'HUMAN RESOURCES INVESTIGATION SECTION',rect:[419,374,166,170],node:[558,352],copy:'细窄的黑色缩写与两行完整名称；不要把三字母缩写改成没有连字的普通大字。'},{code:'BSN',name:'BUSINESS SECTION',rect:[501,526,195,99],node:[637,498],copy:'业务科字标旁的橙色空心构件是原片焦点。网页点选移动同一个节点；移动、选中和说明为本地转译。'},{code:'ENG',name:'ENGINEERING SECTION',rect:[267,613,202,205],node:[430,590],copy:'黑色表面上的白色工程字标带透视倾斜；保留原帧像素和位置，避免抹平成等宽卡片。'},{code:'STRU',name:'STRUCTURAL SECTION',rect:[1254,311,198,198],node:[1408,288],copy:'结构科使用斜置的黑白分带表面。图形材质由原帧保留，选择说明由本地同步。'},{code:'SCIEN',name:'SCIENTIFIC INVESTIGATION SECTION',rect:[1617,347,244,149],node:[1815,323],copy:'较长的研究科缩写仍与环形连字一起出现；源码按钮提供完整名称，画面不重新排字。'},{code:'ORIG',name:'ORIGINIUM ART SECTION',rect:[1432,507,230,99],node:[1615,483],copy:'源石技艺字标以横向宽度和特殊连字组织，不把它缩成无解释的ORG。'},{code:'NRG',name:'ENERGY SECTION',rect:[1306,605,196,155],node:[1460,581],copy:'能量科代码为NRG；旧版只取部分机构，现按原帧完整保留全部十个模块。'},{code:'ECO',name:'ECOLOGICAL SECTION',rect:[1554,674,174,170],node:[1682,650],copy:'深色生态科块中，O的内环嵌入机构符号，与其余字标共享视觉系统。'}];
const matrix=document.querySelector('#matrix-picks'),list=document.querySelector('#department-list'),node=document.querySelector('#focus-node');let deptIndex=3;const graphButtons=[],listButtons=[];
departments.forEach((d,i)=>{const hit=document.createElement('button');hit.dataset.department=String(i);hit.setAttribute('aria-label',d.code+' / '+d.name);hit.setAttribute('aria-pressed',String(i===deptIndex));hit.style.cssText='--x:'+d.rect[0]/19.2+';--y:'+d.rect[1]/10.8+';--w:'+d.rect[2]/19.2+';--h:'+d.rect[3]/10.8;hit.onclick=()=>selectDepartment(i);matrix.append(hit);graphButtons.push(hit);const entry=document.createElement('button');entry.dataset.department=String(i);entry.setAttribute('aria-pressed',String(i===deptIndex));const b=document.createElement('b'),s=document.createElement('span');b.textContent=d.code;s.textContent=d.name;entry.append(b,s);entry.onclick=()=>selectDepartment(i);list.append(entry);listButtons.push(entry);});
function selectDepartment(index){deptIndex=index;if(scene!=='matrix')chooseScene('matrix');else showInteractive();const d=departments[index];[...graphButtons,...listButtons].forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.department)===index)));node.style.left=d.node[0]/19.2+'%';node.style.top=d.node[1]/10.8+'%';document.querySelector('#department-code').textContent=d.code;document.querySelector('#department-name').textContent=d.name;document.querySelector('#department-copy').textContent=d.copy;}
function syncMotionPreference(){reduced=query.get('motion')==='reduce'||preference.matches;document.documentElement.classList.toggle('motion-reduced',reduced);const all=document.querySelector('#play-all');all.disabled=reduced;all.textContent=reduced?'逐段手动播放':'连续场景';if(reduced){continuous=false;all.setAttribute('aria-pressed','false');showInteractive();}}
document.addEventListener('visibilitychange',()=>{if(document.hidden)video.pause();});preference.addEventListener('change',syncMotionPreference);if(query.get('reference')==='1'){document.querySelector('#reference-only').checked=true;terminal.classList.add('reference-only');}syncMotionPreference();if(query.has('scene'))chooseScene(query.get('scene'));else showInteractive();
})();
