const mega=document.querySelector('.mega'),menus={Products:['Payments','Billing','Connect','Issuing','Crypto','Agentic commerce'],Solutions:['Enterprise','Startups','Platforms','Marketplaces'],Developers:['Documentation','API reference','Libraries','Developer tools'],Resources:['Customer stories','Guides','Blog','Support']};
(()=>{
 const header=document.querySelector('header'),buttons=[...document.querySelectorAll('[data-menu]')],reduce=matchMedia('(prefers-reduced-motion:reduce)'),desktop=matchMedia('(min-width:641px)'),ease='cubic-bezier(.45,.05,.55,.95)';
 let token=0,phase='closed',key='',leaveTimer,animations=[],activeTrigger=null;
 mega.inert=true;mega.setAttribute('aria-hidden','true');mega.dataset.phase=phase;
 function stop(){animations.forEach(a=>a.cancel());animations=[];}
 function finishOpen(id){if(id!==token||phase==='closing')return;stop();phase='open';mega.dataset.phase=phase;mega.style.height='';mega.style.maxHeight='';}
 function close(focus=false){clearTimeout(leaveTimer);if(phase==='closed')return;const from=getComputedStyle(mega),start={opacity:from.opacity,transform:from.transform,clipPath:from.clipPath,height:mega.getBoundingClientRect().height};const id=++token;stop();phase='closing';mega.dataset.phase=phase;mega.inert=true;mega.setAttribute('aria-hidden','true');buttons.forEach(b=>b.setAttribute('aria-expanded','false'));
  const finish=()=>{if(id!==token||phase!=='closing')return;stop();mega.hidden=true;phase='closed';mega.dataset.phase=phase;mega.style.height='';mega.style.maxHeight='';if(focus)activeTrigger?.focus({preventScroll:true});};
  if(reduce.matches||!desktop.matches){finish();return;}
  const main=mega.animate([{opacity:start.opacity,transform:start.transform,height:start.height+'px'},{opacity:0,transform:'translateY(-12px)',height:start.height+'px'}],{duration:300,easing:ease,fill:'both'}),mask=mega.animate([{clipPath:start.clipPath==='none'?'inset(0 0 0 0)':start.clipPath,maxHeight:start.height+'px'},{clipPath:'inset(0 0 100% 0)',maxHeight:'0px'}],{duration:200,easing:ease,fill:'both'});animations=[main,mask];Promise.allSettled(animations.map(a=>a.finished)).then(finish);
 }
 function show(button){if(!desktop.matches)return;clearTimeout(leaveTimer);if((phase==='open'||phase==='opening')&&key===button.dataset.menu)return;const shown=!mega.hidden,computed=shown?getComputedStyle(mega):null,start={height:shown?mega.getBoundingClientRect().height:0,opacity:computed?.opacity||'0',transform:computed?.transform||'translateY(-12px)',clipPath:computed?.clipPath||'inset(0 0 100% 0)'};const id=++token;stop();key=button.dataset.menu;activeTrigger=button;mega.hidden=false;mega.inert=false;mega.setAttribute('aria-hidden','false');mega.dataset.key=key;mega.querySelector('strong').textContent=key;mega.querySelector('div').innerHTML=menus[key].map(t=>'<a href="#products">'+t+' ↗︎</a>').join('');buttons.forEach(b=>b.setAttribute('aria-expanded',String(b===button)));mega.style.height='';mega.style.maxHeight='';const height=mega.getBoundingClientRect().height;phase='opening';mega.dataset.phase=phase;
  if(reduce.matches){finishOpen(id);return;}
  const main=mega.animate([{height:(shown?start.height:height)+'px',opacity:start.opacity,transform:start.transform},{height:height+'px',opacity:1,transform:'translateY(0)'}],{duration:300,easing:ease,fill:'both'}),mask=mega.animate([{clipPath:start.clipPath==='none'?'inset(0 0 0 0)':start.clipPath,maxHeight:(shown?start.height:0)+'px'},{clipPath:'inset(0 0 0 0)',maxHeight:height+'px'}],{duration:200,easing:ease,fill:'both'});animations=[main,mask];Promise.allSettled(animations.map(a=>a.finished)).then(()=>finishOpen(id));
 }
 buttons.forEach(b=>{b.onclick=()=>show(b);b.addEventListener('mouseenter',()=>{if(matchMedia('(hover:hover)').matches)show(b);});b.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();show(b);mega.querySelector('a')?.focus();}});});
 header.addEventListener('mouseleave',()=>{if(desktop.matches)leaveTimer=setTimeout(()=>close(),140);});header.addEventListener('mouseenter',()=>clearTimeout(leaveTimer));mega.addEventListener('mouseenter',()=>clearTimeout(leaveTimer));
 document.addEventListener('click',e=>{if(desktop.matches&&!e.target.closest('header'))close();});document.addEventListener('keydown',e=>{if(desktop.matches&&e.key==='Escape')close(true);});desktop.addEventListener('change',()=>{if(!desktop.matches)close();});reduce.addEventListener('change',()=>{if(!reduce.matches)return;if(phase==='closing')close();else if(phase!=='closed')finishOpen(token);});
})();
const product=document.querySelector('#product-dialog'),account=document.querySelector('#account-dialog');document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>{product.querySelector('h2').textContent=b.dataset.product;product.querySelector('.dialog-copy').textContent='Explore how '+b.dataset.product+' fits your business.';product.querySelector('.detail-ui').innerHTML='<label>Business model<select><option>Online business</option><option>Subscription business</option><option>Platform business</option></select></label><small>Local interactive preview</small><strong class="preview-status">Ready for online payments</strong>';product.querySelector('select').onchange=e=>product.querySelector('.preview-status').textContent=['Ready for online payments','Recurring revenue enabled','Connected accounts enabled'][e.target.selectedIndex];product.showModal()});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{account.querySelector('h2').textContent=b.dataset.open;account.showModal()});document.querySelectorAll('dialog .close,dialog .close-bottom').forEach(b=>b.onclick=()=>b.closest('dialog').close());const cases=[['Hertz','A consistent checkout experience across locations.','hertz'],['URBN','Connected retail across a family of brands.','urbn'],['Instacart','Payments for a marketplace and its participants.','instacart'],['Le Monde','Recurring payments for a subscription business.','lemonde']];document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-case]').forEach(x=>{x.setAttribute('aria-selected','false');x.querySelector('span').textContent='+'});b.setAttribute('aria-selected','true');b.querySelector('span').textContent='—';let c=cases[+b.dataset.case];document.querySelector('.case-name').textContent=c[0];document.querySelector('#case-copy').textContent=c[1];document.querySelector('#case-link').href='https://stripe.com/customers/'+c[2]});

document.querySelectorAll("[role=tablist]").forEach(list=>list.addEventListener("keydown",e=>{if(!["ArrowRight","ArrowLeft","Home","End"].includes(e.key))return;const buttons=[...list.querySelectorAll("[role=tab]")];if(!buttons.length)return;e.preventDefault();let i=buttons.indexOf(document.activeElement);i=e.key==="Home"?0:e.key==="End"?buttons.length-1:(i+(e.key==="ArrowRight"?1:-1)+buttons.length)%buttons.length;buttons[i].focus();buttons[i].click()}));

// Source navigation opens on real pointer entry. Click and keyboard remain supported.
(()=>{const reduced=matchMedia('(prefers-reduced-motion:reduce)'),roll=document.querySelector('.terminal-roll'),checkout=document.querySelector('.checkout'),logo=document.querySelector('.checkout-brand'),name=document.querySelector('.checkout-name'),price=document.querySelector('.checkout-price'),pay=checkout.querySelector('em'),img=checkout.querySelector('img');const steps=[['ROASTERY','Electric kettle','$65.00'],['SHOWFLIX','Monthly subscription','¥1,886'],['Bloom & Co.','Electric kettle','$65.00']];let n=0,timer,inView=false;function step(){n=(n+1)%steps.length;roll.style.transform='translateY(-'+(n*100)+'%)';checkout.dataset.scene=n;logo.textContent=steps[n][0];name.textContent=steps[n][1];price.textContent=steps[n][2];pay.textContent='Pay '+steps[n][2];img.hidden=n===1;}function sync(){clearInterval(timer);if(inView&&!reduced.matches&&!document.hidden)timer=setInterval(step,5000);}new IntersectionObserver(rows=>{inView=rows[0].isIntersecting;sync();},{threshold:.25}).observe(document.querySelector('.payments'));reduced.addEventListener('change',sync);document.addEventListener('visibilitychange',sync);const customers=document.querySelector('.customers');const clone=customers.cloneNode(true);clone.setAttribute('aria-hidden','true');document.querySelector('.customers-viewport').append(clone);})();
