let era='all';let query='';
const search=document.getElementById('search');const cards=[...document.querySelectorAll('#caves article')];const selected=document.getElementById('selected-filters');
function update(){let count=0;cards.forEach(card=>{const show=(era==='all'||card.dataset.era===era)&&card.dataset.key.includes(query);card.hidden=!show;if(show)count++});document.getElementById('result-count').textContent=`显示 ${count} 个洞窟`;document.getElementById('empty').hidden=count!==0;document.querySelectorAll('[data-era][aria-pressed]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.era===era)));selected.replaceChildren();for(const [kind,value] of [['era',era==='all'?'':era],['query',query]]){if(!value)continue;const chip=document.createElement('button');chip.type='button';chip.textContent=value+' ×';chip.setAttribute('aria-label',`移除${kind==='era'?'时代':'搜索'}条件 ${value}`);chip.addEventListener('click',()=>{if(kind==='era')era='all';else{query='';search.value=''}update();document.getElementById('reset').focus()});selected.append(chip)}}
document.querySelectorAll('.filter-options button').forEach(button=>button.addEventListener('click',()=>{era=button.dataset.era;update()}));
document.getElementById('search-form').addEventListener('submit',event=>{event.preventDefault();query=search.value.trim();update();document.getElementById('catalogue').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})});
document.getElementById('reset').addEventListener('click',()=>{era='all';query='';search.value='';update()});
const viewer=document.getElementById('viewer');const image=document.getElementById('viewer-image');const viewport=document.getElementById('image-viewport');let scale=1;
function zoom(value){scale=Math.max(1,Math.min(3,value));image.style.width=scale*100+'%';document.getElementById('zoom-status').textContent=Math.round(scale*100)+'%';document.getElementById('zoom-out').disabled=scale===1;document.getElementById('zoom-in').disabled=scale===3;if(scale===1){viewport.scrollLeft=0;viewport.scrollTop=0}}
document.getElementById('open-viewer').addEventListener('click',()=>{zoom(1);viewer.showModal()});document.getElementById('close-viewer').addEventListener('click',()=>viewer.close());document.getElementById('zoom-in').addEventListener('click',()=>zoom(scale+.5));document.getElementById('zoom-out').addEventListener('click',()=>zoom(scale-.5));document.getElementById('zoom-reset').addEventListener('click',()=>zoom(1));
