import data from './data.js';
import { TransparentOperator } from './transparent-video.js';
import { LoreViewer } from './lore.js';

const $=(s,root=document)=>root.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
const motionPreference=matchMedia('(prefers-reduced-motion:reduce)'),forcedReduced=new URL(location.href).searchParams.get('motion')==='reduce';
let reduced=motionPreference.matches||forcedReduced;
const assets=window.AtlasAssets;
const wait=ms=>new Promise(resolve=>setTimeout(resolve,reduced?0:ms));
const activate=(el,action,label)=>{if(!el)return;el.tabIndex=0;el.setAttribute('role','button');if(label)el.setAttribute('aria-label',label);el.addEventListener('click',action);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();action(e);}});};
const imageReady=url=>assets.load(url,async src=>{const image=new Image();image.src=src;await image.decode();return image;});
let portraitMode=matchMedia('(orientation:portrait)').matches;
function resize(){portraitMode=innerWidth<=innerHeight;document.documentElement.style.fontSize=(portraitMode?innerWidth/67.5:Math.min(innerWidth/160,innerHeight/90))+'px';document.documentElement.style.setProperty('--vh-offset','0px');$('.home-section-container').style.height=portraitMode?'':innerHeight+'px';positionRoster();}

// Resource completion determines progress; elapsed time never masquerades as bytes loaded.
const loader=$('#entry-loader');let loaderGeneration=0;
async function prepare(){const generation=++loaderGeneration;loader.classList.remove('leaving');loader.hidden=false;$('.entry-loader-error').hidden=true;let count=0;loader.style.setProperty('--progress','0%');
 const home=$('.bg-inner'),title=$('.bg-title');const urls=[home,title].flatMap(e=>[...getComputedStyle(e).backgroundImage.matchAll(/url\(["']?([^"')]+)/g)].map(m=>m[1]));urls.push(data.operators[0].illust,'assets/bg.9e174372.jpg');
 const tasks=[...urls.map(imageReady),document.fonts.load('16px SansMedium'),document.fonts.load('16px Gilroy-Medium'),document.fonts.load('16px Novecentosanswide-DemiBold')];
 const fail=new Set();const run=tasks.map((p,i)=>Promise.race([p,new Promise((_,reject)=>setTimeout(()=>reject(Error('resource timeout')),25000))]).catch(()=>fail.add(i)).finally(()=>{if(generation!==loaderGeneration)return;count++;const progress=Math.round(count/tasks.length*100);loader.style.setProperty('--progress',progress+'%');$('.entry-loader-percent b').textContent=progress;}));
 await Promise.all(run);if(generation!==loaderGeneration)return;if(fail.size){$('.entry-loader-error').hidden=false;return;}finishLoader();
}
function finishLoader(){setTimeout(()=>{$$('[data-animation-element]',document.querySelector('#home')).forEach((e,i)=>{e.style.opacity='1';if(!reduced)e.animate([{opacity:0,transform:'translateY(2rem)'},{opacity:1,transform:'translateY(0)'}],{duration:600,delay:i*100,fill:'both'});});},reduced?0:1500);loaderGeneration++;loader.style.setProperty('--progress','100%');$('.entry-loader-percent b').textContent='100';loader.classList.add('leaving');document.documentElement.dataset.caseLoading='ready';setTimeout(()=>{loader.hidden=true;},reduced?0:2400);}
$('#load-retry').onclick=()=>{assets.retry();prepare();};$('#load-continue').onclick=finishLoader;

// Header hover expands all icon rows, preserving the 300ms source transition.
const rail=$('.header-pc-header-container');rail.addEventListener('pointerenter',()=>rail.classList.add('header-detail-active'));rail.addEventListener('pointerleave',()=>rail.classList.remove('header-detail-active'));rail.addEventListener('focusin',e=>{if(e.target.matches(':focus-visible'))rail.classList.add('header-detail-active');});rail.addEventListener('focusout',e=>{if(!rail.contains(e.relatedTarget))rail.classList.remove('header-detail-active');});
const mobileHeader=$('.header-h5-header-container');function mobileMenu(open){$('.header-menu-icon',mobileHeader).setAttribute('aria-expanded',String(open));mobileHeader.classList.toggle('header-menu-active',open);$$('.header-h5-menu,.header-menu-icon,.header-logo',mobileHeader).forEach(e=>e.classList.toggle('header-active',open));}activate($('.header-menu-icon',mobileHeader),()=>{mobileMenu(!mobileHeader.classList.contains('header-menu-active'));const opened=mobileHeader.classList.contains('header-menu-active');$('.header-menu-icon',mobileHeader).setAttribute('aria-expanded',String(opened));},'展开或收起导航');
const routes=['home','operator','lore','information','calendar','gameplay','notice'];
function navigate(id){$('#operator-directory').hidden=true;document.body.classList.remove('directory-open');mobileMenu(false);history.replaceState(null,'','#'+id);$('#'+id).scrollIntoView({behavior:reduced?'instant':'smooth'});}
$$('.header-inner-container>.header-nav-item').forEach((el,i)=>activate(el,()=>navigate(routes[i]),el.textContent.trim()));
$$('.header-menu-item').forEach((el,i)=>activate(el,()=>navigate(['home','operator','lore','information','calendar','gameplay','aic','notice'][i]),el.textContent.trim()));
$$('.header-logo').filter(e=>!loader.contains(e)).forEach(el=>activate(el,()=>navigate('home'),'返回首页'));
const outgoing=(el,url,label)=>activate(el,()=>window.open(url,'_blank','noopener,noreferrer'),label);
$$('.header-preserve-button,.header-h5-preserve-button,.pc-cn-cloud-game-button,.h5-cn-cloud-game-button').forEach(e=>outgoing(e,'https://endfield.hypergryph.com/','前往终末地官方游戏入口'));
$$('.downloader-item').forEach(e=>{if(e.classList.contains('downloader-hidden'))return;outgoing(e,'https://endfield.hypergryph.com/','官方 '+(e.textContent||$('img',e)?.alt||'下载'));});
$$('.pc-cn-button,.h5-cn-button').forEach(e=>outgoing(e,e.textContent.includes('支付')?'https://user.hypergryph.com/':'https://www.skland.com/','官方 '+e.textContent.trim()));
$$('.header-button').forEach(e=>{if(e.textContent.includes('声音'))return;outgoing(e,'https://user.hypergryph.com/',e.textContent.trim());});

let operatorIndex=0,rosterWindow=1,operatorGeneration=0,mode='2D';
const operatorRoot=$('.operator-section-container');
const player=new TransparentOperator($('.operator-illustration-container'),assets,reduced);
const viewButtons=$$('.operator-switcher3d');viewButtons.forEach(e=>{e.dataset.mode='2D';activate(e,()=>setOperatorMode(mode==='2D'?'3D':'2D'),'切换干员2D和3D');});
// The source renders a moving window. Build the complete directory before positioning it.
const roster=$('.operator-item-container');const rosterTemplate=$('.operator-switch-item',roster);
roster.replaceChildren(...data.operators.map(o=>{const el=rosterTemplate.cloneNode(true);el.classList.remove('operator-active');el.dataset.operator=o.key;el.setAttribute('aria-label',o.name);$('.operator-image',el).dataset.key=o.key;const ring=document.createElement('img');ring.className='operator-active-bg';ring.alt='';ring.src='assets/operator-selection-ring.svg';$('.operator-avatar-ring',el).replaceWith(ring);return el;}));
function positionRoster(){const length=data.operators.length;$$('.operator-switch-item').forEach(el=>{const index=data.operators.findIndex(o=>o.key===el.dataset.operator);let delta=(index-rosterWindow+length)%length;if(delta>length/2)delta-=length;const value=(delta+1)*(portraitMode?13:12.25)+1.875;el.style.transform=portraitMode?'translateX('+value+'rem)':'translateY('+value+'rem)';el.classList.toggle('operator-active',index===operatorIndex);el.setAttribute('aria-pressed',String(index===operatorIndex));el.style.visibility=delta>=-5&&delta<=6?'visible':'hidden';el.tabIndex=delta>=-1&&delta<=2?0:-1;});}
async function flicker(elements,reverse=false){if(reduced)return;for(const duration of (reverse?[70,85,100]:[100,85,70])){await Promise.all(elements.map(e=>e.animate([{opacity:0},{opacity:1}],{duration,easing:'ease-out'}).finished.catch(()=>{})));}}
function writeOperator(o){$$('.operator-illustration').forEach(e=>e.dataset.key=o.key);$$('.operator-title-inner-container .operator-title,.operator-h5-container .operator-name-container .operator-title').forEach(e=>e.textContent=o.name);$$('.operator-h5-container .operator-name-en-container').forEach(e=>{e.children[0].textContent=o.codename;e.children[1].textContent='// '+String(o.index+1).padStart(2,'0');});$$('.operator-h5-container .operator-index').forEach(e=>e.textContent=String(o.index+1).padStart(2,'0')+' / '+data.operators.length);const rec=$('.operator-header-inner-container .operator-name-container');if(rec){rec.children[0].textContent=o.codename;rec.children[1].textContent=`${o.index+1} / ${data.operators.length}`;}
 $$(' .operator-icons').forEach(e=>{e.children[0].dataset.key=o.prof;e.children[1].dataset.key=o.elem;});$$('.operator-content-inner-container,.operator-h5-container .operator-content-container').forEach(e=>{const values=$$('.operator-tag .operator-value',e);[o.campName,o.raceName,o.cv['zh-cn'],o.cv['ja-jp']].forEach((text,i)=>{if(values[i])values[i].textContent=text;});});
 $$('.operator-detail .inner').forEach(e=>{e.replaceChildren(...o.profile.map(line=>{const p=document.createElement('div');p.className='operator-line';p.textContent=line;return p;}));});
 $$('.operator-stars').forEach(e=>{e.replaceChildren(...Array.from({length:o.rarity},()=>{const star=document.createElement('div');star.className='operator-star';return star;}));});positionRoster();
}
async function selectOperator(index){const token=++operatorGeneration;operatorIndex=(index+data.operators.length)%data.operators.length;rosterWindow=operatorIndex;mode='2D';player.stop();const layers=[$('.operator-illustration-container'),...$$('.operator-header-inner-container,.operator-title-inner-container,.operator-content-inner-container')];await flicker(layers,true);if(token!==operatorGeneration)return;writeOperator(data.operators[operatorIndex]);viewButtons.forEach(e=>{e.dataset.mode='2D';e.classList.remove('operator-active');e.setAttribute('aria-pressed','false');});await imageReady(data.operators[operatorIndex].illust).catch(()=>{});if(token===operatorGeneration)await flicker(layers);}
async function setOperatorMode(next){const token=++operatorGeneration;mode=next;viewButtons.forEach(e=>{e.dataset.mode=next;e.classList.toggle('operator-active',next==='3D');e.setAttribute('aria-pressed','false');});await flicker([$('.operator-illustration-container')],true);if(token!==operatorGeneration)return;if(next==='2D'){player.stop();return;}const icon=document.createElement('div');icon.className='operator-loading-icon';icon.textContent='3D';$('.operator-illust-layer').append(icon);try{const operator=data.operators[operatorIndex];await Promise.all([player.play({...operator.video,key:operator.key}),wait(500)]);if(token!==operatorGeneration)return;viewButtons.forEach(e=>e.setAttribute('aria-pressed','true'));}catch{if(token!==operatorGeneration)return;mode='2D';viewButtons.forEach(e=>{e.dataset.mode='2D';e.classList.remove('operator-active');e.setAttribute('aria-pressed','false');});player.stop();icon.textContent='重试';await wait(800);}finally{icon.remove();}}
$$('.operator-switch-item').forEach(e=>activate(e,()=>selectOperator(data.operators.findIndex(o=>o.key===e.dataset.operator)),e.getAttribute('aria-label')));
$$('.operator-prev,.operator-next').forEach(e=>activate(e,()=>selectOperator(operatorIndex+(e.classList.contains('operator-prev')?-1:1)),e.classList.contains('operator-prev')?'上一位干员':'下一位干员'));
// Source switcher arrow names differ between the desktop/mobile wrapper; bind by order.
$$('.operator-operator-switcher').forEach(root=>{const arrows=$$('.operator-button',root);arrows.forEach((e,i)=>activate(e,()=>{rosterWindow=(rosterWindow+(i===0?-4:4)+data.operators.length)%data.operators.length;positionRoster();},i===0?'向上翻动干员头像':'向下翻动干员头像'));});
writeOperator(data.operators[0]);

const directory=$('#operator-directory');const back=document.createElement('button');back.className='directory-back';back.textContent='返回干员档案';directory.firstElementChild.append(back);back.onclick=()=>navigate('operator');
$$('.operator-list-button').forEach(e=>activate(e,()=>{directory.hidden=false;document.body.classList.add('directory-open');history.replaceState(null,'','#operators');scrollTo({top:0,behavior:'instant'});back.focus();},'全部干员'));
$$('.operator-item-operator-item',directory).forEach(e=>{const key=$('.operator-item-image',e).dataset.key;activate(e,()=>{navigate('operator');selectOperator(data.operators.findIndex(o=>o.key===key));},'查看'+data.operators.find(o=>o.key===key).name+'档案');});
const filters={prof:'none',elem:'none'};
$$('.dropdown-root',directory).forEach(root=>{const type=root.classList.contains('dropdown-prof')?'prof':'elem';const trigger=$('.dropdown-trigger',root),panel=$('.dropdown-panel',root);panel.hidden=true;activate(trigger,()=>{panel.hidden=!panel.hidden;root.classList.toggle('dropdown-open',!panel.hidden);trigger.setAttribute('aria-expanded',String(!panel.hidden));},type==='prof'?'干员职业':'属性');$$('.dropdown-option',root).forEach(option=>activate(option,()=>{const key=$('.dropdown-icon',option).dataset.key;filters[type]=key;$$('.dropdown-option',root).forEach(o=>{o.classList.toggle('dropdown-option-selected',o===option);o.setAttribute('aria-selected',String(o===option));});trigger.firstElementChild.textContent=key==='none'?(type==='prof'?'干员职业':'属性'):$('.dropdown-text',option).textContent;$('.dropdown-icon',trigger).dataset.key=key;panel.hidden=true;root.classList.remove('dropdown-open');trigger.setAttribute('aria-expanded','false');$$('.operator-item-operator-item',directory).forEach(card=>{const o=data.operators.find(o=>o.key===$('.operator-item-image',card).dataset.key);card.hidden=!((filters.prof==='none'||filters.prof===o.prof)&&(filters.elem==='none'||filters.elem===o.elem));});},option.textContent.trim()));});

// True binary point clouds: scan, rays, burst rotation, drag, and source model transforms.
const lore=new LoreViewer($('.lore-canvas-container'),data.worldModels,assets,reduced);
let loreIndex=0,loreLock=false;
async function selectLore(index){if(loreLock||lore.lock)return;loreLock=true;loreIndex=(index+data.worldModels.length)%data.worldModels.length;const info=$('.lore-info-wrapper');info.classList.add('switching');try{const change=lore.switchTo(loreIndex);await wait(600);const item=data.worldModels[loreIndex];$('.lore-active-codename').textContent=item.codename;$('.lore-paging').textContent=`${loreIndex+1} / 6`;$('.lore-name').textContent=item.name;$('.lore-active-intro').textContent=item.intro;$$('.lore-navi-dot').forEach((e,i)=>{e.classList.toggle('lore-active',i===loreIndex);e.setAttribute('aria-pressed',String(i===loreIndex));});info.classList.remove('switching');await change;}catch{info.classList.remove('switching');}finally{loreLock=false;}}
activate($('.lore-prev'),()=>selectLore(loreIndex-1),'上一项世界观');activate($('.lore-next'),()=>selectLore(loreIndex+1),'下一项世界观');$$('.lore-navi-dot').forEach((e,i)=>activate(e,()=>selectLore(i),data.worldModels[i].name));

// Three simultaneously visible cards, different scale, real 10s previews and complete-film modal.
let mediaIndex=0,mediaPosition=10,mediaGeneration=0;const mediaRoot=$('#information');const strip=$('.swiper-wrapper',mediaRoot);strip.replaceChildren();
const mediaCards=Array.from({length:data.media.length*3},(_,i)=>{const item=data.media[i%data.media.length];const el=document.createElement('div');el.className='information-info-video';const box=document.createElement('div');box.className='information-cover-box';const image=document.createElement('img');assets.attach(image,item.cover);image.alt=item.title;box.append(image);const mask=document.createElement('div');mask.className='information-mask';box.append(mask);el.append(box);activate(el,()=>showMedia(i%data.media.length),item.title);strip.append(el);return el;});
const previewHost=$('.information-video-container,.information-preview-container,.information-bg-video',mediaRoot)||$('.players-video-container',mediaRoot);const previewVideo=document.createElement('video');previewVideo.muted=true;previewVideo.loop=true;previewVideo.playsInline=true;previewVideo.preload='metadata';if(previewHost){previewHost.replaceChildren(previewVideo);}
function showMedia(index){const token=++mediaGeneration;const nextIndex=(index+data.media.length)%data.media.length;let delta=(nextIndex-mediaIndex+data.media.length)%data.media.length;if(delta>data.media.length/2)delta-=data.media.length;mediaPosition+=delta;mediaIndex=nextIndex;const item=data.media[mediaIndex];mediaCards.forEach((e,i)=>e.classList.toggle('information-active',i===mediaPosition));strip.style.transform=`translateX(${(1-mediaPosition)*100/3}%)`;setTimeout(()=>{if(token!==mediaGeneration||mediaPosition>=10&&mediaPosition<20)return;mediaPosition=mediaIndex+10;strip.style.transition='none';strip.style.transform=`translateX(${(1-mediaPosition)*100/3}%)`;mediaCards.forEach((e,i)=>e.classList.toggle('information-active',i===mediaPosition));requestAnimationFrame(()=>requestAnimationFrame(()=>strip.style.transition=''));},reduced?0:620);const title=$('.information-title',mediaRoot);if(title)title.textContent=item.title;const date=$('.information-time',mediaRoot);if(date)date.textContent=item.date;const cat=$('.information-cate',mediaRoot);if(cat)cat.textContent={SPECIAL:'特别映像',VERSION:'版本PV',CHARACTER:'干员叙事'}[item.category];assets.attach(previewVideo,item.preview);if(!reduced&&previewHost)assets.play(previewVideo).catch(()=>{});const prev=$('.information-nav-info.information-prev',mediaRoot),next=$('.information-nav-info.information-next',mediaRoot);if(prev)prev.innerHTML=`${String((mediaIndex+9)%10+1).padStart(3,'0')} / 010<span class="information-tag">LAST</span>`;if(next)next.innerHTML=`<span class="information-tag">NEXT</span>${String((mediaIndex+1)%10+1).padStart(2,'0')} / 010`;}
activate($('.information-nav-btn.information-prev'),()=>showMedia(mediaIndex-1),'上一段影像');activate($('.information-nav-btn.information-next'),()=>showMedia(mediaIndex+1),'下一段影像');
const dialog=$('#media-dialog'),film=$('video',dialog);activate($('.information-play-btn'),()=>{const item=data.media[mediaIndex];$('.media-official',dialog).href=item.fullVideo;film.src=item.fullVideo;dialog.showModal();film.play().catch(()=>{});},'播放当前官方影像');$('.media-close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{film.pause();film.removeAttribute('src');film.load();});outgoing($('.information-button'),'https://endfield.hypergryph.com/information','更多官方影像');showMedia(0);

// Black mask precedes yellow mask; then the next image opens in the same direction.
function album(section,items){let index=0,locked=false;const root=$('#'+section),detail=$('.gameplay-album-detail',root),top=$('.gameplay-album-top',root),yellow=$('.gameplay-album-middle',root),black=$('.gameplay-album-bottom',root);
 function setInfo(){const item=items[index];$('.gameplay-album-title',detail).textContent=item.title;$('.gameplay-album-description',detail).textContent=item.description;$('.gameplay-album-index',detail).textContent=(index+1)+' / '+items.length;const numbers=$$('.pagination-pagination-number>span',root);if(numbers.length)numbers[0].textContent=index+1;}
 function setMedia(){const item=items[index];top.replaceChildren();if(section==='gameplay'){const video=document.createElement('video');video.muted=true;video.playsInline=true;video.loop=true;video.preload='metadata';assets.attach(video,item.image);top.append(video);if(!reduced)assets.play(video).catch(()=>{});}else{const image=document.createElement('img');assets.attach(image,item.image);image.alt=item.title;top.append(image);assets.attach(yellow,item.image);}}
 function reveal(el,direction,delay){const frames=Array.from({length:41},(_,i)=>{const t=i/40,p=100*(1-Math.pow(1-t,4));return{clipPath:direction>0?'inset(0 0 0 '+(100-p)+'%)':'inset(0 '+(100-p)+'% 0 0)',offset:t};});return el.animate(frames,{duration:reduced?1:400,delay:reduced?0:delay,easing:'linear',fill:'both'}).finished.catch(()=>{});}
 async function change(direction){if(locked)return;locked=true;index=(index+direction+items.length)%items.length;const outgoing=document.createElement('div');outgoing.className='album-outgoing';outgoing.append(...top.childNodes);top.parentNode.prepend(outgoing);setMedia();const textExit=detail.animate([{opacity:1,transform:'translateX(0)'},{opacity:0,transform:'translateX(2rem)'}],{duration:reduced?1:500,easing:'ease-in',fill:'forwards'}).finished.catch(()=>{});const layers=Promise.all([reveal(black,direction,0),reveal(yellow,direction,250),reveal(top,direction,500)]);await textExit;setInfo();const textEntry=detail.animate([{opacity:0,transform:'translateX(-2rem)'},{opacity:1,transform:'translateX(0)'}],{duration:reduced?1:500,easing:'ease-out',fill:'forwards'}).finished.catch(()=>{});await Promise.all([layers,textEntry]);[top,yellow,black,detail].forEach(e=>e.getAnimations().forEach(a=>a.cancel()));$$('video',outgoing).forEach(v=>v.pause());outgoing.remove();locked=false;}
 $$('.pagination-pagination',root).forEach(p=>$$('.pagination-button',p).forEach((e,i)=>activate(e,()=>change(i===0?-1:1),i===0?'上一项'+section:'下一项'+section)));setInfo();setMedia();}
album('gameplay',data.gameplay);album('aic',data.aic);
const noticeCards=$$('.notice-carousel-content-container .carousel-item');let noticeIndex=0;const bulletins=data.bulletins.slice(0,noticeCards.length);
function showNotice(index){noticeIndex=Math.max(0,Math.min(index,noticeCards.length-1));noticeCards.forEach((e,i)=>{const d=i-noticeIndex,n=Math.abs(d);e.style.transform=n?`translateX(calc(${d*100}% ${d>0?'-':'+'} ${2.755+(n-1)*7.76}rem))`:'translateX(0%)';$('.notice-notice-item',e).classList.toggle('notice-active',i===noticeIndex);});const b=bulletins[noticeIndex];$('.notice-title-container .notice-title').textContent=b.title;$('.notice-time').textContent=new Date(b.displayTime*1000).toISOString().slice(0,10).replaceAll('-','.');const numbers=$$('.notice-carousel-pagination .pagination-pagination-number>span');if(numbers[0])numbers[0].textContent=noticeIndex+1;}
$$('.notice-carousel-pagination .pagination-button').forEach((e,i)=>activate(e,()=>showNotice(noticeIndex+(i===0?-1:1)),i===0?'上一条公告':'下一条公告'));noticeCards.forEach((e,i)=>outgoing(e,'https://endfield.hypergryph.com/notice/'+bulletins[i].cid,bulletins[i].title));$$('.notice-detail-button').forEach(e=>outgoing(e,'https://endfield.hypergryph.com/notice','更多官方情报'));showNotice(0);

const observer=new IntersectionObserver(rows=>{for(const row of rows){if(row.isIntersecting){const root=row.target.firstElementChild;root?.classList.add('entered');$$('.section-title-arrow-block,.operator-section-divider',row.target).forEach(e=>e.classList.add(e.classList.contains('operator-section-divider')?'operator-active':'section-title-active'));if(row.target.id==='lore')lore.setVisible(true);$$('video',row.target).filter(v=>v.muted&&!reduced).forEach(v=>assets.play(v).catch(()=>{}));}else{if(row.target.id==='lore')lore.setVisible(false);$$('video',row.target).forEach(v=>assets.pause(v));}}},{threshold:.15});$$('main>.section-viewer-section').forEach(e=>observer.observe(e));
const navObserver=new IntersectionObserver(rows=>{const row=rows.filter(r=>r.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!row)return;const active=routes.indexOf(row.target.id==='aic'?'gameplay':row.target.id);if(active>=0)$('.header-overlay').style.transform=`translateY(${12.625+active*5}rem)`;$$('.header-nav-item').forEach((e,i)=>{e.classList.toggle('header-active',routes[i]===row.target.id||routes[i]==='gameplay'&&row.target.id==='aic');});},{rootMargin:'-20% 0px -45% 0px',threshold:[0,.2,.5]});$$('main>.section-viewer-section').forEach(e=>navObserver.observe(e));
addEventListener('scroll',()=>{const progress=document.documentElement.scrollTop/Math.max(1,document.documentElement.scrollHeight-innerHeight),offset=(300*progress)%120;$$('.gameplay-endfield-pre .gameplay-icon').forEach((el,i)=>el.style.transform='translateX('+(i===0?-offset:120-offset)+'%)');},{passive:true});
document.addEventListener('visibilitychange',()=>{if(document.hidden){player.pause();lore.setVisible(false);$$('video,audio').forEach(e=>e.pause());}else if(mode==='3D')player.resume();});
// The original folded tools use a short divider; hover expands them with the rail.
function paintRailTools(){const expanded=rail.classList.contains('header-detail-active');$$('.header-button-frame-container .header-button',rail).forEach((e,i)=>e.style.transform='translate3d('+(expanded?'.6875':'0')+'rem,'+(.5+i*3.75)+'rem,0)');$$('.header-button-frame-container .header-divider',rail).forEach((e,i)=>e.style.transform='translate3d('+(expanded?'1.125':'1.25')+'rem,'+(3.875+i*3.75)+'rem,0) scaleX('+(expanded?'13.8':'1')+')');}
new MutationObserver(paintRailTools).observe(rail,{attributes:true,attributeFilter:['class']});paintRailTools();
addEventListener('resize',resize);resize();prepare();
if(location.hash==='#operators'){directory.hidden=false;}else if(location.hash&&$(location.hash)){setTimeout(()=>navigate(location.hash.slice(1)),100);}

// Dropdowns close on Escape and outside input, preserving the source visibility class.
function closeFilters(){ $$('.dropdown-root',directory).forEach(root=>{root.classList.remove('dropdown-open');$('.dropdown-panel',root).hidden=true;$('.dropdown-trigger',root).setAttribute('aria-expanded','false');}); }
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeFilters();mobileMenu(false);}});document.addEventListener('pointerdown',e=>{if(!e.target.closest('.dropdown-root'))closeFilters();});
const mobileNotices=$$('.notice-bulletin-item');let mobileNoticeIndex=0;function showMobileNotice(index){mobileNoticeIndex=Math.max(0,Math.min(index,Math.ceil(data.bulletins.length/2)-1));mobileNotices.forEach((el,i)=>{const b=data.bulletins[mobileNoticeIndex*2+i];el.hidden=!b;if(!b)return;assets.attach($('img',el),b.cover);$('img',el).alt=b.title;$('.notice-title',el).textContent=b.title;$('.notice-date',el).textContent=new Date(b.displayTime*1000).toISOString().slice(0,10).replaceAll('-','.');el.dataset.cid=b.cid;});const numbers=$$('.notice-h5-content-container .pagination-pagination-number>span');if(numbers[0])numbers[0].textContent=mobileNoticeIndex+1;}
$$('.notice-h5-content-container .pagination-button').forEach((e,i)=>activate(e,()=>showMobileNotice(mobileNoticeIndex+(i===0?-1:1)),i===0?'上一页公告':'下一页公告'));mobileNotices.forEach(e=>activate(e,()=>window.open('https://endfield.hypergryph.com/notice/'+e.dataset.cid,'_blank','noopener,noreferrer'),'打开官方公告'));showMobileNotice(0);
const bgm=new Audio();bgm.loop=true;bgm.preload='none';assets.attach(bgm,'assets/sound-bgm.3ce37f.mp3');let soundOn=false;const soundButtons=$$('.header-button').filter(e=>e.textContent.includes('声音'));function paintSound(){soundButtons.forEach(e=>{const label=$('.header-text-wrapper',e);if(label)label.textContent='声音: '+(soundOn?'打开':'关闭');e.setAttribute('aria-pressed',String(soundOn));});}soundButtons.forEach(e=>activate(e,async()=>{soundOn=!soundOn;if(soundOn)try{await assets.play(bgm);}catch{soundOn=false;}else bgm.pause();paintSound();},'切换背景音乐'));paintSound();

activate($('.operator-detail-button'),()=>{const drawer=$('.operator-drawer-wrapper');drawer.classList.toggle('operator-active');$('.operator-detail-button').setAttribute('aria-expanded',String(drawer.classList.contains('operator-active')));},'展开或收起干员档案');
$('.operator-illustration-container').addEventListener('operatorvideoerror',()=>{mode='2D';viewButtons.forEach(e=>{e.dataset.mode='2D';e.classList.remove('operator-active');e.setAttribute('aria-pressed','false');});});

// The calendar heading follows the source's normal → fixed → bottom states.
const calendar=$('.calendar-calendar-container'),calendarHeading=$('.calendar-stick-container'),calendarImage=$('.calendar-calendar');
let calendarWidth=0,calendarTick=0;
function positionCalendar(){calendarTick=0;const title=$('.calendar-title'),timeline=$('.calendar-timeline'),height=title.getBoundingClientRect().height+timeline.getBoundingClientRect().height;
 if(height>0)calendarImage.style.marginTop=(height+10)+'px';
 const box=calendar.getBoundingClientRect(),headingHeight=calendarHeading.getBoundingClientRect().height;
 calendarHeading.classList.remove('calendar-stick-fixed','calendar-stick-bottom');calendarHeading.style.removeProperty('width');calendarHeading.style.removeProperty('left');
 if(portraitMode){calendarWidth=0;return;}
 calendarWidth=calendarHeading.getBoundingClientRect().width;
 if(box.top>0)return;
 if(box.bottom<=headingHeight){calendarHeading.classList.add('calendar-stick-bottom');return;}
 calendarHeading.classList.add('calendar-stick-fixed');calendarHeading.style.width=calendarWidth+'px';calendarHeading.style.left=calendarImage.getBoundingClientRect().left+'px';
}
function scheduleCalendar(){if(!calendarTick)calendarTick=requestAnimationFrame(positionCalendar);}
addEventListener('scroll',scheduleCalendar,{passive:true});addEventListener('resize',scheduleCalendar);$$('img',calendar).forEach(img=>img.addEventListener('load',scheduleCalendar));scheduleCalendar();

motionPreference.addEventListener('change',()=>{reduced=motionPreference.matches||forcedReduced;if(reduced){$$('video,audio').forEach(el=>el.pause());for(const animation of document.getAnimations())if(animation.effect?.getTiming().iterations!==Infinity)try{animation.finish();}catch{animation.cancel();}}else{for(const section of $$('main>.section-viewer-section')){const box=section.getBoundingClientRect();if(box.top<innerHeight&&box.bottom>0)$$('video',section).filter(v=>v.muted).forEach(v=>assets.play(v).catch(()=>{}));}}});
