import * as THREE from './vendor/three.module.js';
import shaders from './shaders.js';
/* Independent renderer/control implementation around the observed official xyz binaries,
   shader equations, transforms and scan timing. Original bundle is never executed. */
const ease=t=>t<.5?2*t*t:1-(-2*t+2)**2/2;
const clamp=t=>Math.min(1,Math.max(0,t));
const SCAN_END=2000*Math.log(3)+1000;
// The public source uses seeded gradient noise, rather than independent white noise.
class GradientNoise {
 constructor(seed=Math.floor(Math.random()*10000)){let state=seed;const values=Array.from({length:256},(_,i)=>i);for(let i=255;i>0;i--){state=(9301*state+49297)%233280;const j=state%(i+1);[values[i],values[j]]=[values[j],values[i]];}this.p=values.concat(values);}
 fade(t){return t*t*t*(t*(6*t-15)+10);}
 grad(hash,x,y=0,z=0){const h=hash&15,u=h<8?x:y,v=h<4?y:h===12||h===14?x:z;return(h&1?-u:u)+(h&2?-v:v);}
 lerp(t,a,b){return a+t*(b-a);}
 one(x){const i=Math.floor(x)&255,f=x-Math.floor(x);return(this.lerp(this.fade(f),this.grad(this.p[i],f),this.grad(this.p[i+1],f-1))+1)/2;}
 two(x,y){const p=this.p,i=Math.floor(x)&255,j=Math.floor(y)&255,fx=x-Math.floor(x),fy=y-Math.floor(y),u=this.fade(fx),v=this.fade(fy);return(this.lerp(v,this.lerp(u,this.grad(p[p[i]+j],fx,fy),this.grad(p[p[i+1]+j],fx-1,fy)),this.lerp(u,this.grad(p[p[i]+j+1],fx,fy-1),this.grad(p[p[i+1]+j+1],fx-1,fy-1)))+1)/2;}
}
function noiseTexture(twoDimensions=false){const size=256,noise=new GradientNoise(),values=new Float32Array(size*(twoDimensions?size:1));for(let y=0;y<(twoDimensions?size:1);y++)for(let x=0;x<size;x++){const u=y/size*8,v=x/size*8;values[y*size+x]=twoDimensions?.5*noise.two(u,v)+.25*noise.two(2*u,2*v)+.125*noise.two(4*u,4*v):noise.one(v);}const texture=new THREE.DataTexture(values,size,twoDimensions?size:1,THREE.RedFormat,THREE.FloatType);texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.needsUpdate=true;return texture;}
export class LoreViewer {
 constructor(container,models,assets,reduced){this.container=container;this.models=models;this.assets=assets;this.reduced=reduced;this.visible=false;this.dragging=false;this.targetRotation=0;this.rotation=0;this.frame=0;this.rayFrame=0;this.actors=[];this.rays=[];this.index=-1;this.transitionStart=0;this.changedAt=0;container.replaceChildren();const preference=matchMedia('(prefers-reduced-motion:reduce)'),forced=new URL(location.href).searchParams.get('motion')==='reduce'||reduced&&!preference.matches;preference.addEventListener('change',event=>this.setReducedMotion(forced||event.matches));
  try{this.renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});}catch{container.textContent='此设备无法启动点云渲染';return;}this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(75,1,.1,10000);this.camera.position.set(0,300,2000);container.append(this.renderer.domElement);this.initRays();this.resize();this.ready=Promise.all(models.map(m=>this.load(m)));this.ready.then(()=>this.switchTo(0));
  const down=e=>{if(e.pointerType==='touch'&&Math.abs(e.movementY)>Math.abs(e.movementX))return;this.dragging=true;this.lastX=e.clientX;container.setPointerCapture(e.pointerId);container.style.cursor='grabbing';};container.addEventListener('pointerdown',down);container.addEventListener('pointermove',e=>{if(this.dragging){this.targetRotation+=(e.clientX-this.lastX)*.01;this.lastX=e.clientX;}});const up=()=>{this.dragging=false;container.style.cursor='grab';};container.addEventListener('pointerup',up);container.addEventListener('pointercancel',up);container.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();this.targetRotation+=(e.key==='ArrowLeft'?-.15:.15);}});container.tabIndex=0;container.setAttribute('role','img');container.setAttribute('aria-label','可拖动的世界观点云，左右方向键旋转');addEventListener('resize',()=>this.resize());this.tick=this.tick.bind(this);this.tick();
 }
 async load(model){const response=await this.assets.fetch(model.binarySrc);const raw=new Float32Array(await response.arrayBuffer());if(raw.length%3||!raw.every(Number.isFinite))throw Error('Invalid xyz point cloud');const box=new THREE.Box3();for(let i=0;i<raw.length;i+=3)box.expandByPoint(new THREE.Vector3(raw[i],raw[i+1],raw[i+2]));const center=box.getCenter(new THREE.Vector3()),scale=1900/(box.max.y-box.min.y);const points=new Float32Array(raw.length),more=new Float32Array(raw.length/3*4);for(let i=0;i<raw.length;i+=3){points[i]=(raw[i]-center.x)*scale;points[i+1]=(raw[i+1]-center.y)*scale;points[i+2]=(raw[i+2]-center.z)*scale;const j=i/3*4;more.set([1,4+Math.floor(Math.random()*5),1+Math.floor(Math.random()*3),-100+Math.floor(Math.random()*201)],j);}model.points=points;model.more=more;return model;}
 actor(model){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(model.points,3));geometry.setAttribute('pointMoreData',new THREE.BufferAttribute(model.more,4));const uniforms={};const defaults={scanLineY1:-1150,scanLineY2:-1150,scanLineY3:-1150,scanLineWidth:20,isActive:true,noiseTexture:noiseTexture(true),cameraFadeDistance:model.cameraFadeDistance,cameraFadeStart:model.cameraFadeStart,pointSizeScale:model.pointSizeScale,scanLineYOffsetStrength:30,scanLineYOffsetNoiseStrength:180,featherWidth:.1,coreRadius:.1,innerGlowStrength:.6,compressStrength:.5,resolution:new THREE.Vector2(this.width,1080),glitchEffects0:new THREE.Vector4(),glitchEffects1:new THREE.Vector4(),glitchEffects2:new THREE.Vector4(),glitchEffects3:new THREE.Vector4()};for(const [k,v]of Object.entries(defaults))uniforms[k]={value:v};const material=new THREE.ShaderMaterial({uniforms,vertexShader:shaders.pointVertex,fragmentShader:shaders.pointFragment,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending});const mesh=new THREE.Points(geometry,material);mesh.position.set(-model.pivot.x,-model.pivot.y,-model.pivot.z);const group=new THREE.Group();group.position.set(model.offset.x+model.pivot.x,model.offset.y+model.pivot.y,model.offset.z+model.pivot.z);group.scale.setScalar(model.scale);group.add(mesh);this.scene.add(group);return{group,mesh,model,uniforms,enter:performance.now(),exit:0};}
 async switchTo(index){if(!this.renderer)return;await this.ready;if(index<0||index>=this.models.length||index===this.index||this.lock)return;this.lock=true;this.stopGlitchLoop();const old=this.actors.at(-1);try{if(old){old.exit=performance.now();old.uniforms.isActive.value=false;}this.index=index;this.changedAt=performance.now();this.rayMaterial.uniforms.cameraFadeDistance.value=this.models[index].cameraFadeDistance;const actor=this.actor(this.models[index]);this.actors.push(actor);this.transitionStart=actor.enter;this.container.dataset.model=this.models[index].key;this.container.setAttribute('aria-label',this.models[index].name+'点云，可拖动或方向键旋转');if(this.reduced){for(let i=1;i<=3;i++)actor.uniforms['scanLineY'+i].value=1150;}else await new Promise(resolve=>setTimeout(resolve,SCAN_END));if(old)this.disposeActor(old);if(!this.reduced)this.startGlitchLoop(actor);}finally{this.lock=false;}}
 stopGlitchLoop(){clearTimeout(this.glitchTimer);for(const timer of this.glitchPulses||[])clearTimeout(timer);this.glitchPulses=[];for(const actor of this.actors)for(let i=0;i<4;i++)actor.uniforms['glitchEffects'+i].value.set(0,0,0,0);}
 startGlitchLoop(actor){const pulse=()=>{if(this.reduced||!this.actors.includes(actor))return;this.glitchPulses=[];const count=3+Math.floor(Math.random()*4);for(let p=0;p<count;p++)this.glitchPulses.push(setTimeout(()=>{if(!this.actors.includes(actor))return;const values=Array(16).fill(0),lines=6+Math.floor(Math.random()*3);for(let i=0;i<lines;i++){values[2*i]=-2000+4000*Math.random();values[2*i+1]=(Math.random()>.5?1:-1)*Math.random()*5;}for(let i=0;i<4;i++)actor.uniforms['glitchEffects'+i].value.set(...values.slice(i*4,i*4+4));},80*p));this.glitchPulses.push(setTimeout(()=>{for(let i=0;i<4;i++)actor.uniforms['glitchEffects'+i].value.set(0,0,0,0);},80*count+80));this.glitchTimer=setTimeout(pulse,4000+Math.random()*2000);};this.glitchPulses=[];pulse();}
 disposeActor(actor){this.scene.remove(actor.group);actor.mesh.geometry.dispose();actor.uniforms.noiseTexture.value.dispose();actor.mesh.material.dispose();this.actors=this.actors.filter(a=>a!==actor);}
 resize(){if(!this.renderer)return;this.width=1080*this.container.clientWidth/(this.container.clientHeight||1);this.renderer.setSize(this.width,1080,false);this.camera.aspect=this.width/1080;this.camera.lookAt(innerWidth>innerHeight?0:-550,0,0);this.camera.updateProjectionMatrix();for(const actor of this.actors)actor.uniforms.resolution.value.set(this.width,1080);}
 initRays(){const count=2000;this.rayGeometry=new THREE.InstancedBufferGeometry();this.rayGeometry.instanceCount=count;this.rayGeometry.setAttribute('position',new THREE.Float32BufferAttribute([0,0,0,1,0,0],3));for(const [key,size]of Object.entries({src:3,target:3,progress:1,randomOffset:1,baseOpacity:1}))this.rayGeometry.setAttribute(key,new THREE.InstancedBufferAttribute(new Float32Array(count*size),size));const noise=noiseTexture();this.rayMaterial=new THREE.ShaderMaterial({vertexShader:shaders.laserVertex,fragmentShader:shaders.laserFragment,uniforms:{noiseTexture:{value:noise},cameraFadeDistance:{value:3000}},transparent:true,depthWrite:false,blending:THREE.AdditiveBlending});this.rayMesh=new THREE.LineSegments(this.rayGeometry,this.rayMaterial);this.rayMesh.frustumCulled=false;this.scene.add(this.rayMesh);}
 spawn(actor,line,multiplier){const points=actor.model.points;let made=0;for(let i=0;i<500&&made<20*multiplier;i++){const offset=Math.floor(Math.random()*points.length/3)*3;if(Math.abs(points[offset+1]-line)>40)continue;const target=new THREE.Vector3(points[offset],points[offset+1],points[offset+2]),src=new THREE.Vector3([-3000,400,3000][Math.floor(Math.random()*3)],2000,0);if(actor.model.laserMode==='ceiling'){src.x=target.x;src.z=target.z;}const slot=this.rays.findIndex(r=>!r||performance.now()>r.start+r.duration+r.lifetime);const index=slot<0?this.rays.length:slot;if(index>=2000)break;this.rays[index]={src,target,actor,start:performance.now(),duration:(.5+Math.random())*400*multiplier,lifetime:(.5+Math.random())*400*multiplier,opacity:.8*Math.random()*multiplier,random:Math.random()};made++;}}
 updateRays(now){const geom=this.rayGeometry;for(let i=0;i<2000;i++){const ray=this.rays[i];if(!ray||now>ray.start+ray.duration+ray.lifetime){geom.attributes.progress.setX(i,0);continue;}const target=ray.target.clone().add(ray.actor.mesh.position).applyMatrix4(ray.actor.group.matrixWorld);const src=ray.src.clone();if(ray.actor.model.laserMode==='ceiling')src.add(ray.actor.mesh.position).applyMatrix4(ray.actor.group.matrixWorld);geom.attributes.src.setXYZ(i,src.x,src.y,src.z);geom.attributes.target.setXYZ(i,target.x,target.y,target.z);geom.attributes.progress.setX(i,clamp((now-ray.start)/ray.duration));geom.attributes.randomOffset.setX(i,ray.random);geom.attributes.baseOpacity.setX(i,ray.opacity);}for(const attr of Object.values(geom.attributes))attr.needsUpdate=true;}
 tick(){this.frame=requestAnimationFrame(this.tick);if(!this.visible||!this.renderer)return;const now=performance.now(),age=now-this.changedAt;if(!this.dragging&&!this.reduced){let speed=.005;if(this.lock&&age<2000)speed*=age<400?1+19*ease(clamp(age/400)):age<1200?20:20-19*ease(clamp((age-1200)/800));this.targetRotation+=speed;}this.rotation+=(this.targetRotation-this.rotation)*.1;
  for(const actor of this.actors){actor.group.rotation.y=this.rotation;for(let i=0;i<3;i++){const elapsed=now-(actor.exit||actor.enter);const duration=actor.exit?2000:3000/(i+1),delay=actor.exit?0:2000*Math.log(i+1);actor.uniforms['scanLineY'+(i+1)].value=this.reduced?1150:actor.exit?-1150+2300*ease(clamp(elapsed/2000)):-1350+2500*ease(clamp((elapsed-delay)/duration));}if(!this.reduced&&this.lock&&actor===this.actors.at(-1)&&++this.rayFrame%2===0){this.spawn(actor,actor.uniforms.scanLineY1.value,1);this.spawn(actor,actor.uniforms.scanLineY2.value,.4);}}
  this.scene.updateMatrixWorld();this.updateRays(now);this.renderer.render(this.scene,this.camera);
 }
 setVisible(value){this.visible=value;}
 setReducedMotion(value){if(this.reduced===value)return;this.reduced=value;this.stopGlitchLoop();if(value){this.targetRotation=this.rotation;this.rays=[];for(const actor of this.actors)for(let i=1;i<=3;i++)actor.uniforms['scanLineY'+i].value=1150;}else if(!this.lock&&this.actors.length)this.startGlitchLoop(this.actors.at(-1));}
}
