/* Source mechanism: official module 25221 / 40489. Public RGB-left + luma-alpha-right
   video, not a draggable character model. Independently implemented frame lifecycle. */
export class TransparentOperator {
 constructor(host,assets,reduced){this.host=host;this.assets=assets;this.reduced=reduced;this.generation=0;this.frame=0;this.container=document.createElement('div');this.container.className='operator-video-container';this.elementContainer=document.createElement('div');this.elementContainer.className='operator-video-ele-container';this.elementContainer.style.opacity='1';this.node=document.createElement('div');this.node.className='transparent-video-container operator-video';this.video=document.createElement('video');this.video.muted=true;this.video.playsInline=true;this.video.crossOrigin='anonymous';this.video.preload='none';this.canvas=document.createElement('canvas');this.node.append(this.video,this.canvas);this.elementContainer.append(this.node);this.container.append(this.elementContainer);host.append(this.container);this.gl=this.canvas.getContext('webgl',{alpha:true});this.init();this.video.addEventListener('pause',()=>this.cancelFrame());this.video.addEventListener('play',()=>{if(this.reduced){this.video.pause();return;}if(this.node.classList.contains('active'))this.schedule(this.generation);});const preference=matchMedia('(prefers-reduced-motion:reduce)'),forced=new URL(location.href).searchParams.get('motion')==='reduce'||reduced&&!preference.matches;preference.addEventListener('change',event=>this.setReducedMotion(forced||event.matches));}
 init(){const gl=this.gl;if(!gl){this.context=this.canvas.getContext('2d',{willReadFrequently:true});return;}const shader=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};this.program=gl.createProgram();gl.attachShader(this.program,shader(gl.VERTEX_SHADER,'attribute vec2 p;varying vec2 uv;void main(){gl_Position=vec4(p,0.,1.);uv=p*.5+.5;uv.y=1.-uv.y;}'));gl.attachShader(this.program,shader(gl.FRAGMENT_SHADER,'precision mediump float;uniform sampler2D movie;varying vec2 uv;void main(){vec3 rgb=texture2D(movie,vec2(uv.x*.5,uv.y)).rgb;vec3 mask=texture2D(movie,vec2(uv.x*.5+.5,uv.y)).rgb;gl_FragColor=vec4(rgb,dot(mask,vec3(.3,.59,.11)));}'));gl.linkProgram(this.program);if(!gl.getProgramParameter(this.program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(this.program));gl.useProgram(this.program);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,1,1]),gl.STATIC_DRAW);const p=gl.getAttribLocation(this.program,'p');gl.enableVertexAttribArray(p);gl.vertexAttribPointer(p,2,gl.FLOAT,false,0,0);this.texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,this.texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.clearColor(0,0,0,0);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.DST_ALPHA);gl.uniform1i(gl.getUniformLocation(this.program,'movie'),0);}
 async load(url,token=this.generation){this.cancelLoad?.();const loaded=await new Promise((resolve,reject)=>{let settled=false;const clear=()=>{clearTimeout(timer);this.video.removeEventListener('loadeddata',ok);this.video.removeEventListener('error',fail);if(this.cancelLoad===cancel)this.cancelLoad=null;};const finish=(value,error)=>{if(settled)return;settled=true;clear();error?reject(error):resolve(value);};const cancel=()=>finish(false);const ok=()=>finish(token===this.generation);const fail=()=>finish(false,Error('Character video unavailable'));const timer=setTimeout(fail,25000);this.cancelLoad=cancel;this.video.addEventListener('loadeddata',ok);this.video.addEventListener('error',fail);try{this.assets.attach(this.video,url);this.video.load();}catch(error){finish(false,error);}});if(!loaded||token!==this.generation)return false;if(!this.video.videoWidth||this.video.videoWidth%2||!this.video.videoHeight)throw Error('Invalid RGB-alpha media dimensions');this.canvas.width=this.video.videoWidth/2;this.canvas.height=this.video.videoHeight;if(this.gl)this.gl.viewport(0,0,this.canvas.width,this.canvas.height);return true;}
 async play(resources){const token=++this.generation;this.elementContainer.dataset.key=resources.key||'';this.cancelFrame();this.video.pause();this.video.onended=null;this.video.loop=false;this.node.classList.remove('active');this.host.classList.remove('showing-3d');let idle=this.reduced;if(!await this.load(idle?resources.idle:resources.enter,token)||token!==this.generation)return;if(this.reduced&&!idle){idle=true;if(!await this.load(resources.idle,token)||token!==this.generation)return;}this.video.loop=idle;this.node.classList.add('active');this.host.classList.add('showing-3d');this.draw();this.video.onended=async()=>{if(token!==this.generation)return;this.cancelFrame();try{if(!await this.load(resources.idle,token)||token!==this.generation)return;this.video.loop=true;if(!this.reduced)await this.assets.play(this.video);else await this.renderStill(token);if(token===this.generation&&!this.reduced)this.schedule(token);}catch(error){if(token!==this.generation)return;this.stop();this.host.dispatchEvent(new CustomEvent('operatorvideoerror',{detail:{stage:'idle',message:error.message}}));}};if(this.reduced){await this.renderStill(token);return;}await this.assets.play(this.video);if(token===this.generation)this.schedule(token);}
 async renderStill(token){if(token!==this.generation)return;if(this.video.currentTime===0&&this.video.duration>0)await new Promise(resolve=>{const finish=()=>{clearTimeout(timer);this.video.removeEventListener('seeked',finish);resolve();};const timer=setTimeout(finish,2500);this.video.addEventListener('seeked',finish,{once:true});this.video.currentTime=Math.min(1/30,this.video.duration/2);});if(token===this.generation&&this.reduced)this.draw();}
 draw(){if(this.video.readyState<2)return;const gl=this.gl;if(gl){gl.useProgram(this.program);gl.bindTexture(gl.TEXTURE_2D,this.texture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGB,gl.RGB,gl.UNSIGNED_BYTE,this.video);gl.clear(gl.COLOR_BUFFER_BIT);gl.drawArrays(gl.TRIANGLE_STRIP,0,4);}else{const w=this.canvas.width,h=this.canvas.height;this.context.drawImage(this.video,0,0,w,h,0,0,w,h);const rgb=this.context.getImageData(0,0,w,h);this.context.drawImage(this.video,w,0,w,h,0,0,w,h);const mask=this.context.getImageData(0,0,w,h);for(let i=0;i<rgb.data.length;i+=4)rgb.data[i+3]=mask.data[i]*.3+mask.data[i+1]*.59+mask.data[i+2]*.11;this.context.putImageData(rgb,0,0);}}
 schedule(token){if(token!==this.generation||this.video.paused||this.frame)return;const callback=()=>{this.frame=0;if(token!==this.generation)return;this.draw();this.schedule(token);};this.frame=this.video.requestVideoFrameCallback?this.video.requestVideoFrameCallback(callback):requestAnimationFrame(callback);}
 cancelFrame(){if(!this.frame)return;if(this.video.requestVideoFrameCallback&&this.video.cancelVideoFrameCallback)this.video.cancelVideoFrameCallback(this.frame);else cancelAnimationFrame(this.frame);this.frame=0;}
 stop(){this.generation++;this.cancelLoad?.();this.cancelFrame();this.video.pause();this.video.onended=null;this.node.classList.remove('active');this.host.classList.remove('showing-3d');}
 pause(){this.cancelFrame();this.video.pause();}
 resume(){const token=this.generation;if(this.node.classList.contains('active')&&!this.reduced)this.assets.play(this.video).then(()=>this.schedule(token)).catch(()=>{});}
 setReducedMotion(value){if(this.reduced===value)return;this.reduced=value;if(value){this.pause();this.draw();}else if(!document.hidden&&this.host.getBoundingClientRect().bottom>0&&this.host.getBoundingClientRect().top<innerHeight)this.resume();}
}
