// A query override makes the reduced-motion branch reviewable without changing browser settings.
const motionOverride=new URLSearchParams(location.search).get('motion')==='reduce';
if(motionOverride)document.documentElement.dataset.motion='reduce';
function motionReduced(){return motionOverride||matchMedia('(prefers-reduced-motion: reduce)').matches;}
const slides=[{title:'Train your Umamusume!',character:'gameplay_specialweek.CDUq1xrt.avif',alt:'Special Week official illustration',screens:['gameplay_image_1-1.PhrOaKih.avif','gameplay_image_1-2.DY13j7tt.avif'],description:'Choose a training regimen and help your Umamusume grow.'},{title:'Forge lifelong friendships!',character:'gameplay_silencesuzuka.Chw3ZKQc.avif',alt:'Silence Suzuka official illustration',screens:['gameplay_image_2-1.BcVJ7hBy.avif','gameplay_image_2-2.BKFdgH7d.avif'],description:'Meet your fellow Umamusume and spend time together at Tracen Academy.'},{title:'And to the races they go!',character:'gameplay_winningticket.BucYg9KM.avif',alt:'Winning Ticket official illustration',screens:['gameplay_image_3-1.BNkL4nTh.avif','gameplay_image_3-2.Bimj2-Ng.avif'],description:'Watch a field of up to 18 Umamusume compete on the racecourse.'}];
let index=0;const stage=document.querySelector('.gameplay-stage'),tabs=[...document.querySelectorAll('[data-slide]')],previous=document.querySelector('#previous'),nextButton=document.querySelector('#next');
const rail=document.createElement('div');rail.className='gameplay-rail';slides.forEach((s,i)=>{const panel=document.createElement('article');panel.className='gameplay-slide';panel.style.setProperty('--scene-position',(i*50)+'%');panel.innerHTML=`<h3>${s.title}</h3><div class="screens"><img src="assets/${s.screens[0]}" alt="Official gameplay screen ${i+1}.1"><img src="assets/${s.screens[1]}" alt="Official gameplay screen ${i+1}.2"></div><img class="character" src="assets/${s.character}" alt="${s.alt}"><p class="scene-caption">${s.description}</p>`;rail.append(panel);});stage.querySelectorAll('h3,.screens,.character,.scene-caption').forEach(e=>e.remove());stage.prepend(rail);const announcement=document.createElement('p');announcement.className='sr-only';announcement.setAttribute('role','status');stage.after(announcement);
function showSlide(n){index=Math.max(0,Math.min(slides.length-1,n));rail.style.transform=`translateX(${-index*100}%)`;rail.dataset.currentSlide=String(index+1);rail.querySelectorAll('.gameplay-slide').forEach((p,i)=>{p.inert=i!==index;p.setAttribute('aria-hidden',String(i!==index));});tabs.forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));previous.disabled=index===0;nextButton.disabled=index===slides.length-1;announcement.textContent=slides[index].title+' '+(index+1)+' / '+slides.length;}
tabs.forEach(b=>b.addEventListener('click',()=>showSlide(Number(b.dataset.slide))));previous.addEventListener('click',()=>showSlide(index-1));nextButton.addEventListener('click',()=>showSlide(index+1));document.querySelector('#gameplay').addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();showSlide(index+(e.key==='ArrowRight'?1:-1));}});showSlide(0);
const menu=document.querySelector('#study-menu'),menuButton=document.querySelector('#menu-button');menuButton.addEventListener('click',()=>{menu.hidden=!menu.hidden;menuButton.setAttribute('aria-expanded',String(!menu.hidden));});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.hidden=true;menuButton.setAttribute('aria-expanded','false');}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){menu.hidden=true;menuButton.setAttribute('aria-expanded','false');}});
const dialog=document.querySelector('#trailer-dialog'),trailer=document.querySelector('#trailer-video');document.querySelector('#trailer-open').addEventListener('click',()=>{dialog.showModal();trailer.currentTime=0;trailer.muted=false;trailer.play().catch(()=>{});});document.querySelector('#trailer-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>trailer.pause());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});document.addEventListener('visibilitychange',()=>{if(document.hidden)trailer.pause();});addEventListener('pagehide',()=>trailer.pause());
let sceneTouch=null;stage.addEventListener('touchstart',e=>sceneTouch=e.touches.length===1?e.touches[0].clientX:null,{passive:true});stage.addEventListener('touchend',e=>{if(sceneTouch!==null){const dx=e.changedTouches[0].clientX-sceneTouch;if(Math.abs(dx)>40)showSlide(index+(dx<0?1:-1));sceneTouch=null;}},{passive:true});

const officialHeader=document.querySelector('.official-header'),officialMenu=document.querySelector('#official-mobile-menu'),officialMenuButton=document.querySelector('.official-menu-button');function paintHeader(){officialHeader.classList.toggle('is-large',scrollY<Math.min(innerWidth,2000)*.07);}addEventListener('scroll',paintHeader,{passive:true});addEventListener('resize',paintHeader);paintHeader();function closeOfficialMenu(){officialMenu.hidden=true;officialMenuButton.setAttribute('aria-expanded','false');officialMenuButton.setAttribute('aria-label','Open official sections');officialMenuButton.querySelector('span').textContent='Menu';document.body.classList.remove('official-menu-open');}officialMenuButton.addEventListener('click',()=>{if(!officialMenu.hidden){closeOfficialMenu();return;}officialMenu.hidden=false;officialMenuButton.setAttribute('aria-expanded','true');officialMenuButton.setAttribute('aria-label','Close official sections');officialMenuButton.querySelector('span').textContent='Close';document.body.classList.add('official-menu-open');});officialMenu.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeOfficialMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeOfficialMenu();});matchMedia('(min-width:900px)').addEventListener('change',closeOfficialMenu);const downloadDialog=document.querySelector('#download-dialog');document.querySelectorAll('[data-download-open]').forEach(b=>b.addEventListener('click',()=>{closeOfficialMenu();downloadDialog.showModal();}));downloadDialog.querySelector('.download-close').addEventListener('click',()=>downloadDialog.close());downloadDialog.addEventListener('click',e=>{if(e.target===downloadDialog){const r=downloadDialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)downloadDialog.close();}});
