const panel=document.querySelector('#nav-panel');const menus={visit:[['Plan your visit','#visit-info'],['Tickets and admission','https://www.metmuseum.org/visit'],['Become a Member','#membership']],exhibitions:[['Now On View','#exhibitions'],['All exhibitions','https://www.metmuseum.org/exhibitions']],art:[['Collection Highlights','#art'],['Explore the collection','https://www.metmuseum.org/art/collection']]};let active;
const mobileToggle=document.querySelector('#mobile-menu');
function hide(){panel.hidden=true;panel.classList.remove('mobile-navigation');document.body.classList.remove('mobile-nav-open');document.querySelectorAll('[data-menu],#mobile-menu').forEach(b=>b.setAttribute('aria-expanded','false'));mobileToggle.setAttribute('aria-label','Open menu');mobileToggle.textContent='☰︎';active=null}
function destination(text,href){const a=document.createElement('a');a.textContent=text+(href.startsWith('http')?' ↗︎':'');a.href=href;if(href.startsWith('http')){a.target='_blank';a.rel='noopener'}a.onclick=hide;return a}
function menu(name,button){
 if(active===name){hide();return}hide();active=name;panel.replaceChildren();
 if(name==='mobile'){
  panel.classList.add('mobile-navigation');document.body.classList.add('mobile-nav-open');mobileToggle.textContent='×';mobileToggle.setAttribute('aria-label','Close menu');
  for(const [key,title] of [['visit','Visit'],['exhibitions','Exhibitions and Events'],['art','Art']]){const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent=title;details.append(summary);menus[key].forEach(([text,href])=>details.append(destination(text,href)));panel.append(details)}
  panel.append(destination('Learn with Us','https://www.metmuseum.org/learn'),destination('Research','https://www.metmuseum.org/research'),destination('Shop','https://store.metmuseum.org/'),destination('Tickets','https://www.metmuseum.org/visit'),destination('Membership','#membership'));
  const langs=document.createElement('div');langs.className='mobile-languages';for(const [title,code] of [['English','en'],['Español','es'],['Português','pt'],['Français','fr'],['Italiano','it'],['Deutsch','de'],['日本語','ja'],['한국어','ko'],['中文 (简体)','zh'],['Pусский','ru']])langs.append(destination(title,'https://www.metmuseum.org/'+code));panel.append(langs);
 }else menus[name].forEach(([text,href])=>panel.append(destination(text,href)));
 panel.hidden=false;button.setAttribute('aria-expanded','true');
}
document.querySelectorAll('[data-menu]').forEach(b=>b.onclick=()=>menu(b.dataset.menu,b));mobileToggle.onclick=e=>menu('mobile',e.currentTarget);document.addEventListener('keydown',e=>{if(e.key==='Escape'){hide();mobileToggle.focus()}});
document.querySelectorAll('[data-rail]').forEach(b=>b.onclick=()=>{const r=document.getElementById(b.dataset.rail);r.scrollBy({left:r.clientWidth*.9*Number(b.dataset.direction),behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'})});const exhibits={pollock:['Krasner and Pollock: Past Continuous','Through January 31, 2027','pollock.webp','https://www.metmuseum.org/exhibitions'],costume:['Costume Art','Through January 10, 2027','costume.webp','https://www.metmuseum.org/exhibitions'],orientalism:['Orientalism: Between Fact and Fantasy','Through February 28, 2027','orientalism.webp','https://www.metmuseum.org/exhibitions'],liu:['The Genesis Facade Commission: Liu Wei, Speculation','Through June 8, 2027','liu-wei.webp','https://www.metmuseum.org/exhibitions']};document.querySelectorAll('[data-exhibit]').forEach(b=>b.onclick=()=>{const d=exhibits[b.dataset.exhibit];document.querySelector('#detail-title').textContent=d[0];document.querySelector('#detail-date').textContent=d[1];document.querySelector('#detail-image').src='assets/'+d[2];document.querySelector('#detail-image').alt=d[0];document.querySelector('#detail-link').href=d[3];document.querySelector('#detail').showModal()});document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());const search=document.querySelector('#search-dialog'),input=document.querySelector('#search-input'),results=document.querySelector('#search-results');function find(){results.replaceChildren();[['Visit information','visit-info'],['Exhibitions','exhibitions'],['Collection Highlights','art'],['Membership','membership']].filter(([s])=>s.toLowerCase().includes(input.value.toLowerCase())).forEach(([t,id])=>{const a=document.createElement('a');a.textContent=t+' →';a.href='#'+id;a.onclick=()=>search.close();results.append(a)});if(!results.children.length)results.textContent='No matching section.'}document.querySelector('#search-open').onclick=()=>{search.showModal();find();input.focus()};input.oninput=find;document.querySelector('#language').onclick=()=>document.querySelector('#language-dialog').showModal();
