const menu=document.querySelector('#menu'),toggle=document.querySelector('#menu-toggle');function closeMenu(){menu.hidden=true;toggle.setAttribute('aria-expanded','false')}toggle.onclick=()=>{menu.hidden=!menu.hidden;toggle.setAttribute('aria-expanded',!menu.hidden)};menu.querySelectorAll('a').forEach(a=>a.onclick=closeMenu);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});document.querySelector('#back-top').onclick=()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});
// The three photographs and 500ms track are observed; the 6s cycle is a local approximation.
const concert=document.querySelector('.concert-photo'),concertTrack=document.querySelector('.concert-track');
const concertReduce=matchMedia('(prefers-reduced-motion: reduce)');let concertIndex=0,concertPaused=concertReduce.matches,concertInside=false,concertVisible=false;
const concertPause=document.querySelector('#concert-pause');
function concertShow(delta){concertIndex=(concertIndex+delta+3)%3;concertTrack.style.transform='translateX('+(-100*concertIndex)+'%)';document.querySelector('#concert-position').textContent=(concertIndex+1)+' / 3'}
function concertPauseState(){concertPause.setAttribute('aria-pressed',String(concertPaused));concertPause.setAttribute('aria-label',concertPaused?'Lecture des photographies':'Pause des photographies');concertPause.textContent=concertPaused?'▶':'Ⅱ'}
document.querySelector('#concert-prev').onclick=()=>concertShow(-1);document.querySelector('#concert-next').onclick=()=>concertShow(1);concertPause.onclick=()=>{concertPaused=!concertPaused;concertPauseState()};
concert.addEventListener('pointerenter',()=>concertInside=true);concert.addEventListener('pointerleave',()=>concertInside=false);concert.addEventListener('focusin',()=>concertInside=true);concert.addEventListener('focusout',()=>concertInside=false);
let concertStart=null;concert.addEventListener('touchstart',e=>{concertStart=e.touches[0].clientX},{passive:true});concert.addEventListener('touchend',e=>{if(concertStart===null)return;const dx=e.changedTouches[0].clientX-concertStart;if(Math.abs(dx)>40)concertShow(dx<0?1:-1);concertStart=null},{passive:true});
new IntersectionObserver(es=>concertVisible=es[0].isIntersecting,{threshold:.15}).observe(concert);
const concertTimer=setInterval(()=>{if(concertVisible&&!concertPaused&&!concertInside&&!document.hidden)concertShow(1)},6000);
concertReduce.addEventListener('change',()=>{if(concertReduce.matches){concertPaused=true;concertPauseState()}});window.addEventListener('pagehide',()=>clearInterval(concertTimer),{once:true});concertPauseState();
