// A query override makes the reduced-motion branch reviewable without changing browser settings.
const motionOverride=new URLSearchParams(location.search).get('motion')==='reduce';
if(motionOverride)document.documentElement.dataset.motion='reduce';
function motionReduced(){return motionOverride||matchMedia('(prefers-reduced-motion: reduce)').matches;}
let heroVisible=true;
const hero=document.querySelector('#hero-video'),bgButton=document.querySelector('#background-toggle'),reduce=matchMedia('(prefers-reduced-motion: reduce)');
function updateBackground(){bgButton.setAttribute('aria-pressed',String(!hero.paused));bgButton.textContent=hero.paused?'▶ Background motion':'Ⅱ Pause background';}hero.addEventListener('loadedmetadata',()=>{hero.currentTime=Math.min(.1,hero.duration||.1);if(!motionReduced()&&heroVisible&&!document.hidden)hero.play().catch(updateBackground);});['play','pause','ended'].forEach(e=>hero.addEventListener(e,updateBackground));bgButton.addEventListener('click',async()=>{if(hero.paused){try{await hero.play();}catch{bgButton.textContent='Try background playback again';}}else hero.pause();});reduce.addEventListener('change',()=>{if(reduce.matches)hero.pause();});
const trailer=document.querySelector('#trailer-video'),start=document.querySelector('#trailer-start'),sound=document.querySelector('#trailer-sound'),status=document.querySelector('#playback-state');trailer.muted=true;
function updateTrailer(){const playing=!trailer.paused&&!trailer.ended;start.hidden=playing;document.querySelector('#trailer-label').textContent=trailer.currentTime>0?'RESUME TRAILER':'PLAY TRAILER';sound.setAttribute('aria-pressed',String(!trailer.muted));sound.textContent=trailer.muted?'Sound off':'Sound on';status.textContent=(playing?'Trailer playing':'Trailer paused')+' · '+(trailer.muted?'audio off':'audio on');}
start.addEventListener('click',async()=>{hero.pause();trailer.muted=false;try{await trailer.play();}catch{status.textContent='Playback unavailable. Try the video controls.';}});sound.addEventListener('click',()=>{trailer.muted=!trailer.muted;updateTrailer();});['play','pause','ended','volumechange'].forEach(e=>trailer.addEventListener(e,updateTrailer));
const menu=document.querySelector('.game-nav'),menuButton=document.querySelector('#menu-toggle');function closeMenu(){menu.classList.remove('open');menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label','Open game navigation');}menuButton.addEventListener('click',()=>{const open=menu.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Close game navigation':'Open game navigation');});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
document.querySelector('#award-toggle').addEventListener('click',e=>{const expanded=e.currentTarget.getAttribute('aria-expanded')!=='true';document.querySelectorAll('.more-award').forEach(a=>a.hidden=!expanded);e.currentTarget.setAttribute('aria-expanded',String(expanded));e.currentTarget.textContent=expanded?'Show fewer awards ⌃':'Show more awards ⌄';});
const images=['4-8f27e7fa.jpg','5-ecebe13c.jpg','6-d85fcf35.jpg','3-6cd6eb91.jpg'];let current=0;const galleryImage=document.querySelector('#gallery-image'),galleryWindow=document.createElement('div'),galleryTrack=document.createElement('div');galleryWindow.className='gallery-window';galleryTrack.className='gallery-track';images.forEach((file,i)=>{const figure=document.createElement('figure'),img=document.createElement('img');img.src='assets/'+file;img.alt='Official Monument Valley screenshot '+(i+1);figure.append(img);galleryTrack.append(figure);});galleryWindow.append(galleryTrack);galleryImage.replaceWith(galleryWindow);
function showImage(next){current=(next+images.length)%images.length;galleryTrack.style.transform=`translateX(${-current*100}%)`;galleryTrack.dataset.image=String(current+1);[...galleryTrack.children].forEach((f,i)=>{f.inert=i!==current;f.setAttribute('aria-hidden',String(i!==current));});document.querySelector('#gallery-caption').textContent=String(current+1).padStart(2,'0')+' / 04 — Original game image';document.querySelectorAll('[data-gallery]').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===current)));}document.querySelector('#gallery-next').addEventListener('click',()=>showImage(current+1));document.querySelector('#gallery-previous').addEventListener('click',()=>showImage(current-1));document.querySelectorAll('[data-gallery]').forEach(b=>b.addEventListener('click',()=>showImage(Number(b.dataset.gallery))));document.querySelector('.gallery-stage').addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();showImage(current+(e.key==='ArrowRight'?1:-1));}});showImage(0);
const sectionLinks=[...document.querySelectorAll('.section-nav a')];const observer=new IntersectionObserver(items=>{for(const item of items){if(item.isIntersecting)sectionLinks.forEach(a=>a.classList.toggle('current',a.hash==='#'+item.target.id));}},{rootMargin:'-20% 0px -55% 0px'});sectionLinks.forEach(a=>observer.observe(document.querySelector(a.hash)));

new IntersectionObserver(es=>{heroVisible=es[0].intersectionRatio>=.15;if(!heroVisible)hero.pause();},{threshold:.15}).observe(document.querySelector('#home'));document.addEventListener('visibilitychange',()=>{if(document.hidden){hero.pause();trailer.pause();}});
