function atlasImage(url){return window.AtlasAssets?window.AtlasAssets.attach(new Image(),url):Object.assign(new Image(),{src:url});}
// Current MV1 mechanisms; explicit pause/reduced-motion controls are local study aids.
const reduced=matchMedia('(prefers-reduced-motion:reduce)'),phone=matchMedia('(max-width:699px)'),override=new URLSearchParams(location.search).get('motion')==='reduce';
if(override)document.documentElement.dataset.motion='reduce';
const quiet=()=>override||reduced.matches,main=document.querySelector('main');main.inert=true;let entryReady=false;
setTimeout(()=>{document.querySelector('#loading-screen').hidden=true;main.inert=false;document.body.classList.remove('loading');document.body.dataset.entry='ready';entryReady=true;background();},1000);
const hero=document.querySelector('#hero-video'),bgButton=document.querySelector('#background-toggle'),trailer=document.querySelector('#trailer-video'),start=document.querySelector('#trailer-start'),sound=document.querySelector('#trailer-sound'),status=document.querySelector('#playback-state');
let heroVisible=true,bgRequested=!quiet();
function background(){if(entryReady&&bgRequested&&heroVisible&&!document.hidden&&trailer.paused)hero.play().catch(bgState);else hero.pause();}
function bgState(){bgButton.setAttribute('aria-pressed',String(!hero.paused));bgButton.textContent=hero.paused?'▶ Background motion':'Ⅱ Pause background';}
hero.addEventListener('loadedmetadata',background);['play','pause','ended'].forEach(e=>hero.addEventListener(e,bgState));bgButton.onclick=()=>{bgRequested=hero.paused;background();};
new IntersectionObserver(rows=>{heroVisible=rows[0].intersectionRatio>=.15;background();},{threshold:.15}).observe(document.querySelector('#home'));
trailer.muted=false;
function trailerState(){const playing=!trailer.paused&&!trailer.ended;start.hidden=playing;document.querySelector('#trailer-label').textContent=trailer.currentTime>0?'RESUME TRAILER':'PLAY TRAILER';sound.setAttribute('aria-pressed',String(!trailer.muted));sound.textContent=trailer.muted?'Sound off':'Sound on';status.textContent=(playing?'Trailer playing':'Trailer paused')+' · '+(trailer.muted?'audio off':playing?'original audio on':'original audio ready');background();}
start.onclick=async()=>{try{await trailer.play();}catch{status.textContent='Playback unavailable. Try the video controls.';}};sound.onclick=()=>{trailer.muted=!trailer.muted;trailerState();};['play','pause','ended','volumechange'].forEach(e=>trailer.addEventListener(e,trailerState));trailerState();
const menu=document.querySelector('.game-nav'),menuButton=document.querySelector('#menu-toggle'),series=document.querySelector('#series-links');
function menuState(){const open=menu.classList.contains('open');series.inert=phone.matches&&!open;series.setAttribute('aria-hidden',String(phone.matches&&!open));menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Close game navigation':'Open game navigation');document.body.style.overflow=phone.matches&&open?'hidden':'';}
function closeMenu(){menu.classList.remove('open');menuState();}
menuButton.onclick=()=>{menu.classList.toggle('open');menuState();};menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});phone.addEventListener('change',closeMenu);menuState();
// The reference activates a chapter when the viewport centre is inside its bounds.
const nav=document.querySelector('.section-nav'),links=[...nav.querySelectorAll('a')],sections=[...document.querySelectorAll('main>section')],awards=document.querySelector('#awards');let scrollFrame=0,navFrame=0;
function updateSections(){scrollFrame=0;const active=sections.find(s=>{const r=s.getBoundingClientRect();return r.top<=innerHeight/2&&r.bottom>=innerHeight/2;});sections.forEach(s=>s.classList.toggle('active-section',s===active));awards.classList.toggle('awards-active',active===awards||quiet());links.forEach(a=>{const on=a.hash==='#'+active?.id;a.classList.toggle('current',on);if(on)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});nav.classList.toggle('visible',active?.id!=='home');nav.inert=active?.id==='home';}
function requestSections(){if(!scrollFrame)scrollFrame=requestAnimationFrame(updateSections);}
function stopNavigation(){cancelAnimationFrame(navFrame);}
function centre(s){stopNavigation();const from=scrollY,r=s.getBoundingClientRect(),to=Math.max(0,Math.min(document.documentElement.scrollHeight-innerHeight,from+r.top+r.height/2-innerHeight/2));if(quiet()){scrollTo(0,to);return;}const began=performance.now();function frame(now){const t=Math.min(1,(now-began)/450);scrollTo(0,from+(to-from)*(1-Math.cos(Math.PI*t))/2);if(t<1)navFrame=requestAnimationFrame(frame);}navFrame=requestAnimationFrame(frame);}
[...links,document.querySelector('.down-arrow')].forEach(a=>a.onclick=e=>{e.preventDefault();centre(document.querySelector(a.hash));});addEventListener('scroll',requestSections,{passive:true});addEventListener('resize',requestSections);addEventListener('wheel',stopNavigation,{passive:true});addEventListener('touchstart',stopNavigation,{passive:true});
nav.addEventListener('pointerenter',()=>document.body.classList.add('nav-preview'));nav.addEventListener('pointerleave',()=>document.body.classList.remove('nav-preview'));nav.addEventListener('focusin',()=>document.body.classList.add('nav-preview'));nav.addEventListener('focusout',e=>{if(!nav.contains(e.relatedTarget))document.body.classList.remove('nav-preview');});updateSections();
const awardWrap=document.querySelector('.awards-expand'),first=document.querySelector('.awards-first'),rest=document.querySelector('.awards-rest'),awardButton=document.querySelector('#award-toggle');let expanded=false;
function sizeAwards(){awardWrap.style.height=phone.matches?(first.offsetHeight+(expanded?rest.offsetHeight:0))+'px':'';rest.inert=phone.matches&&!expanded;rest.setAttribute('aria-hidden',String(phone.matches&&!expanded));awardButton.setAttribute('aria-expanded',String(expanded));awardButton.querySelector('span').textContent=expanded?'Hide':'Show All';requestSections();}
awardButton.onclick=()=>{expanded=!expanded;sizeAwards();};addEventListener('resize',sizeAwards);phone.addEventListener('change',sizeAwards);document.fonts.ready.then(sizeAwards);sizeAwards();
const files=['3-6cd6eb91.jpg','4-8f27e7fa.jpg','5-ecebe13c.jpg','6-d85fcf35.jpg','7-802e623e.jpg','8-513af37d.jpg','9-69d2baed.jpg','10-b44ce70c.jpg','11-bc582657.jpg','12-c9d7501d.jpg','13-981028d4.jpg','15-56207bdd.jpg','16-89042586.jpg','17-9f2e87bd.jpg'];
const gallery=document.querySelector('.gallery'),windowEl=document.querySelector('.gallery-window'),track=document.querySelector('.gallery-track'),dots=document.querySelector('.gallery-dots'),pause=document.querySelector('#gallery-pause'),caption=document.querySelector('#gallery-caption');
let current=0,prefix=4,slideWidth=0,renderIndex=4,busy=false,pending=null,transitionTimer,timer,visible=false,hovered=false,focused=false,paused=false;const mod=n=>(n%files.length+files.length)%files.length;
function schedule(){clearTimeout(timer);if(visible&&!hovered&&!focused&&!paused&&!quiet()&&!document.hidden&&!busy)timer=setTimeout(()=>select(current+1),3000);}
function position(animate){track.style.transition=animate&&!quiet()?'transform 500ms ease':'none';track.style.transform='translate3d('+(-(renderIndex*slideWidth-(windowEl.clientWidth-slideWidth)/2))+'px,0,0)';}
function highlight(){[...track.children].forEach(f=>{const i=+f.dataset.index,on=i===current;f.classList.toggle('selected',on);if(!f.dataset.clone){const shown=on||(!phone.matches&&(i===mod(current-1)||i===mod(current+1)));f.inert=!shown;f.setAttribute('aria-hidden',String(!shown));f.tabIndex=on?0:-1;}});[...dots.children].forEach((d,i)=>d.setAttribute('aria-pressed',String(i===current)));caption.textContent=String(current+1).padStart(2,'0')+' / 14 — Original game image';track.dataset.image=String(current+1);}
function finish(){clearTimeout(transitionTimer);busy=false;renderIndex=prefix+current;position(false);if(pending!==null){const n=pending;pending=null;select(n);}else schedule();}
function select(index){const n=mod(index);if(busy){pending=n;return;}if(n===current)return;clearTimeout(timer);renderIndex=prefix+(current===13&&n===0?14:current===0&&n===13?-1:n);current=n;highlight();busy=!quiet();position(busy);if(busy)transitionTimer=setTimeout(finish,520);else finish();}
function build(){clearTimeout(transitionTimer);busy=false;pending=null;prefix=phone.matches?2:4;const figures=[];for(let i=-prefix;i<14+prefix;i++){const index=mod(i),clone=i<0||i>=14,f=document.createElement('figure');f.className='gallery-slide';f.dataset.index=index;if(clone){f.dataset.clone='true';f.inert=true;f.setAttribute('aria-hidden','true');}else{f.setAttribute('role','button');f.setAttribute('aria-label','View screenshot '+(index+1));f.onclick=()=>select(index);f.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(index);}};}const img=atlasImage('assets/'+files[index]);img.alt=clone?'':'Official Monument Valley screenshot '+(index+1);img.width=900;img.height=1454;img.draggable=false;f.append(img);figures.push(f);}track.replaceChildren(...figures);slideWidth=windowEl.clientWidth*(phone.matches?.6:1/3);track.style.setProperty('--slide-width',slideWidth+'px');renderIndex=prefix+current;highlight();position(false);schedule();}
files.forEach((_,i)=>{const b=document.createElement('button');b.dataset.gallery=i;b.setAttribute('aria-label','Screenshot '+(i+1));b.setAttribute('aria-pressed',String(i===0));b.textContent='●';b.onclick=()=>select(i);dots.append(b);});
document.querySelector('#gallery-next').onclick=()=>select((pending??current)+1);document.querySelector('#gallery-previous').onclick=()=>select((pending??current)-1);gallery.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();select(e.key==='Home'?0:e.key==='End'?13:(pending??current)+(e.key==='ArrowRight'?1:-1));});
gallery.addEventListener('pointerenter',()=>{hovered=true;schedule();});gallery.addEventListener('pointerleave',()=>{hovered=false;schedule();});gallery.addEventListener('focusin',()=>{focused=true;schedule();});gallery.addEventListener('focusout',e=>{focused=gallery.contains(e.relatedTarget);schedule();});let touchX=null;windowEl.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')touchX=e.clientX;});windowEl.addEventListener('pointerup',e=>{if(touchX!==null&&Math.abs(e.clientX-touchX)>40)select(current+(e.clientX<touchX?1:-1));touchX=null;});windowEl.addEventListener('pointercancel',()=>touchX=null);
pause.onclick=()=>{paused=!paused;pause.setAttribute('aria-pressed',String(paused));pause.textContent=paused?'▶ Resume gallery':'Ⅱ Pause gallery';schedule();};new IntersectionObserver(rows=>{visible=rows[0].intersectionRatio>=.15;schedule();},{threshold:.15}).observe(gallery);addEventListener('resize',build);phone.addEventListener('change',build);
document.addEventListener('visibilitychange',()=>{if(document.hidden)trailer.pause();background();schedule();});reduced.addEventListener('change',()=>{if(quiet()){bgRequested=false;finish();}background();schedule();requestSections();});build();addEventListener('pagehide',()=>{clearTimeout(timer);clearTimeout(transitionTimer);stopNavigation();hero.pause();trailer.pause();});
