// A query override makes the reduced-motion branch reviewable without changing browser settings.
const motionOverride=new URLSearchParams(location.search).get('motion')==='reduce';
if(motionOverride)document.documentElement.dataset.motion='reduce';
function motionReduced(){return motionOverride||matchMedia('(prefers-reduced-motion: reduce)').matches;}
const video=document.querySelector('#keyart-video'),toggle=document.querySelector('#video-toggle'),status=document.querySelector('#media-status');let paused=motionReduced(),heroVisible=true;
function motion(){if(paused||document.hidden||!heroVisible)video.pause();else video.play().catch(()=>{paused=true;toggle.textContent='▶︎';toggle.setAttribute('aria-label','播放首屏动态画面');status.textContent='自动画面播放被阻止，请点击播放按钮'});toggle.textContent=paused?'▶︎':'Ⅱ';toggle.setAttribute('aria-pressed',String(paused));toggle.setAttribute('aria-label',paused?'播放首屏动态画面':'暂停首屏动态画面')}motion();toggle.addEventListener('click',()=>{paused=!paused;motion()});document.addEventListener('visibilitychange',motion);
const voiceButton=document.querySelector('#character-voice');let activeVoice=null;function stopCharacterVoice(){if(activeVoice){if(window.AtlasAssets)window.AtlasAssets.pause(activeVoice);else activeVoice.pause();}voiceButton.setAttribute('aria-pressed','false');voiceButton.setAttribute('aria-label','播放当前角色原始语音');}
voiceButton.addEventListener('click',()=>{if(activeVoice&&!activeVoice.paused){stopCharacterVoice();return;}const voiceURL='assets/voice-'+(current+1)+'-'+(Math.floor(Math.random()*3)+1)+'.mp3';activeVoice=window.AtlasAssets?window.AtlasAssets.attach(new Audio(),voiceURL):new Audio(voiceURL);activeVoice.addEventListener('ended',stopCharacterVoice);(window.AtlasAssets?window.AtlasAssets.play(activeVoice):activeVoice.play()).then(()=>{voiceButton.setAttribute('aria-pressed','true');voiceButton.setAttribute('aria-label','暂停角色原始语音');}).catch(()=>{status.textContent='语音未能播放，请再次点击麦克风';});});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopCharacterVoice();});addEventListener('pagehide',stopCharacterVoice);
const data=[{name:'Vesna',description:"Commander of the Druzhna and the Tsaritsa's keen blade.",art:'character-1.webp'},{name:'Vodyanitsa',description:'Prima Donna of the Korolevskiy Troupe, a Water Imp who has parted from her kin.',art:'character-2.webp'}];let current=0;const pickers=[...document.querySelectorAll('[data-character]')];function render(animate=false){if(animate&&!motionReduced()){const old=document.querySelector('#character-art').cloneNode(true);old.removeAttribute('id');old.classList.add('motion-ghost');old.setAttribute('aria-hidden','true');document.querySelector('#character-art').after(old);old.animate([{opacity:1},{opacity:0}],{duration:100}).onfinish=()=>old.remove();document.querySelector('#character-art').animate([{opacity:0},{opacity:1}],{duration:100});document.querySelector('.character-stage').dataset.transition='opacity-100';setTimeout(()=>document.querySelector('.character-stage').dataset.transition='idle',100);}let c=data[current];document.querySelector('#name').textContent=c.name;document.querySelector('#description').textContent=c.description;document.querySelector('#character-art').src='assets/'+c.art;document.querySelector('#character-art').alt=c.name+'官方立绘';document.querySelector('.character-stage').style.backgroundImage='url(assets/character-background'+(current?'-2':'')+'.webp)';document.querySelector('#character-voice img').src='assets/microphone-'+(current+1)+'.webp';stopCharacterVoice();pickers.forEach((p,i)=>p.setAttribute('aria-pressed',String(i===current)));document.querySelector('#dialog-name').textContent=c.name;document.querySelector('#dialog-description').textContent=c.description}
pickers.forEach((b,i)=>{b.addEventListener('click',()=>{current=i;render(true)});b.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();current=1-current;render(true);pickers[current].focus()}})});const detail=document.querySelector('#detail-dialog'),calendar=document.querySelector('#calendar-dialog');document.querySelector('#details').addEventListener('click',()=>{render();detail.showModal()});document.querySelector('#calendar-open').addEventListener('click',()=>calendar.showModal());document.querySelectorAll('dialog .close').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));[detail,calendar].forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));

new IntersectionObserver(es=>{heroVisible=es[0].intersectionRatio>=.2;motion();},{threshold:.2}).observe(document.querySelector('#home'));matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',()=>{if(motionReduced())paused=true;motion();});

// Local full-page state preserves the source's translated scene journey, with explicit timing approximation.
const pageTrack=document.querySelector('main'),pagePanels=[...pageTrack.children];pagePanels.forEach((p,i)=>p.dataset.chapter=String(i));let page=0,locked=false,pendingPage=null,pageTimer;
function paintPage(instant=false){const requested=pagePanels[page].offsetTop,max=pageTrack.scrollHeight-innerHeight,offset=Math.min(requested,Math.max(0,max));pageTrack.style.transition=instant||motionReduced()?'none':'transform 600ms ease';pageTrack.style.transform='translate3d(0,'+(-offset)+'px,0)';document.body.dataset.chapter=String(page);pagePanels.forEach(p=>{const visible=p.offsetTop+p.offsetHeight>offset&&p.offsetTop<offset+innerHeight;p.inert=!visible;p.setAttribute('aria-hidden',String(!visible));});heroVisible=page===0;motion();if(page!==1)stopCharacterVoice();}
function goPage(n){n=Math.max(0,Math.min(pagePanels.length-1,n));if(locked){pendingPage=n;return;}if(n===page)return;page=n;locked=!motionReduced();paintPage();clearTimeout(pageTimer);pageTimer=setTimeout(()=>{locked=false;pageTrack.style.transition='none';if(pendingPage!==null){const next=pendingPage;pendingPage=null;goPage(next);}},motionReduced()?0:650);}
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const target=document.querySelector(a.hash);if(!target)return;const i=pagePanels.indexOf(target);if(i>=0){e.preventDefault();goPage(i);}}));
function dialogOpen(){return !!document.querySelector('dialog[open]');}
addEventListener('wheel',e=>{if(dialogOpen()||Math.abs(e.deltaY)<20)return;const panel=e.target.closest('[data-chapter]');if(panel&&['auto','scroll'].includes(getComputedStyle(panel).overflowY)&&panel.scrollHeight>panel.clientHeight+2&&((e.deltaY>0&&panel.scrollTop+panel.clientHeight<panel.scrollHeight-2)||(e.deltaY<0&&panel.scrollTop>0)))return;e.preventDefault();if(!locked)goPage(page+(e.deltaY>0?1:-1));},{passive:false});
addEventListener('keydown',e=>{if(dialogOpen()||e.target.closest('button,a,input'))return;if(['ArrowDown','ArrowUp','PageDown','PageUp','Home','End'].includes(e.key)){e.preventDefault();goPage(e.key==='Home'?0:e.key==='End'?pagePanels.length-1:page+(['ArrowDown','PageDown'].includes(e.key)?1:-1));}});
let pageTouch=null;addEventListener('touchstart',e=>{pageTouch=e.touches.length===1?[e.touches[0].clientX,e.touches[0].clientY]:null;},{passive:true});addEventListener('touchend',e=>{if(!pageTouch||dialogOpen())return;const dx=e.changedTouches[0].clientX-pageTouch[0],dy=e.changedTouches[0].clientY-pageTouch[1];if(Math.abs(dy)>40&&Math.abs(dy)>Math.abs(dx))goPage(page+(dy<0?1:-1));pageTouch=null;},{passive:true});addEventListener('resize',()=>paintPage(true));paintPage(true);
