// A query override makes the reduced-motion branch reviewable without changing browser settings.
const motionOverride=new URLSearchParams(location.search).get('motion')==='reduce';
if(motionOverride)document.documentElement.dataset.motion='reduce';
function motionReduced(){return motionOverride||matchMedia('(prefers-reduced-motion: reduce)').matches;}
const video=document.querySelector('#keyart-video'),toggle=document.querySelector('#video-toggle'),status=document.querySelector('#media-status');let paused=motionReduced(),heroVisible=true;
function motion(){if(paused||document.hidden||!heroVisible)video.pause();else video.play().catch(()=>{paused=true;toggle.textContent='▶';toggle.setAttribute('aria-label','播放首屏动态画面');status.textContent='自动画面播放被阻止，请点击播放按钮'});toggle.textContent=paused?'▶':'Ⅱ';toggle.setAttribute('aria-pressed',String(paused));toggle.setAttribute('aria-label',paused?'播放首屏动态画面':'暂停首屏动态画面')}motion();toggle.addEventListener('click',()=>{paused=!paused;motion()});document.addEventListener('visibilitychange',motion);
const data=[{name:'Vesna',description:"Commander of the Druzhna and the Tsaritsa's keen blade.",art:'character-1.webp'},{name:'官方第二角色',description:'Prima Donna of the Korolevskiy Troupe, a Water Imp who has parted from her kin.',art:'character-2.webp'}];let current=0;const pickers=[...document.querySelectorAll('[data-character]')];function render(animate=false){if(animate&&!motionReduced()){const old=document.querySelector('#character-art').cloneNode(true);old.removeAttribute('id');old.classList.add('motion-ghost');old.setAttribute('aria-hidden','true');document.querySelector('#character-art').after(old);old.animate([{opacity:1},{opacity:0}],{duration:100}).onfinish=()=>old.remove();document.querySelector('#character-art').animate([{opacity:0},{opacity:1}],{duration:100});document.querySelector('.character-stage').dataset.transition='opacity-100';setTimeout(()=>document.querySelector('.character-stage').dataset.transition='idle',100);}let c=data[current];document.querySelector('#name').textContent=c.name;document.querySelector('#description').textContent=c.description;document.querySelector('#character-art').src='assets/'+c.art;document.querySelector('#character-art').alt=c.name+'官方立绘';document.querySelector('#preview-art').src='assets/'+c.art;pickers.forEach((p,i)=>p.setAttribute('aria-pressed',String(i===current)));document.querySelector('#dialog-name').textContent=c.name;document.querySelector('#dialog-description').textContent=c.description}
pickers.forEach((b,i)=>{b.addEventListener('click',()=>{current=i;render(true)});b.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();current=1-current;render(true);pickers[current].focus()}})});const detail=document.querySelector('#detail-dialog'),calendar=document.querySelector('#calendar-dialog');document.querySelector('#details').addEventListener('click',()=>{render();detail.showModal()});document.querySelector('#calendar-open').addEventListener('click',()=>calendar.showModal());document.querySelectorAll('dialog .close').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));[detail,calendar].forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));

new IntersectionObserver(es=>{heroVisible=es[0].intersectionRatio>=.2;motion();},{threshold:.2}).observe(document.querySelector('#home'));matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',()=>{if(motionReduced())paused=true;motion();});
