// A query override makes the reduced-motion branch reviewable without changing browser settings.
const motionOverride=new URLSearchParams(location.search).get('motion')==='reduce';
if(motionOverride)document.documentElement.dataset.motion='reduce';
function motionReduced(){return motionOverride||matchMedia('(prefers-reduced-motion: reduce)').matches;}
const scenes=[...document.querySelectorAll('.world')],videos=scenes.map(s=>s.querySelector('video')),chapters=[...document.querySelectorAll('.chapters a')],stage=document.querySelector('.world-stage');
const audio=document.querySelector('#bgm'),sound=document.querySelector('#sound'),motion=document.querySelector('#motion'),status=document.querySelector('#media-status'),gate=document.querySelector('#entry-gate');let current=0,paused=motionReduced(),stageVisible=true,changeToken=0,entered=false,idleTimer,sceneLock=false,pendingScene=null;
function videoState(){videos.forEach((v,i)=>{if(i!==current||paused||!entered||document.hidden||!stageVisible)v.pause();else v.play().catch(()=>{paused=true;motion.textContent='▶︎ 播放画面';status.textContent='点击播放画面开始静音影片';});});motion.textContent=paused?'▶︎ 播放画面':'Ⅱ 暂停画面';motion.setAttribute('aria-pressed',String(paused));}
function wakeUI(){clearTimeout(idleTimer);document.body.classList.remove('ui-idle');if(entered&&!motionReduced()&&!document.activeElement.closest('header,.main-nav,.chapters'))idleTimer=setTimeout(()=>document.body.classList.add('ui-idle'),3000);}
async function selectScene(index,{hash=true,restart=true}={}){index=(index+scenes.length)%scenes.length;if(sceneLock){pendingScene=index;return;}sceneLock=true;await window.CaseLoading?.prepare(scenes[index],{hint:true});sceneLock=!motionReduced();current=index;scenes.forEach((s,i)=>{const active=i===current;s.classList.toggle('active',active);s.inert=!active;s.setAttribute('aria-hidden',String(!active));});chapters.forEach((a,i)=>{if(i===current)a.setAttribute('aria-current','true');else a.removeAttribute('aria-current');});if(restart)videos[current].currentTime=0;if(hash)history.replaceState(null,'','#world-'+(current+1));stage.dataset.scene=String(current+1);stage.dataset.transition=motionReduced()?'instant':'blur-dark';const token=++changeToken;setTimeout(()=>{if(token!==changeToken)return;sceneLock=false;if(pendingScene!==null){const next=pendingScene;pendingScene=null;selectScene(next);}else stage.dataset.transition='idle';},motionReduced()?0:300);videoState();wakeUI();}
document.querySelectorAll('a[href^="#world-"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const i=Number(a.hash.split('-').pop())-1;selectScene(i);if(a.classList.contains('skip'))stage.focus();}));
stage.addEventListener('keydown',e=>{if(e.target.closest('button,a,input'))return;if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();selectScene(e.key==='Home'?0:e.key==='End'?2:current+(e.key==='ArrowRight'?1:-1));}});
chapters.forEach((a,i)=>a.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();selectScene(i+(e.key==='ArrowRight'?1:-1));chapters[current].focus();}}));
let touchStart=null;stage.addEventListener('touchstart',e=>{touchStart=e.touches.length===1?[e.touches[0].clientX,e.touches[0].clientY]:null;},{passive:true});stage.addEventListener('touchend',e=>{if(!touchStart)return;const dx=e.changedTouches[0].clientX-touchStart[0],dy=e.changedTouches[0].clientY-touchStart[1];if(Math.abs(dx)>10&&Math.abs(dx)>Math.abs(dy))selectScene(Math.max(0,Math.min(2,current+(dx<0?1:-1))));touchStart=null;},{passive:true});
videos.forEach((v,i)=>v.addEventListener('timeupdate',()=>{if(i===current&&entered&&!paused&&!motionReduced()&&v.duration-v.currentTime<1)selectScene(current+1);}));
motion.addEventListener('click',()=>{paused=!paused;videoState();});sound.addEventListener('click',async()=>{if(!audio.paused){audio.pause();return;}try{await audio.play();status.textContent='官网原始 BGM · 未公开曲名';}catch{status.textContent='音频无法播放，请再次点击 SOUND';}});function audioState(){sound.setAttribute('aria-pressed',String(!audio.paused));sound.textContent=audio.paused?'♫ SOUND OFF':'♫ SOUND ON';}['play','pause'].forEach(e=>audio.addEventListener(e,audioState));
new IntersectionObserver(es=>{stageVisible=es[0].intersectionRatio>=.25;videoState();},{threshold:.25}).observe(stage);document.addEventListener('visibilitychange',()=>{if(document.hidden)audio.pause();videoState();});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',()=>{if(motionReduced())paused=true;videoState();});
const initial=Number(location.hash.split('-').pop())-1;selectScene(initial>=0&&initial<3?initial:0,{hash:false,restart:false});
stage.inert=true;
function finishEntry(){gate.classList.add('leaving');entered=true;stage.inert=false;document.body.classList.remove('awaiting-entry');videoState();wakeUI();setTimeout(()=>{gate.hidden=true;gate.inert=true;stage.focus({preventScroll:true});},motionReduced()?0:800);}
function enter(on){if(gate.dataset.phase)return;gate.dataset.phase='emblem';gate.querySelector('.sound-choice').inert=true;sessionStorage.setItem('zelda-study-entry','seen');if(on){document.querySelector('#emblem-se').play().catch(()=>{});audio.volume=0;audio.play().catch(()=>{status.textContent='点击 SOUND 开启原站音乐';});setTimeout(()=>{audio.volume=1;},motionReduced()?0:3400);}if(motionReduced()){finishEntry();return;}setTimeout(()=>gate.classList.add('pulse'),2000);setTimeout(finishEntry,3600);}
document.querySelectorAll('[data-enter]').forEach(b=>b.onclick=()=>enter(b.dataset.enter==='on'));
document.addEventListener('pointermove',wakeUI,{passive:true});document.addEventListener('focusin',wakeUI);document.addEventListener('touchstart',wakeUI,{passive:true});
if(sessionStorage.getItem('zelda-study-entry')==='seen'){gate.hidden=true;entered=true;stage.inert=false;document.body.classList.remove('awaiting-entry');videoState();wakeUI();}else gate.querySelector('[data-enter="off"]').focus({preventScroll:true});
window.addEventListener('pagehide',()=>{audio.pause();document.querySelector('#emblem-se').pause();videos.forEach(v=>v.pause());clearTimeout(idleTimer);});
