// A query override makes the reduced-motion branch reviewable without changing browser settings.
const motionOverride=new URLSearchParams(location.search).get('motion')==='reduce';
if(motionOverride)document.documentElement.dataset.motion='reduce';
function motionReduced(){return motionOverride||matchMedia('(prefers-reduced-motion: reduce)').matches;}
const scenes=[...document.querySelectorAll('.world')],videos=scenes.map(s=>s.querySelector('video')),chapters=[...document.querySelectorAll('.chapters a')],stage=document.querySelector('.world-stage');
const audio=document.querySelector('#bgm'),sound=document.querySelector('#sound'),motion=document.querySelector('#motion'),status=document.querySelector('#media-status');let current=0,paused=motionReduced(),stageVisible=true,changeToken=0;
function videoState(){videos.forEach((v,i)=>{if(i!==current||paused||document.hidden||!stageVisible)v.pause();else v.play().catch(()=>{paused=true;videoState();status.textContent='画面播放被阻止，请点击播放画面';});});motion.textContent=paused?'▶ 播放画面':'Ⅱ 暂停画面';motion.setAttribute('aria-pressed',String(paused));}
function selectScene(index,{hash=true,restart=true}={}){current=(index+scenes.length)%scenes.length;scenes.forEach((s,i)=>{const active=i===current;s.classList.toggle('active',active);s.inert=!active;s.setAttribute('aria-hidden',String(!active));});chapters.forEach((a,i)=>{if(i===current)a.setAttribute('aria-current','true');else a.removeAttribute('aria-current');});if(restart)videos[current].currentTime=0;if(hash)history.replaceState(null,'','#world-'+(current+1));stage.dataset.scene=String(current+1);stage.dataset.transition=motionReduced()?'instant':'brightness';const token=++changeToken;setTimeout(()=>{if(token===changeToken)stage.dataset.transition='idle';},motionReduced()?0:300);videoState();}
document.querySelectorAll('a[href^="#world-"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const i=Number(a.hash.split('-').pop())-1;selectScene(i);if(a.classList.contains('skip'))stage.focus();}));
stage.addEventListener('keydown',e=>{if(e.target.closest('button,a,input'))return;if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();selectScene(e.key==='Home'?0:e.key==='End'?2:current+(e.key==='ArrowRight'?1:-1));}});
chapters.forEach((a,i)=>a.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();selectScene(i+(e.key==='ArrowRight'?1:-1));chapters[current].focus();}}));
let touchStart=null;stage.addEventListener('touchstart',e=>{touchStart=e.touches.length===1?[e.touches[0].clientX,e.touches[0].clientY]:null;},{passive:true});stage.addEventListener('touchend',e=>{if(!touchStart)return;const dx=e.changedTouches[0].clientX-touchStart[0],dy=e.changedTouches[0].clientY-touchStart[1];if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy)*1.2)selectScene(current+(dx<0?1:-1));touchStart=null;},{passive:true});
videos.forEach((v,i)=>v.addEventListener('ended',()=>{if(i===current&&!paused&&!motionReduced())selectScene(current+1);}));
motion.addEventListener('click',()=>{paused=!paused;videoState();});sound.addEventListener('click',async()=>{if(!audio.paused){audio.pause();return;}try{await audio.play();status.textContent='官网原始 BGM · 未公开曲名';}catch{status.textContent='音频无法播放，请再次点击 SOUND';}});function audioState(){sound.setAttribute('aria-pressed',String(!audio.paused));sound.textContent=audio.paused?'♫ SOUND OFF':'♫ SOUND ON';}['play','pause'].forEach(e=>audio.addEventListener(e,audioState));
new IntersectionObserver(es=>{stageVisible=es[0].intersectionRatio>=.25;videoState();},{threshold:.25}).observe(stage);document.addEventListener('visibilitychange',()=>{if(document.hidden)audio.pause();videoState();});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',()=>{if(motionReduced())paused=true;videoState();});
const initial=Number(location.hash.split('-').pop())-1;selectScene(initial>=0&&initial<3?initial:0,{hash:false,restart:false});
