// A query override makes the reduced-motion branch reviewable without changing browser settings.
const motionOverride=new URLSearchParams(location.search).get('motion')==='reduce';
if(motionOverride)document.documentElement.dataset.motion='reduce';
function motionReduced(){return motionOverride||matchMedia('(prefers-reduced-motion: reduce)').matches;}
const video=document.querySelector('#background-video'),motionButton=document.querySelector('#motion-toggle'),reduce=matchMedia('(prefers-reduced-motion: reduce)');
function mediaState(){const playing=!video.paused&&!video.ended;motionButton.setAttribute('aria-pressed',String(playing));motionButton.textContent=playing?'Ⅱ 背景映像を停止':'▶ 背景映像を再生';}
video.addEventListener('loadedmetadata',()=>{video.currentTime=Math.min(.1,video.duration||.1);if(!motionReduced()&&backgroundVisible&&!document.hidden)video.play().catch(mediaState);});['play','pause','ended'].forEach(type=>video.addEventListener(type,mediaState));motionButton.addEventListener('click',async()=>{if(video.paused){try{await video.play();}catch{motionButton.textContent='再生できません · もう一度';motionButton.setAttribute('aria-pressed','false');}}else video.pause();});reduce.addEventListener('change',()=>{if(reduce.matches)video.pause();});
const menu=document.querySelector('#primary-nav'),toggle=document.querySelector('#menu-toggle');function closeMenu(){menu.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','メニューを開く');}toggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'メニューを閉じる':'メニューを開く');});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.querySelectorAll('a').forEach(l=>l.classList.remove('active'));a.classList.add('active');closeMenu();}));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
const resources=[{image:'help-enter.69f99d8a.png',category:'OFFICIAL HELP',title:'先生お悩み相談室',description:'公式のヘルプページへ。ゲームに関する案内とFAQを確認できます。',link:'https://bluearchive.jp/help'},{image:'comicEntry.2de61182.png',category:'OFFICIAL COMIC',title:'あおはるレコード',description:'公式ホームから案内されているコミック入口。キャラクターの日常へつながります。',link:'https://bluearchive.jp/comics02'},{image:'ffcLogo.f1e83d2f.png',category:'OFFICIAL FOUR-PANEL COMIC',title:'ぶるーあーかいぶっ！',description:'公式の4コマコミックへ。学園世界を遊びのあるイラストで紹介する入口です。',link:'https://bluearchive.jp/comics'}];
document.querySelectorAll('[data-resource]').forEach(button=>button.addEventListener('click',()=>{const r=resources[Number(button.dataset.resource)];document.querySelector('#resource-image').src='assets/'+r.image;document.querySelector('#resource-image').alt=r.title+' 公式入口';document.querySelector('#resource-category').textContent=r.category;document.querySelector('#resource-title').textContent=r.title;document.querySelector('#resource-description').textContent=r.description;document.querySelector('#resource-link').href=r.link;document.querySelectorAll('[data-resource]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));}));

const students=[{name:'シロコ',cv:'小倉唯',year:'2年',birthday:'5月16日',height:'156cm',art:'shiroko.png'},{name:'ホシノ',cv:'花守ゆみり',year:'3年',birthday:'1月2日',height:'145cm',art:'hoshino.png'},{name:'セリカ',cv:'大橋彩香',year:'1年',birthday:'6月25日',height:'153cm',art:'serika.png'},{name:'ノノミ',cv:'三浦千幸',year:'2年',birthday:'9月1日',height:'160cm',art:'nonomi.png'}];let student=0;const studentTrack=document.querySelector('.ba-character-track'),studentButtons=[...document.querySelectorAll('[data-student]')];students.forEach((s,i)=>{const panel=document.createElement('article');panel.className='ba-student';panel.innerHTML=`<div class="ba-student-card"><img class="card-school" src="assets/school-abydos-card.png" alt="アビドス"><h3>${s.name}</h3><p>CV: ${s.cv}</p><dl><dt>学園</dt><dd>アビドス高等学校</dd><dt>学年</dt><dd>${s.year}</dd><dt>誕生日</dt><dd>${s.birthday}</dd><dt>身長</dt><dd>${s.height}</dd></dl></div><img class="ba-student-art" src="assets/${s.art}" alt="${s.name} 公式立ち絵">`;studentTrack.append(panel);});function selectStudent(n){student=Math.max(0,Math.min(students.length-1,n));studentTrack.style.transform=`translate3d(${-student*100}%,0,0)`;studentTrack.dataset.student=String(student+1);[...studentTrack.children].forEach((p,i)=>{p.inert=i!==student;p.setAttribute('aria-hidden',String(i!==student));});studentButtons.forEach((b,i)=>b.setAttribute('aria-pressed',String(i===student)));document.querySelector('.ba-character-status').textContent=students[student].name+' / '+(student+1)+' of 4';}studentButtons.forEach((b,i)=>{b.addEventListener('click',()=>selectStudent(i));b.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();selectStudent(student+(e.key==='ArrowRight'?1:-1));studentButtons[student].focus();}});});document.querySelector('.ba-character-window').addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();selectStudent(student+(e.key==='ArrowRight'?1:-1));}});selectStudent(0);let backgroundVisible=true;new IntersectionObserver(es=>{backgroundVisible=es[0].intersectionRatio>=.15;if(!backgroundVisible)video.pause();},{threshold:.15}).observe(document.querySelector('#home'));document.addEventListener('visibilitychange',()=>{if(document.hidden)video.pause();});
