/* Geometry, camera projection, point shader and pointer force match the public Arknights WORLD modules. */
class WorldParticleField{
 constructor(canvas,reduced){this.canvas=canvas;this.reduced=reduced;this.paused=false;this.active=false;this.pointer={x:0,y:0,interactive:false};this.pointerSamples=0;this.modelKey='rhodes';this.detail=false;this.ready=this.init();}
 async init(){try{this.models=await (window.AtlasAssets?window.AtlasAssets.fetch('assets/world-models.json'):fetch('assets/world-models.json')).then(r=>r.json());const T=window.AKTHREE;this.scene=new T.xsS;this.camera=new T.cPb;this.renderer=new T.CP7({canvas:this.canvas,alpha:true});this.positions=new Float32Array(30000);this.colors=new Float32Array(40000);this.speeds=new Float32Array(10000);for(let i=0;i<10000;i++){this.positions[i*3]=(Math.random()-.5)*innerWidth;this.positions[i*3+1]=(Math.random()-.5)*innerHeight;this.positions[i*3+2]=(Math.random()-.5)*500;this.speeds[i]=20+Math.random()*10;this.colors[i*4+3]=-1;}this.aPosition=new T.TlE(this.positions,3);this.aColor=new T.TlE(this.colors,4);let geometry=new T.u9r;geometry.setAttribute('position',this.aPosition);geometry.setAttribute('color',this.aColor);const particleLoader=new T.dpR();let texture=await (window.AtlasAssets?window.AtlasAssets.load('assets/particle.png',url=>particleLoader.loadAsync(url)):particleLoader.loadAsync('assets/particle.png'));let material=new T.jyz({uniforms:{uTexture:new T.xWb(texture),uPointSize:new T.xWb(3)},vertexShader:'attribute vec4 color; varying vec4 vColor; uniform float uPointSize; void main(){vColor=color;vec4 mvPosition=modelViewMatrix*vec4(position,1.0);gl_PointSize=uPointSize;gl_Position=projectionMatrix*mvPosition;}',fragmentShader:'uniform sampler2D uTexture;varying vec4 vColor;void main(){vec4 texture=texture2D(uTexture,gl_PointCoord);gl_FragColor=vColor*texture;}',transparent:true,depthTest:false});this.scene.add(new T.woe(geometry,material));this.prepareHover(T);this.resize();this.setModel(this.modelKey,this.detail);this.canvas.dataset.renderer='official-three-webgl';this.canvas.dataset.pool='10000';this.tick=this.tick.bind(this);if(this.active)this.start();}catch(error){this.canvas.dataset.renderer='unavailable';document.querySelector('.world-note').textContent='此浏览器无法运行 WebGL 粒子场；世界设定仍可通过按钮访问。';console.warn('WORLD renderer unavailable',error.message);}}
 prepareHover(T){this.loader=new T.dpR;this.emptyTexture=new T.xEZ;this.previewMaterial=new T.jyz({transparent:true,uniforms:{offset:{value:200},offsetRadio:{value:new T.FM8(1.5,1.5)},speed:{value:new T.FM8(0,0)},u_texture:{value:this.emptyTexture}},vertexShader:'#define PI 3.1415926535897932384626433832795\nuniform vec2 speed;uniform vec2 offsetRadio;uniform float offset;varying vec2 vUv;float get_offest(float n,float aspect,float _offset){return cos((n-0.5)*PI/2.0)*aspect*_offset;}void main(){vUv=uv;vec3 c_position=position+vec3(get_offest(uv.y,speed.x,offsetRadio.x*offset),get_offest(uv.x,speed.y,offsetRadio.y*offset),0.0);vec4 mvPosition=modelViewMatrix*vec4(c_position,1.0);gl_Position=projectionMatrix*mvPosition;}',fragmentShader:'#define PI 3.1415926535897932384626433832795\nuniform sampler2D u_texture;uniform vec2 speed;uniform float offset;uniform vec2 offsetRadio;varying vec2 vUv;float get_offest(float n,float speed,float offset){return cos((n-0.5)*PI/2.0)*speed*offset;}void main(){vec2 uvR=vUv+vec2(get_offest(vUv.y,speed.x,offsetRadio.x*0.01),get_offest(vUv.x,speed.y,offsetRadio.y*0.01));vec2 colorR=texture2D(u_texture,uvR).ra;gl_FragColor=vec4(colorR.x*colorR.y,0.0,0.0,colorR.y);vec2 uvG=vUv+vec2(get_offest(vUv.y,speed.x,offsetRadio.x*0.02),get_offest(vUv.x,speed.y,offsetRadio.y*0.02));vec2 colorG=texture2D(u_texture,uvG).ga;gl_FragColor+=vec4(0.0,colorG.x*colorG.y,0.0,colorG.y);vec2 uvB=vUv+vec2(get_offest(vUv.y,speed.x,offsetRadio.x*0.03),get_offest(vUv.x,speed.y,offsetRadio.y*0.03));vec2 colorB=texture2D(u_texture,uvB).ba;gl_FragColor+=vec4(0.0,0.0,colorB.x*colorB.y,colorB.y);}'});this.preview=new T.Kj0(new T._12(1000,1000,100,100),this.previewMaterial);this.preview.visible=false;this.scene.add(this.preview);}
 hover(key){if(!this.preview||this.detail||this.reduced())return;const token=++this.previewToken|| (this.previewToken=1);this.hovered=true;this.preview.visible=true;this.preview.position.set(this.pointer.x,this.pointer.y,0);const previewURL='assets/'+key+'.png',load=url=>this.loader.loadAsync(url);(window.AtlasAssets?window.AtlasAssets.load(previewURL,load):load(previewURL)).then(t=>{if(this.previewToken===token&&this.hovered)this.previewMaterial.uniforms.u_texture.value=t;}).catch(()=>{});}
 unhover(){this.hovered=false;this.previewToken=(this.previewToken||0)+1;if(this.preview){this.preview.visible=false;this.previewMaterial.uniforms.u_texture.value=this.emptyTexture;}}
 resize(){if(!this.renderer)return;this.width=this.canvas.clientWidth;this.height=this.canvas.clientHeight;this.renderer.setSize(Math.round(this.width*devicePixelRatio),Math.round(this.height*devicePixelRatio),false);this.camera.near=110;this.camera.far=1000;this.camera.aspect=this.width/this.height;this.camera.fov=window.AKTHREE.M8C.radToDeg(2*Math.atan(this.height/2/160));this.camera.updateProjectionMatrix();this.camera.position.set(0,0,160);this.camera.lookAt(0,0,0);this.pointer.interactive=false;this.transform();}
 transform(){if(!this.width)return;const portrait=this.height>=this.width;const ratio=portrait?Math.min(this.width/750,this.height/1334):Math.min(this.width/1920,this.height/1080);this.scale=(this.detail?(portrait?1:1.2):1.8)*ratio;this.cx=this.detail?(portrait?-5.75*(16*ratio)*ratio:-.2*this.width):.15*this.width;this.cy=this.detail?(portrait?.15*this.height:.05*this.height):0;}
 setModel(key,detail){this.modelKey=key;this.detail=detail;this.unhover();if(!this.models)return;this.model=this.models[key];this.target=this.model.points.map(([x,y,a=255])=>[x-this.model.size.width/2,this.model.size.height/2-y,a/255]);for(let i=this.target.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[this.target[i],this.target[j]]=[this.target[j],this.target[i]];}this.transform();this.canvas.dataset.model=key;this.canvas.dataset.points=String(this.model.count);if(this.reduced()){this.settle();this.render();}else if(this.active)this.start();}
 move(event){const b=this.canvas.getBoundingClientRect();this.pointer={x:event.clientX-b.left-this.width/2,y:this.height/2-(event.clientY-b.top),interactive:true};this.pointerSamples++;this.canvas.dataset.pointerSamples=String(this.pointerSamples);if(this.active&&!this.reduced()&&!this.paused)this.start();}
 leave(){this.pointer.interactive=false;this.unhover();}
 settle(){if(!this.model)return;for(let i=0;i<10000;i++){let k=i*3,c=i*4,p=this.target[i];if(p){this.positions[k]=p[0]*this.scale+this.cx;this.positions[k+1]=p[1]*this.scale+this.cy;this.positions[k+2]=0;this.colors.set([1,1,1,p[2]],c);}else this.colors[c+3]=-1;}this.aPosition.needsUpdate=true;this.aColor.needsUpdate=true;this.canvas.dataset.displacement='0';}
 update(){let displacement=0;for(let i=0;i<10000;i++){const k=i*3,c=i*4,s=1/this.speeds[i],p=this.target[i];if(!p){this.colors[c+3]+=(-1-this.colors[c+3])*s;continue;}const tx=p[0]*this.scale+this.cx,ty=p[1]*this.scale+this.cy;const gx=this.pointer.interactive?this.pointer.x-this.positions[k]:0,gy=this.pointer.interactive?this.pointer.y-this.positions[k+1]:0,d=Math.sqrt(gx*gx+gy*gy),v=1/(1+d)/(1+d);this.positions[k]+=(tx-this.positions[k])*s-100*gx*v;this.positions[k+1]+=(ty-this.positions[k+1])*s-100*gy*v;this.positions[k+2]+=(0-this.positions[k+2])*s;for(let n=0;n<3;n++)this.colors[c+n]+=(1-this.colors[c+n])*s;this.colors[c+3]+=(p[2]-this.colors[c+3])*s;displacement+=Math.hypot(this.positions[k]-tx,this.positions[k+1]-ty);}this.aPosition.needsUpdate=true;this.aColor.needsUpdate=true;this.canvas.dataset.displacement=(displacement/this.model.count).toFixed(2);if(this.hovered&&this.preview){let dx=this.pointer.x-this.preview.position.x,dy=this.pointer.y-this.preview.position.y,len=Math.hypot(dx,dy),speed=Math.max(Math.min(len/24,100),.03),f=len>.72?speed/len:0,ax=Math.abs(dx)<.72?0:dx*f,ay=Math.abs(dy)<.72?0:dy*f;this.preview.position.x+=ax;this.preview.position.y+=ay;this.previewMaterial.uniforms.speed.value.set(ax/24,ay/24);}}
 render(){if(this.renderer)this.renderer.render(this.scene,this.camera);}
 tick(){this.raf=null;if(!this.active||this.paused||document.hidden)return;if(this.reduced()){this.settle();this.render();return;}if(this.model)this.update();this.render();this.raf=requestAnimationFrame(this.tick);}
 start(){if(!this.renderer||this.raf||this.paused||document.hidden)return;this.raf=requestAnimationFrame(this.tick);}
 setActive(active){this.active=active;this.canvas.dataset.active=String(active);if(active){this.resize();this.start();}else{if(this.raf)cancelAnimationFrame(this.raf);this.raf=null;this.leave();}}
 setPaused(paused){this.paused=paused;if(paused){if(this.raf)cancelAnimationFrame(this.raf);this.raf=null;this.unhover();}else if(this.active)this.start();this.canvas.dataset.paused=String(paused);}
}
