const motionOverride=new URLSearchParams(location.search).get('motion')==='reduce';
if(motionOverride)document.documentElement.dataset.motion='reduce';
const mediaQuery=matchMedia('(prefers-reduced-motion: reduce)');
function motionReduced(){return motionOverride||mediaQuery.matches;}
const bgm=document.querySelector('#bgm'),sound=document.querySelector('#sound'),voiceAudio=document.querySelector('#voice-audio'),voiceButton=document.querySelector('#voice'),status=document.querySelector('#audio-status'),video=document.querySelector('#home-video'),motion=document.querySelector('#motion');
let paused=motionReduced(),homeVisible=false,audioFade=null,audioFadeResolve=null;
function motionState(){if(paused||document.hidden||!homeVisible)video.pause();else video.play().catch(()=>{status.textContent='点击播放画面以启动静音PV'});motion.textContent=paused?'▷ 播放动态':'Ⅱ 暂停动态';motion.setAttribute('aria-pressed',String(paused));}
function cancelBgmFade(){if(audioFade!==null)cancelAnimationFrame(audioFade);audioFade=null;if(audioFadeResolve){audioFadeResolve(false);audioFadeResolve=null;}}
function fadeBgm(to,duration){cancelBgmFade();const from=bgm.volume,start=performance.now();bgm.dataset.fade=to?'in':'out';bgm.dataset.fadeDuration=String(duration);return new Promise(resolve=>{audioFadeResolve=resolve;function step(now){const p=Math.max(0,Math.min((now-start)/duration,1));bgm.volume=Math.max(0,Math.min(from+(to-from)*p,1));bgm.dataset.volume=bgm.volume.toFixed(3);bgm.dataset.fadeProgress=p.toFixed(3);if(p<1)audioFade=requestAnimationFrame(step);else{audioFade=null;audioFadeResolve=null;bgm.dataset.fade='idle';resolve(true);}}audioFade=requestAnimationFrame(step);});}
let audioDesired=false,audioSerial=0;
sound.addEventListener('click',async()=>{const serial=++audioSerial;audioDesired=!audioDesired;if(!audioDesired){sound.setAttribute('aria-pressed','false');sound.setAttribute('aria-label','播放官网背景音乐');status.textContent='SOUND OFF';await fadeBgm(0,300);if(serial===audioSerial&&!audioDesired)bgm.pause();return;}try{if(bgm.paused)bgm.volume=0;await bgm.play();if(serial!==audioSerial)return;sound.setAttribute('aria-pressed','true');sound.setAttribute('aria-label','关闭官网背景音乐');status.textContent='原站 BGM · 未见公开曲名';fadeBgm(1,600);}catch{audioDesired=false;status.textContent='BGM 播放失败，请再次点击';sound.setAttribute('aria-pressed','false');}});
function bgmState(){const playing=!bgm.paused&&!bgm.ended;sound.setAttribute('aria-pressed',String(playing));sound.setAttribute('aria-label',playing?'关闭官网背景音乐':'播放官网背景音乐');}
['play','pause','ended'].forEach(e=>bgm.addEventListener(e,bgmState));bgmState();

const operators=[{cn:'凯尔希',en:"KAL'TSIT",art:'kaltsit',actor:'日笠阳子',voice:'kaltsit-voice.wav',bio:'罗德岛最高管理者之一，阿米娅的直接辅导者。罗德岛医疗部门的总负责人。作为罗德岛的老成员，凯尔希医生是在阿米娅背后最稳固的援护者。'},{cn:'阿米娅',en:'AMIYA',art:'amiya',actor:'黑泽朋世',voice:'amiya-voice.mp3',bio:'罗德岛公开的领袖，在组织与伙伴们的帮助下，努力为感染者寻求新的道路。此处为档案的简短学习摘要。'},{cn:'陈',en:"CH'EN",art:'chen',actor:'石上静香',voice:'chen-voice.mp3',bio:'龙门近卫局特别督察组的精英干员，以严谨的态度与出众的作战能力守护龙门。此处为角色背景的简短学习摘要。'}];let selected=0,elite=1;const choices=[...document.querySelectorAll('[data-operator]')],elites=[...document.querySelectorAll('[data-elite]')];
function renderOperator(){voiceAudio.pause();let o=operators[selected];document.querySelector('#name-en').textContent=o.en;document.querySelector('#outline-name').textContent=o.en;document.querySelector('#name-cn').textContent=o.cn;document.querySelector('#actor').textContent=o.actor;document.querySelector('#bio').textContent=o.bio;document.querySelector('#ghost-art').src='assets/'+o.art+'.png';const fig=document.querySelector('#operator-art');fig.src='assets/'+o.art+(elite===2?'-e2':'')+'.png';fig.alt=o.cn+'精英'+elite+'立绘';const f=selected===0?(elite===1?[.5078125,.2734375,-.390625,-.05859375,1.3]:[.52734375,.66015625,-.4375,-.369140625,1.3]):selected===1?(elite===1?[.4921875,.421875,-.3671875,-.203125,1.3]:[.5078125,.498046875,-.408203125,-.30859375,1.5]):(elite===1?[.6875,.154296875,-.3671875,-.10546875,1.3]:[.5078125,.498046875,-.408203125,-.30859375,1.5]);fig.style.transformOrigin=(f[0]*100)+'% '+(f[1]*100)+'%';fig.style.transform='translate('+(f[2]*100)+'%,'+(f[3]*100)+'%) scale('+f[4]+')';choices.forEach((b,i)=>b.setAttribute('aria-pressed',String(i===selected)));elites.forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.elite)===elite)));voiceButton.disabled=!o.voice;voiceButton.setAttribute('aria-label',o.voice?'播放'+o.cn+'官方日语语音':o.cn+'语音未单独下载');voiceButton.textContent='▷';operatorEntrance();}
choices.forEach((b,i)=>{b.addEventListener('click',()=>{selected=i;renderOperator()});b.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();selected=(selected+(e.key==='ArrowRight'?1:2))%3;renderOperator();choices[selected].focus()}})});elites.forEach(b=>b.addEventListener('click',()=>{elite=Number(b.dataset.elite);renderOperator()}));voiceButton.addEventListener('click',async()=>{if(!voiceAudio.paused){voiceAudio.pause();voiceButton.textContent='▷';return}let o=operators[selected];if(!o.voice)return;voiceAudio.src='assets/'+o.voice;try{await voiceAudio.play();voiceButton.textContent='Ⅱ';status.textContent=o.cn+' / 官网日语角色语音（非 BGM）'}catch{status.textContent='角色语音播放失败，请重新点击'}});function voiceState(){const o=operators[selected],playing=!voiceAudio.paused&&!voiceAudio.ended;voiceButton.textContent=playing?'Ⅱ':'▷';voiceButton.setAttribute('aria-label',o.voice?(playing?'暂停':'播放')+o.cn+'官方日语语音':o.cn+'语音未单独下载');}['play','pause','ended'].forEach(e=>voiceAudio.addEventListener(e,voiceState));

let operatorAnimations=[];
function operatorEntrance(){operatorAnimations.forEach(a=>a.cancel());if(motionReduced())return;const elements=[document.querySelector('.operator-sprite'),...document.querySelectorAll('.profile>.section-label,.operator-name,.voice,.bio,.operators')];operatorAnimations=elements.map((el,i)=>el.animate([{transform:'translateY(28px)',opacity:0},{transform:'translateY(0)',opacity:1}],{duration:500,delay:i*200,easing:'cubic-bezier(.22,1,.36,1)',fill:'backwards'}));}
const chapters=[...document.querySelectorAll('.stage')],nav=[...document.querySelectorAll('header nav a[href^="#"]')],deck=document.querySelector('#scene-deck'),frame=document.querySelector('#page-frame');
const chapterState={active:0,target:0,phase:'loading',queued:null,serial:0,completed:0,footer:false,booted:false};
const fields=[document.querySelector('#section-number'),document.querySelector('#section-count'),document.querySelector('#section-name')];
const particleField=new WorldParticleField(document.querySelector('#world-particles'),motionReduced);
function reportState(){deck.dataset.active=chapters[chapterState.active].id;deck.dataset.target=chapters[chapterState.target].id;deck.dataset.phase=chapterState.phase;deck.dataset.transitions=chapterState.completed;deck.dataset.queued=chapterState.queued===null?'':chapters[chapterState.queued].id;deck.dataset.serial=chapterState.serial;}
function setIndicator(index){fields[0].textContent=String(index).padStart(2,'0');fields[1].textContent='// '+String(index).padStart(2,'0')+' / 05';fields[2].textContent=chapters[index].dataset.name;}
let indicatorSerial=0;function animateIndicator(index,direction){const stamp=++indicatorSerial;fields.forEach(el=>el.getAnimations().forEach(a=>a.cancel()));if(motionReduced()){setIndicator(index);return [];}const values=[String(index).padStart(2,'0'),'// '+String(index).padStart(2,'0')+' / 05',chapters[index].dataset.name];return fields.map((el,i)=>{const out=el.animate([{transform:'translateY(0)',opacity:1},{transform:'translateY('+(-direction*32)+'px)',opacity:0}],{duration:300,delay:i*100,easing:'cubic-bezier(.455,.03,.515,.955)',fill:'forwards'});out.finished.then(()=>{if(stamp!==indicatorSerial)return;el.textContent=values[i];return el.animate([{transform:'translateY('+(direction*32)+'px)',opacity:0},{transform:'translateY(0)',opacity:1}],{duration:300,delay:200-i*100,easing:'cubic-bezier(.455,.03,.515,.955)',fill:'forwards'}).finished;}).catch(()=>{});return out;});}
function stableChapter(index){document.body.dataset.chapter=chapters[index].id;chapterState.active=index;chapterState.target=index;chapterState.phase='idle';chapters.forEach((s,i)=>{s.classList.toggle('active',i===index);s.classList.remove('incoming');s.inert=i!==index;s.setAttribute('aria-hidden',String(i!==index));s.style.clipPath='';});nav.forEach(a=>{if(a.hash==='#'+chapters[index].id)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});homeVisible=index===0;motionState();if(index!==2)voiceAudio.pause();particleField.setActive(index===3);if(index===3)worldResponsive();if(index===2)operatorEntrance();setIndicator(index);history.replaceState({},'',location.pathname+location.search+'#'+chapters[index].id);document.querySelector('#scene-status').textContent=chapters[index].dataset.name+' / '+String(index).padStart(2,'0');reportState();}
function showFooter(show){chapterState.footer=show;frame.classList.toggle('footer-visible',show);deck.dataset.footer=String(show);}
async function requestChapter(index,kind='nav'){index=Math.max(0,Math.min(chapters.length-1,index));if(!chapterState.booted){chapterState.target=index;reportState();return;}showFooter(false);if(chapterState.phase==='transition'){chapterState.queued=index===chapterState.target?null:index;reportState();return;}if(index===chapterState.active)return;const from=chapterState.active,dir=Math.sign(index-from),serial=++chapterState.serial;chapterState.target=index;chapterState.phase='transition';chapterState.queued=null;deck.dataset.direction=dir>0?'forward':'reverse';reportState();nav.forEach(a=>{if(a.hash==='#'+chapters[index].id)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});if(motionReduced()){chapterState.completed++;stableChapter(index);return;}const outgoing=chapters[from],incoming=chapters[index],duration=innerHeight>=innerWidth?600:1000;incoming.classList.add('incoming');incoming.inert=true;outgoing.inert=true;incoming.setAttribute('aria-hidden','false');deck.dataset.duration=duration;animateIndicator(index,dir);const start=dir>0?'inset(0 0 0 100%)':'inset(0 100% 0 0)',end=dir>0?'inset(0 100% 0 0)':'inset(0 0 0 100%)';const ease='cubic-bezier(.455,.03,.515,.955)';const a=incoming.animate([{clipPath:start},{clipPath:'inset(0 0 0 0)'}],{duration,easing:ease,fill:'forwards'}),b=outgoing.animate([{clipPath:'inset(0 0 0 0)'},{clipPath:end}],{duration,easing:ease,fill:'forwards'});try{await Promise.all([a.finished,b.finished]);}catch{}if(serial!==chapterState.serial)return;a.cancel();b.cancel();chapterState.completed++;const queued=chapterState.queued;stableChapter(index);chapterState.queued=null;if(queued!==null&&queued!==index)requestChapter(queued,'queued');}
function stepChapter(direction){if(!chapterState.booted)return;if(chapterState.footer){if(direction<0)showFooter(false);return;}if(chapterState.phase==='transition'){if(direction!==Number(deck.dataset.direction==='forward'?1:-1))requestChapter(chapterState.target+direction,'reverse-wheel');return;}if(chapterState.active===5&&direction>0){showFooter(true);return;}requestChapter(chapterState.active+direction,'wheel');}
function scrollingInner(target,direction){for(let el=target;el&&el!==deck;el=el.parentElement){const css=getComputedStyle(el);if(/auto|scroll/.test(css.overflowY)&&el.scrollHeight>el.clientHeight+1){if(direction>0&&el.scrollTop+el.clientHeight<el.scrollHeight-1||direction<0&&el.scrollTop>0)return true;}}return false;}
let wheelStamp=0;
deck.addEventListener('wheel',event=>{if(event.ctrlKey||Math.abs(event.deltaX)>Math.abs(event.deltaY)||Math.abs(event.deltaY)<4)return;const dir=Math.sign(event.deltaY);if(scrollingInner(event.target,dir))return;event.preventDefault();const now=performance.now();if(now-wheelStamp<180)return;wheelStamp=now;stepChapter(dir);},{passive:false});
let gesture=null;deck.addEventListener('touchstart',event=>{if(event.touches.length!==1)return;const t=event.touches[0];gesture={x:t.clientX,y:t.clientY,target:event.target};},{passive:true});deck.addEventListener('touchmove',event=>{if(!gesture||event.touches.length!==1)return;const t=event.touches[0],dx=t.clientX-gesture.x,dy=t.clientY-gesture.y;if(Math.abs(dx)>50){gesture=null;return;}if(Math.abs(dy)>50){const dir=dy<0?1:-1;if(!scrollingInner(gesture.target,dir)){event.preventDefault();stepChapter(dir);}gesture=null;}},{passive:false});deck.addEventListener('touchend',()=>gesture=null,{passive:true});
nav.forEach(a=>a.addEventListener('click',event=>{event.preventDefault();requestChapter(chapters.findIndex(s=>s.id===a.hash.slice(1)));document.querySelector('#chapter-nav').classList.remove('open');document.querySelector('#menu-toggle').setAttribute('aria-expanded','false');}));document.querySelectorAll('.scroll[href^="#"],.brand[href^="#"],.skip').forEach(a=>a.addEventListener('click',event=>{event.preventDefault();requestChapter(chapters.findIndex(s=>s.id===a.hash.slice(1)));}));
document.querySelector('#footer-next').addEventListener('click',()=>showFooter(!chapterState.footer));document.querySelector('#menu-toggle').addEventListener('click',()=>{const menu=document.querySelector('#chapter-nav'),open=menu.classList.toggle('open');document.querySelector('#menu-toggle').setAttribute('aria-expanded',String(open));});
document.addEventListener('keydown',event=>{if(event.defaultPrevented||/INPUT|TEXTAREA|SELECT/.test(event.target.tagName)||event.altKey||event.ctrlKey||event.metaKey)return;if(event.key==='Escape'){document.querySelector('#chapter-nav').classList.remove('open');document.querySelector('#menu-toggle').setAttribute('aria-expanded','false');if(chapterState.active===3&&innerWidth>innerHeight)closeWorld();showFooter(false);return;}if(chapterState.active===3&&worldDetail&&['ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();changeWorld(worldIndex+(event.key==='ArrowRight'?1:-1));return;}const down=['ArrowDown','PageDown'].includes(event.key),up=['ArrowUp','PageUp'].includes(event.key);if(down||up){event.preventDefault();stepChapter(down?1:-1);}else if(event.key==='Home'||event.key==='End'){event.preventDefault();requestChapter(event.key==='Home'?0:5,'keyboard');}});
window.addEventListener('hashchange',()=>{const index=chapters.findIndex(s=>s.id===location.hash.slice(1));if(index>=0)requestChapter(index,'history');});
const worlds=[['originiums','源石','ORIGINIUMS','大地被起因不明的天灾四处肆虐，经由天灾席卷过的土地上出现了大量的神秘矿物——“源石”。依赖于技术的进步，源石蕴含的能量投入工业后使得文明顺利迈入现代，与此同时，源石本身也催生出“感染者”的存在。'],['originium_arts','源石技艺','ORIGINIUM ARTS','源石被发现之后，人们发掘出一种通过它来施放一系列令物质改变原有性状的技术，这种技术被称为源石技艺，常被俗称为“法术”。源石技艺所运用的能源，一般被认为来自于源石本身。而人是否能施放法术，以及所能施放法术的形式、强度、效果等，通常受到先天具备的素质、后天对源石技艺的学习能力这两方面因素的制约。'],['reunion','整合运动','REUNION','无种族立场，极端排外的感染者组织。他们宣称“感染者应对自己的身份感到骄傲，积极去获取并使用属于自己的力量”。试图用最原始的手段去争夺世界的公正。以某座被摧毁的伟大城市为开端，医疗机构“罗德岛”的突然介入，令整个事态向着未知发展。'],['infected','感染者','INFECTED','被源石所感染的人。理论致死率100%，死亡时存在扩散传染性以及潜在危险能力，是各国隔离驱逐的目标。长久以来，没人告诉他们该如何渡过余生，如今伴随着一位颠覆者的出现，越来越多的感染者被纳入一场名为“整合运动”的反抗浪潮。'],['nomadic_city','移动城邦','NOMADIC CITY','建造在可移动设备上的城市。频繁发生且破坏力巨大的天灾，迫使几乎所有的国家，都需要采用定期迁移家园与聚落的方式进行躲避。而移动城市，正是在这种需求下慢慢诞生的。人们在迁徙的过程中，尝试将建筑和种种装置安设在移动设备之上，并不断地扩大载具的规模。在文明与技术的演变之下，人们最终创造出了十分庞大的移动城市。'],['rhodes_island','罗德岛','RHODES ISLAND','罗德岛制药公司作为感染者问题专家，聘用感染者，深入危险地区，通过种种手段，已经成功解决了数起感染者引发的事件。而今，他们将面对史无前例的感染者暴乱。在各个势力间游走，发掘不为人知的内幕，抵挡感染者的疯狂进攻，你的决策将决定罗德岛的方向。']];
const world=document.querySelector('#world'),worldButtons=[...document.querySelectorAll('[data-world]')],worldDots=[...document.querySelectorAll('[data-world-dot]')];let worldIndex=0,worldDetail=false,worldSerial=0,worldAnimations=[];
function renderWorldText(i){document.querySelector('#world-cn').textContent=worlds[i][1];document.querySelector('#world-name').textContent=worlds[i][2];document.querySelector('#world-copy').textContent=worlds[i][3];worldDots.forEach((b,n)=>b.setAttribute('aria-pressed',String(n===i)));document.querySelector('.world-nav i').style.left=(i*100/6)+'%';world.dataset.selected=String(i);}
function openWorld(i){worldDetail=true;world.dataset.detail='true';worldIndex=i;renderWorldText(i);particleField.setModel(worlds[i][0],true);if(!motionReduced()){worldAnimations.forEach(a=>a.cancel());worldAnimations=[...document.querySelectorAll('.world-text h3,.world-text h4,.world-text p')].map((el,n)=>el.animate([{transform:'translateY('+ (n===2?'-100%':'100%')+')',opacity:0},{transform:'translateY(0)',opacity:1}],{duration:600,delay:600+n*200,easing:'cubic-bezier(.25,.46,.45,.94)',fill:'backwards'}));}}
function closeWorld(){if(innerWidth<=innerHeight)return;worldDetail=false;world.dataset.detail='false';particleField.setModel('rhodes',false);worldButtons[worldIndex].focus({preventScroll:true});}
async function changeWorld(i){i=(i+6)%6;if(i===worldIndex)return;const dir=Math.sign(i-worldIndex),serial=++worldSerial;worldIndex=i;worldAnimations.forEach(a=>a.cancel());particleField.setModel(worlds[i][0],true);const elements=[...document.querySelectorAll('.world-text h3,.world-text h4,.world-text p')];if(motionReduced()){renderWorldText(i);return;}worldAnimations=elements.map((el,n)=>el.animate([{transform:'translateX(0)',opacity:1},{transform:'translateX('+(-dir*32)+'px)',opacity:0}],{duration:300,delay:n*100,easing:'cubic-bezier(.25,.46,.45,.94)',fill:'forwards'}));try{await Promise.all(worldAnimations.map(a=>a.finished));}catch{return;}if(serial!==worldSerial)return;worldAnimations.forEach(a=>a.cancel());renderWorldText(i);worldAnimations=elements.map((el,n)=>el.animate([{transform:'translateX('+(dir*32)+'px)',opacity:0},{transform:'translateX(0)',opacity:1}],{duration:300,delay:n*100,easing:'cubic-bezier(.25,.46,.45,.94)',fill:'backwards'}));}
worldButtons.forEach((b,i)=>{b.addEventListener('click',()=>openWorld(i));b.addEventListener('pointerenter',()=>particleField.hover(worlds[i][0]));b.addEventListener('focus',()=>{if(!worldDetail)particleField.hover(worlds[i][0]);});});document.querySelector('.world-list').addEventListener('pointerleave',()=>particleField.unhover());worldDots.forEach((b,i)=>b.addEventListener('click',()=>changeWorld(i)));document.querySelector('#world-prev').addEventListener('click',()=>changeWorld(worldIndex-1));document.querySelector('#world-next').addEventListener('click',()=>changeWorld(worldIndex+1));document.querySelector('#world-back').addEventListener('click',closeWorld);world.addEventListener('pointermove',e=>particleField.move(e));world.addEventListener('pointerleave',()=>particleField.leave());
function worldResponsive(){if(innerWidth<=innerHeight&&!worldDetail)openWorld(0);else if(!worldDetail)particleField.setModel('rhodes',false);}
window.addEventListener('resize',()=>{particleField.resize();if(chapterState.active===3)worldResponsive();});
const newsItems=[['公告','2026 // 10 / 07','[明日方舟]10月09日06:00版本更新停机维护公告','6242'],['活动','2026 // 10 / 03','[活动预告]SideStory「昨日海」限时活动即将开启','5101'],['公告','2026 // 09 / 29','[明日方舟]09月29日16:00闪断更新公告','8577']];document.querySelectorAll('[data-news]').forEach(button=>button.addEventListener('click',()=>renderNews(button.dataset.news)));
function renderNews(category){document.querySelectorAll('[data-news]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.news===category)));const items=category==='最新'?newsItems:newsItems.filter(n=>n[0]===category);document.querySelector('#news-list').innerHTML=items.length?items.map(([cat,date,title,id])=>'<a href="https://ak.hypergryph.com/news/'+id+'" target="_blank" rel="noopener"><b>'+cat+'</b><small>'+date+'</small>'+title+'</a>').join(''):'<a href="https://ak.hypergryph.com/news" target="_blank" rel="noopener">查看官方新闻目录 ↗</a>';}
renderNews('最新');motion.addEventListener('click',()=>{paused=!paused;motionState();particleField.setPaused(paused);});
mediaQuery.addEventListener('change',()=>{if(motionReduced()){paused=true;operatorAnimations.forEach(a=>a.cancel());worldAnimations.forEach(a=>a.cancel());}particleField.setPaused(paused);motionState();});document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelBgmFade();audioDesired=false;audioSerial++;bgm.pause();voiceAudio.pause();status.textContent='页面离开前台 · 音频已暂停';}particleField.setActive(chapterState.active===3);motionState();});
renderOperator();
async function boot(){const initial=chapters.findIndex(s=>s.id===location.hash.slice(1));chapterState.target=initial>=0?initial:0;reportState();const loader=document.querySelector('#entry-loader'),bar=document.querySelector('#loading-bar'),percent=document.querySelector('#loading-percent');let loaded=0,progress=0,target=0,start=performance.now();const sources=['assets/background.jpg','assets/bg2.png','assets/common_mask.png','assets/home-poster.jpg','assets/rhodes-island.png'];const tasks=sources.map(src=>new Promise(resolve=>{let image=new Image;image.onload=image.onerror=()=>{loaded++;target=loaded/sources.length*100;resolve();};image.src=src;}));function draw(now){progress+=(target-progress)*.13;const value=Math.floor(progress);bar.style.width=value+'%';percent.textContent=value;if(value<99)requestAnimationFrame(draw);}requestAnimationFrame(draw);await Promise.all(tasks);await new Promise(resolve=>setTimeout(resolve,Math.max(0,1300-(performance.now()-start))));progress=target=100;bar.style.width='100%';percent.textContent='100';await new Promise(resolve=>setTimeout(resolve,300));chapterState.booted=true;stableChapter(chapterState.target);loader.setAttribute('aria-hidden','true');particleField.setPaused(paused);document.body.dataset.loaded='true';}
boot();
